### ISSUE TITLE
Unstable test suite (too lenient shutil.rmtree invocation?)

### ISSUE THREAD

**Issue by mcepl** [jelmer/dulwich#1000]
When building repeatedly package for this project for openSUSE/Tumbleweed we get very unstable tests, see for example 
this [build log](https://github.com/jelmer/dulwich/files/9383649/_log-dulwich.txt). If I read the log correctly then clean up of the testing artefacts uses `shutil.rmtree` without any flags, which may lead to the race condition, when the clean up method tries to remove a file which meanwhile vanished (because gpg-agent has been stopped, for example).

It seems to me that this [patch](https://github.com/jelmer/dulwich/files/9383665/rmtree-ignore-errors.patch.txt) could fix the problem by making `shutil.rmtree` ignoring such problems (we really don't need to be too much careful about it, because we want to get rid of those files anyway).

**Comment by jelmer** [comment]
Hmm, I see the issue. This just happen with gpg-agent files or other things as well? There's only a handful of gpg-related tests.

The problem with ignoring errors is t hat it's likely to cause the testsuite to leave files behind, especially on windows (where files may still exist be be in use, either due to changes in dulwich or for other reasons).

**Comment by jelmer** [comment]
For gpg-agent specifically, we could perhaps just get gpg to not use gpg-agent while running as part of the test suite.

**Comment by mcepl** [comment]
That’s possible. I have actually seen only this one log from the failed build. I was notified by @DimStar77 about the problem, so perhaps he knows more about it.

Of course, switching of gpg-agent (I cannot imagine what it could be good for for the automated tests) seems like even better idea.

**Comment by jelmer** [comment]
Actually, this seems to patch out all of the invocations to shutil.rmtree rather than just the one that's relevant for GNUPGHOME? Have you tried just fixing the latter ? I'd be more open to just changing that one.

**Comment by mcepl** [comment]
Which one it is?

**Comment by jelmer** [comment]
dulwich/tests/test_porcelain.py:280

**Comment by mcepl** [comment]
OK, I can confirm that just this patch seems to make situation more stable:
```diff
---
 dulwich/tests/test_porcelain.py |    2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

--- a/dulwich/tests/test_porcelain.py
+++ b/dulwich/tests/test_porcelain.py
@@ -271,7 +271,7 @@ ya6JVZCRbMXfdCy8lVPgtNQ6VlHaj8Wvnn2FLbWW
         super(PorcelainGpgTestCase, self).setUp()
         self.gpg_dir = os.path.join(self.test_dir, "gpg")
         os.mkdir(self.gpg_dir, mode=0o700)
-        self.addCleanup(shutil.rmtree, self.gpg_dir)
+        self.addCleanup(shutil.rmtree, self.gpg_dir, ignore_errors=True)
         self._old_gnupghome = os.environ.get("GNUPGHOME")
         os.environ["GNUPGHOME"] = self.gpg_dir
         if self._old_gnupghome is
```
