### ISSUE TITLE
Add musllinux wheels to the release process

### ISSUE THREAD

**Issue by n1ngu** [jelmer/dulwich#1007]
It would be nice to publish musllinux wheels to ease installation in MUSL platforms, namely python:alpine docker images. See https://peps.python.org/pep-0656/

https://cibuildwheel.readthedocs.io/en/stable/ is usually very convenient for this, but I see you are not using it?

Wrapping some Python tooling depending on dulwich in an Alpine Docker image is rather cumbersome right now because it involves either

- bloating the tool docker image with build dependencies when you are using alpine precisely to keep it as small as possible or
- getting messed up with multistage images

Having musllinux wheels available would be as easy as
```
FROM python:alpine
RUN pip install dulwich
```

**Comment by jelmer** [comment]
We're currently building wheels in .github/workflows/pythonwheels.yml; any chance that could be extended to build musl  images?

**Comment by nikolaik** [comment]
Made an attempt at this in #1037

**Comment by jelmer** [comment]
Thanks, @nikolaik !

Since your PR has landed, I believe this can be closed.
