### ISSUE TITLE
Intermittent access to documentation

### ISSUE THREAD

**Issue by TuringTux** [jelmer/dulwich#1016]
## Steps to reproduce

1. Access almost any page of the documentation, e.g. https://www.dulwich.io/docs/tutorial/index.html (only the main documentation index page seems to be exempt from the problem).
2. You might already see a "Not Found" error.
3. If not, reload the page. You should now see a "Not Found" error.

Interestingly enough, the page seems to be unavailable precisely every other time.

I'm happy to provide further information to help debug this issue – I hope it is not only a bug on my side, if so, I apologize for the inconvenience.

**Comment by jelmer** [comment]
Fixed, thanks!

**Comment by TuringTux** [comment]
Thank you for the quick reaction and fix!
