### ISSUE TITLE
Is it clean room/black box reverse engineered from git?

### ISSUE THREAD

**Issue by KOLANICH** [jelmer/dulwich#1023]
I mean, is it under GPL as git, its docs and everything derived from GPLed stuff is?

**Comment by jelmer** [comment]
Dulwich is an independent implementation, not derived from the C Git source code. "blackbox reverse engineered" could be read as decompilation or something like that - that's not really how. Most of the file format structure and protocols are fairly straightforward and well-documented across the internet (as well as in the Git technical docs).

**Comment by KOLANICH** [comment]
>Dulwich is an independent implementation, not derived from the C Git source code.

But the docs are also GPLed. When I have asked the maintainers to relicense the docs under a permissive one in order not to have to reverse engineer open source software (which is IMHO stupid and waste of time), Hamano [has told](https://public-inbox.org/git/xmqqeexbrffe.fsf@gitster-ct.c.googlers.com/) that that for him "it takes &lt;...&gt; some effort to convince &lt;himself&gt; that it is worth for us to spend extra brain cycles even thinking about making such statements" who "proclaim that they cannot be bothered to spend the necessary effort to comply with the license as a waste of time", where under "necessary effort" stands reverse engineering in a legally clean way.

>"blackbox reverse engineered" could be read as decompilation

No, decompilation is whitebox. Under a blackbox way is meant using programs as oracles consuming inputs and returning ouputs and then just making sense of the structure in the outputs via trial-and-error using hex editors, Python, Kaitai, `hexdump` and `diff`.
