### ISSUE TITLE
Unable to install https dependencies

### ISSUE THREAD

**Issue by rushilsrivastava** [jelmer/dulwich#1032]
After upgrading to `poetry` to `1.2.0`, which I understand uses `dulwich` internally, I started receiving this error on my local machine when trying to install git dependencies: 

```
ssh: Could not resolve hostname https: nodename nor servname provided, or not known
```

Disabling the `dulwich` using the [escape hatch](https://python-poetry.org/docs/configuration/#experimentalsystem-git-client) seemed to resolve this issue. This issue also seems to have plagued our CI/CD pipeline, so we've downgraded all `poetry` versions for the time being.

**Comment by jelmer** [comment]
Can you please provide more details about what's not working?

**Comment by rushilsrivastava** [comment]
> Can you please provide more details about what's not working?

When installing `poetry` dependencies from `git`, either via `poetry update` or `poetry install`, I get the following:

```
Updating dependencies
Resolving dependencies... (0.1s)

ssh: Could not resolve hostname https: nodename nor servname provided, or not known
```

**Comment by jelmer** [comment]
This is the dulwich bugtracker, so I'm in particular interested in:

* What version of Dulwich are you using?
* What Git repositories are you cloning? If they're private, e.g. what protocols and URL format are they using?
* Do you have custom config in ~/.gitconfig

**Comment by rushilsrivastava** [comment]
> * What version of Dulwich are you using?

The installed version is `0.20.45`; this is also the latest version specified in [Poetry](https://github.com/python-poetry/poetry/blob/master/pyproject.toml#L72).

> * What Git repositories are you cloning? If they're private, e.g. what protocols and URL format are they using?

Any GitHub repository is failing, for example [`pendulum`](https://github.com/sdispater/pendulum).

> * Do you have custom config in ~/.gitconfig

Yes, I didn't think I had anything relevant in there, but I have the following:
```
[url "git@github.com:"]
	insteadOf = https://github.com/
```

This is a duplicate of https://github.com/python-poetry/poetry/issues/6329, which seems to have already been resolved in master. Thanks for the help in pinpointing what was causing that. Any plans on another release soon?

**Comment by jelmer** [comment]
Yep - 0.20.46 is out now.
