### ISSUE TITLE
Consider delaying publishing PyPi release until wheels are ready

### ISSUE THREAD

**Issue by mrosales** [jelmer/dulwich#1034]
It appears that the release process is still underway, so I don't expect this to be a blocking issue (for long), but it seems like the PyPi `tar.gz` for `0.20.46` was published before the wheels for that release were ready. This causes installs of `dulwich` that previously worked on systems/containers without a C compiler installed to suddenly fail.

In my case the issue was with the official Poetry installer, so it blocks any docker images that use poetry from being built, and I will file an issue there to consider pinning package versions for the initial install, but it would help stabilize the release process to make sure the package is only published to PyPi when all of the release artifacts are ready

**Comment by morbitech1** [comment]
+1

**Comment by theandrelima** [comment]
Currently experiencing pretty much the same as described by @mrosales

**Comment by kylebarron** [comment]
This appears to have happened because [the wheel upload failed on CI](https://github.com/jelmer/dulwich/runs/8211866231?check_suite_focus=true) and presumably the `sdist` is uploaded manually.

**Comment by kylebarron** [comment]
> it would help stabilize the release process to make sure the package is only published to PyPi when all of the release artifacts are ready

This would be a pretty simple update to the Github Actions file. You just need to add another build step to build the `sdist` and then ensure the [`publish`](https://github.com/jelmer/dulwich/blob/b2a69e079fa6a15223c670a584a92e1dd5c637e4/.github/workflows/pythonwheels.yml#L85) step requires both of the preceding `build` steps.

I have an example of that in one of my projects here: https://github.com/kylebarron/pymartini/blob/4774549ffa2051c4ddaa254aca191bedcc4d30c5/.github/workflows/build-wheels.yml#L33-L55

**Comment by jelmer** [comment]
> This appears to have happened because [the wheel upload failed on CI](https://github.com/jelmer/dulwich/runs/8211866231?check_suite_focus=true) and presumably the `sdist` is uploaded manually.

Yeah, sorry about that - I've now manually uploaded all the wheels files.

I'll leave this issue open to track the fixing of the github action.

**Comment by jelmer** [comment]
> > it would help stabilize the release process to make sure the package is only published to PyPi when all of the release artifacts are ready
> 
> This would be a pretty simple update to the Github Actions file. That file just needs another build step to build the `sdist` and then ensure the [`publish`](https://github.com/jelmer/dulwich/blob/b2a69e079fa6a15223c670a584a92e1dd5c637e4/.github/workflows/pythonwheels.yml#L85) step requires both of the preceding `build` steps.
> 
> I have an example of this in one of my projects here: https://github.com/kylebarron/pymartini/blob/4774549ffa2051c4ddaa254aca191bedcc4d30c5/.github/workflows/build-wheels.yml#L33-L55

I've considered this, but that makes it impossible to GPG sign the sdist tarball without uploading my private key to the cloud.

**Comment by jorgebodega** [comment]
I've been watching the PR and I'm not sure if there's a reason to execute 190 jobs.

```yml
on:
  push:
  pull_request:
  schedule:
    - cron: "0 6 * * *" # Daily 6AM UTC build
```

Whenever a commit is pushed on a PR that is already created, execute every job twice. Maybe this could be improved? Just for help.
