### ISSUE TITLE
Inconsistent checking of identities

### ISSUE THREAD

**Issue by sattlerc** [jelmer/dulwich#1068]
There appear to be two separate functions for checking identities (e.g. author, committer):
* [`dulwich.repo.check_user_identity`](https://github.com/jelmer/dulwich/blob/1668d09bf7547ce1b81b114793e5454dc9cf0adf/dulwich/repo.py#L216-L229)
* [`dulwich.objects.check_identity`](https://github.com/jelmer/dulwich/blob/1668d09bf7547ce1b81b114793e5454dc9cf0adf/dulwich/objects.py#L196-L215)

The first one is called in `Repo.do_commit`, the second one in `Commit.check`. They behave differently (in an incomparable manner) from each other and from git version 2.37.

| Example | check_identity | check_user_identity | git commit |
|---|---|---|---|
| `a <>` | accept | accept | accept |
| `a <> b` | reject | accept | accept |
| `a<>` | accept | reject | accept |
| `a<>b` | reject | reject | accept |
| `\0 <>` | accept | accept | reject |
| `\n <> b` | reject | accept | reject |
| `\n<>` | accept | reject | reject |
| `a` | reject | reject | reject |

What is the desired behaviour in this project?

**Comment by jelmer** [comment]
Commit.check is meant to behave similarly to "git fsck" rather than commit.

The aim is to be consistent with C git, so differences are probably bugs,

Do you have examples of text being present after <> that is not a timestamp?

**Comment by sattlerc** [comment]
> Commit.check is meant to behave similarly to "git fsck" rather than commit.

`git fsck` seems to [check](https://github.com/git/git/blob/v2.38.1/fsck.c#L777-L821) quite a bit more than `Commit.check` / `check_identity`. And it [checks](https://github.com/git/git/blob/v2.38.1/fsck.c#L745-L775) for null characters in headers.

> Do you have examples of text being present after <> that is not a timestamp?

No. I stumbled on this by analyzing commits that accidentally included characters like `\0\n<>` in author names (which were happily created by dulwich, but then rejected by GitHub in case of `\0` and `\n`).

Another thing I don't understand:
* In [`_parse_message`](https://github.com/jelmer/dulwich/blob/1668d09bf7547ce1b81b114793e5454dc9cf0adf/dulwich/objects.py#L652-L703) (used to parse commit messages, among other things), dulwich parses an encoding of newline characters (followed by a whitespace) in header lines. However, [`do_commit`](https://github.com/jelmer/dulwich/blob/4a91eed0ce54df3d708bdf3929c4de3ed3512649/dulwich/repo.py#L873-L1036) does not encode newline characters in author names in this way. In fact, C git does not seem to understand this encoding of newline characters at all.

**Comment by jelmer** [comment]
> > Commit.check is meant to behave similarly to "git fsck" rather than commit.
> 
> `git fsck` seems to [check](https://github.com/git/git/blob/v2.38.1/fsck.c#L777-L821) quite a bit more than `Commit.check` / `check_identity`. And it [checks](https://github.com/git/git/blob/v2.38.1/fsck.c#L745-L775) for null characters in headers.

Happy to merge PRs that add those checks to Commit.check as well.

**Comment by jelmer** [comment]
> Another thing I don't understand:\n\nIn _parse_message (used to parse commit messages, among other things), dulwich parses an encoding of newline characters (followed by a whitespace) in header lines. However, do_commit does not encode newline characters in author names in this way. In fact, C git does not seem to understand this encoding of newline characters at all.

Yes, not all headers are actually allowed to contain newlines by C git, and do_commit should reject newlines in author/committer identities consistent with C git.

**Comment by sattlerc** [comment]
> Yes, not all headers are actually allowed to contain newlines by C git, and do_commit should reject newlines in author/committer identities consistent with C git.

Do you have an example of headers where such newlines are permitted?

**Comment by jelmer** [comment]
> > Yes, not all headers are actually allowed to contain newlines by C git, and do_commit should reject newlines in author/committer identities consistent with C git.
> 
> Do you have an example of headers where such newlines are permitted?

Mergetag and gpgsig IIRC
