### ISSUE TITLE
Repo.get_walker confused about type of SHA

### ISSUE THREAD

**Issue by sattlerc** [jelmer/dulwich#1075]
[This](https://github.com/jelmer/dulwich/blob/eb409c082b7fd173c9633b481c67e96331083062/dulwich/repo.py#L774-L775) makes it seem `str` is expected, but in fact
```python
repo.get_walker(include = '0' * 40)
```
results in:
```
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by sattlerc** [comment]
Note that `Walker.__init__` already has this:
```python
        if isinstance(include, bytes):
            # TODO(jelmer): Really, this should require a single type.
            # Print deprecation warning here?
            include = [include]
```
So presumably [this](https://github.com/jelmer/dulwich/blob/eb409c082b7fd173c9633b481c67e96331083062/dulwich/repo.py#L774-L775) can just be deleted.

**Comment by jelmer** [comment]
object ids are always bytestrings in Dulwich

The line you're referencing is a remnant from when Dulwich supported Python 2; I've create a  PR to remove it. Thanks!
