### ISSUE TITLE
Allow custom symlink handling on Windows

### ISSUE THREAD

**Issue by bruchar1** [jelmer/dulwich#1169]
This is a follow up on #1005.

On poetry, I'm not able to add a git repository containing symlinks (https://github.com/python-poetry/poetry/issues/7798).

When I clone the git repository with the git client, it simply creates text files containing the path of the symlink. There should be a way to get similar behavior in dulwich.

**Comment by bruchar1** [comment]
In fact, it should probably simply honor the `core.symlinks` config: https://git-scm.com/docs/git-config#Documentation/git-config.txt-coresymlinks

**Comment by jelmer** [comment]
On Fri, Apr 14, 2023 at 06:48:43AM -0700, Charles Brunet wrote:
> In fact, it should probably simply honor the `core.symlinks` config: https://git-scm.com/docs/git-config#Documentation/git-config.txt-coresymlinks

I'd be open to supporting the core.symlinks config.
