### ISSUE TITLE
Poetry Installs Broken in dulwich==0.21.4.1

### ISSUE THREAD

**Issue by bayangan1991** [jelmer/dulwich#1174]
Hey @jelmer,

The currently released `dulwich==0.21.4.1` is being used by the `poetry>=1.4.0` package and is causing it to fail during install.

Would it be possible to get https://github.com/jelmer/dulwich/pull/1173 released asap to resolve this?

**Comment by jelmer** [comment]
Done now, hopefully this one is better..

**Comment by bayangan1991** [comment]
Thanks for the quick turnaround!
