### ISSUE TITLE
Problem with format string in agent_string

### ISSUE THREAD

**Issue by kyle-query** [jelmer/dulwich#1175]
I'm seeing intermittent failures in our CI when poetry attempts to install a package from a git repo URL.

```
  TypeError

  not all arguments converted during string formatting

  at ~/.local/venv/lib/python3.10/site-packages/dulwich/protocol.py:111 in agent_string
      107│ NAK_LINE = b"NAK\n"
      108│ 
      109│ 
      110│ def agent_string():
    → 111│     return ("dulwich/%d.%d.%d" % dulwich.__version__).encode("ascii")
      112│ 
      113│ 
      114│ def capability_agent():
      115│     return CAPABILITY_AGENT + b"=" + agent_string()
```

The problem stopped occurring after Installing dulwich==0.21.4 before installing poetry (which has a dependency on ^0.21.2). That leads me to believe the latest release (~13 hours ago) introduced this bug.

**Comment by jelmer** [comment]
The code you're quoting was changed in the latest release, 0.21.5 - so it's not the latest code.

Please reopen if you can still reproduce these issues with 0.21.5.
