### ISSUE TITLE
index.py does not support multiple IndexEntries with the same path name but different stages for merge

### ISSUE THREAD

**Issue by kevinhendricks** [jelmer/dulwich#1189]
Actual git includes stage information in its index and allows multiple IndexEntries with the exact same path.

The current index.py uses a dict with path as key and value of an IndexEntry.  This only allows a path to exist in an index a single time.  During merge to represent merge conflicts, the real git index uses the concept of a "stage" where stage 0 represents the normal file, stage 1 represents the "ancestor" version of the file, stage 2 represents the "this" version of the file and stage 3 represents the "other".  So up to 3 different entries all with the same path but different stage value must be able to exist in the index at the same time when a merge conflict is detected.    The stage value is encoded in the entry flags with STAGEMASK  and STAGESHIFT values.

Unfortunately actual git uses a hash map to store path values and can therefore allow multiple entries in the same hashmap bucket and see them as distinct.  This approach is not easily repeatable in python unless we decide to make each Index dict value a list or tuple.  

By examining other python implementations such as: 

https://github.com/gitpython-developers/GitPython/tree/main/git/index

they decided to use a dict whose key is a tuple of (path, stage) so that multiple entries with the same path are not an issue.

Using that approach as inspiration, I have modified index.py to support using a ._bynamestage dict that can take either a single path key (defaulting to stage 0 if no conflict or stage 2 "this" otherwise) or a key that is a tuple of path and stage.

By using this approach you can make an index backwards compatible with the the old index while internally properly allowing conflict stage info to exist as it does in real git.

I have attached a zip with both this new index.py version and an updated test_index.py that directly tests the write_index_as_dict.

With these in place, dulwich master passes all make check tests.

Making this part of dulwich master allows work on an external  dulwich_merge capability to continue that I hope one day will make it into dulwich itself.

Please take a look at it and let me know your thoughts when you get a free moment.

Thank you.

[index_stage_support.zip](https://github.com/jelmer/dulwich/files/11898316/index_stage_support.zip)

**Comment by jelmer** [comment]
I think it's just the Index object that is problematic, the other functions for reading and writing index entries are fine?

Please create a pull request (perhaps draft)? zip files are hard to read and provide feedback on.

**Comment by kevinhendricks** [comment]
Yes the index object itself and its set and get item, iterators as well as read dict and write as dict are impacted.

I will create a clean repo from dulwich master, add in the changed pieces and create a PR for you tomorrow.

**Comment by kevinhendricks** [comment]
Had some time after dinner this evening so here is the promised pull request:

https://github.com/jelmer/dulwich/pull/1190

**Comment by kevinhendricks** [comment]
FYI: Fixed the flake8 and mypy typing issues

**Comment by kevinhendricks** [comment]
I started trying to modify dulwich_merge to use your new index.py and just noticed you removed the interface to set conflicts:

```
   def set_merge_conflict(self, apath, stage, mode, sha, time):
        entry = IndexEntry(time,
                           time,
                           0,
                           0,
                           mode,
                           0,
                           0,
                           0,
                           sha,
                           stage << FLAG_STAGESHIFT,
                           0)
        if (apath, 0) in self._bynamestage:
            del self._bynamestage[(apath, 0)]
        self._bynamestage[(apath, stage)] = entry
```

The merge code would have to literally build 3 IndexEntry objects and then create a ConflictedIndexEntry and manually load it into the .byname dict and write out the index.  All of that breaks any encapsulation done by the Index class.

Would it be possible to put something like it back so that index.py again encapsulates the code for creating ConflictEntries?  The merge code really should not need to incorporate internal pieces of the index just to do that.

If not, I can of course import what I need to work around it but this type of method or similar ones exist in the actual git index and libgit2 index classes.

Thanks,

Kevin

**Comment by kevinhendricks** [comment]
And I still would like to hear your thoughts/plans for our dulwich_merge code when you get a free moment.  

Specifically, can you see this merge code ever being integrated into dulwich master or not?  

FYI, the current dulwich_merge  codebase currently passes all of the merge recursive tests from the libgit2 and was used to actually merge two branches of Sigil for our next release.  That took a lot of infrastructure code to get it to do that (myers diff, histogram diff, 3-way merge, and routines to properly recursively merge multiple LCAs to create virtual base/ancestor commits).

But based on the 3 year delay from my prior attempt to help push things forward, and your delay in responding to my earlier related posts, you seem very reluctant to add a merge capability to dulwich and I am truly unsure as to why.  Am I mistaken?

If this is something you do not want and I am just wasting my time trying to help, or if my help is unwanted for any reason, please do just let me know.

Thanks.

Kevin

**Comment by kevinhendricks** [comment]
Here are some changes needed to make your index.py work with merge just like the index.py I submitted in the PR.

The main changes are:

1. change the Stage enum to inherit from IntEnum so conversion back and force using int() works
2. put back a version of the set_merge_conflict routine
3. a bug fix needed for lookup_entry in changes_from_tree for when ConflictedIndexEntries actually exist

FYI, more changes to handle ConflictedIndexEntries might be needed downstream in porcelain ls_files and other places that directly access the index dict using  __getitem__ as my original version checked for stages > 0 and returned only stage 2  (this_entry) in those case if it existed just to prevent the need for downstream changes.  That all went away with your redesign from what I can tell.

Hope this helps.

Kevin


```
diff -u ~/Desktop/index.py index.py
--- /Users/kbhend/Desktop/index.py	2023-07-24 10:49:12
+++ index.py	2023-07-24 12:28:28
@@ -25,7 +25,7 @@
 import struct
 import sys
 from dataclasses import dataclass
-from enum import Enum
+from enum import IntEnum
 from typing import (
     Any,
     BinaryIO,
@@ -72,7 +72,7 @@
 DEFAULT_VERSION = 2
 
 
-class Stage(Enum):
+class Stage(IntEnum):
     NORMAL = 0
     MERGE_CONFLICT_ANCESTOR = 1
     MERGE_CONFLICT_THIS = 2
@@ -495,6 +495,27 @@
                 return True
         return False
 
+    def set_merge_conflict(self, base_entry, base_time, this_entry, this_time, other_entry, other_time):
+        path, base_index_entry, this_index_entry, other_index_entry = None, None, None, None
+        if this_entry:
+            path = this_entry.path
+            this_index_entry = IndexEntry(this_time, this_time, 0, 0, this_entry.mode,
+                                          0, 0, 0, this_entry.sha)
+        if base_entry:
+            if not path:
+                path = base_entry.path
+            base_index_entry = IndexEntry(base_time, base_time, 0, 0, base_entry.mode,
+                                          0, 0, 0, base_entry.sha)
+        if other_entry:
+            if not path:
+                path = other_entry.path
+            other_index_entry = IndexEntry(other_time, other_time, 0, 0, other_entry.mode,
+                                           0, 0, 0, other_entry.sha)
+        if path:         
+            self._byname[path] = ConflictedIndexEntry(ancestor=base_index_entry, 
+                                                      this=this_index_entry, 
+                                                      other=other_index_entry)
+
     def clear(self):
         """Remove all contents from this index."""
         self._byname = {}
@@ -533,6 +554,8 @@
 
         def lookup_entry(path):
             entry = self[path]
+            if isinstance(entry, ConflictedIndexEntry):
+                entry = entry.this
             return entry.sha, cleanup_mode(entry.mode)
 
         yield from changes_from_tree(
```

**Comment by kevinhendricks** [comment]
@jelmer
I know you are probably busy, but would you please let me know about including the changes required for separate merge support (see diff above especially including the bug fix).

And please comment on your plans for eventually adding merge support to dulwich.

Without those, we (Sigil) will be forced to simply fork dulwich permanently and make our own releases and I truly do not want to do that!   Permanent forks are a headache I simply do not need.  But the complete lack of any feedback despite numerous requests and long 3 year delay leads us to believe there is no real interest on your part.

Thank you,

Kevin

**Comment by jelmer** [comment]
I've seen your message, will try to follow up this week.
