### ISSUE TITLE
type annotation and docstring disagree

### ISSUE THREAD

**Issue by dimbleby** [jelmer/dulwich#1205]
https://github.com/jelmer/dulwich/blob/1391db38c754ab15f2dcd498c295c025e5332672/dulwich/index.py#L455-L460

but if the object that is returned is a `ConflictedIndexEntry`, then it doesn't have any of the properties that the docstring asserts.

(context: https://github.com/python-poetry/poetry/blob/02448cf7f184dea204156f7dcb620a4f01a0068e/src/poetry/vcs/git/backend.py#L354, which does not typecheck with the newly published annotation).

**Comment by jelmer** [comment]
Thanks, clarified in the docstring.

Note that previously the behaviour of conflicted paths was a bit undefined. If you're not expecting to work with conflicts in your tree (as you might do when you're working with fresh clones) then you could probably just assert that the type is IndexEntry.

**Comment by dimbleby** [comment]
thanks - I guessed this was likely to get resolved in favour of the code, appreciate the fast confirmation
