### ISSUE TITLE
where did all the code since August go?!?

### ISSUE THREAD

**Issue by dimbleby** [jelmer/dulwich#1254]
this repository is currently showing that the last commit to master was in August.  But there has been lots of activity since then.

Has there been a mishap with a force push?

In case it helps to recover things:
- https://github.com/jelmer/dulwich/network shows https://github.com/AmirulAndalib/dulwich/ as a fork with everything up to and including #1252
- I have also taken a fork and pushed AmirulAndalib/master to dimbleby/master

**Comment by jelmer** [comment]
Not sure what happened there; it looks like maybe I pushed from an old branch. Either way, I've restored the branch and disabled force pushing on master.
