### ISSUE TITLE
worktreeConfig capitalization problem

### ISSUE THREAD

**Issue by wshanks** [jelmer/dulwich#1285]
dulwich only tests for `extensions.worktreeconfig` but in the [git documentation](https://git-scm.com/docs/git-worktree#_configuration_file) it is written as `extensions.worktreeConfig`. Recently, we started seeing [dulwich error in GitHub Actions](https://github.com/Qiskit-Extensions/qiskit-experiments/actions/runs/8786231049/job/24108610355#step:6:152) with `dulwich.repo.UnsupportedExtension: b'worktreeConfig'`. I tested locally and confirmed that `extensions.worktreeconfig` does not lead to an error from dulwich but `extensions.worktreeConfig` does.

I am not sure what is going on with GitHub Actions. I see that someone was affected by this in https://github.com/jelmer/dulwich/pull/1262 but then closed it as "fixed by git". Also, some other users have been having the opposite problem with GitHub Actions it seems: https://github.com/GitTools/actions/issues/1115. It seems like this setting is not consistent across GitHub Actions runs recently.

**Comment by 0x2b3bfa0** [comment]
> _[The variable names are case-insensitive, allow only alphanumeric characters and `-`, and must start with an alphabetic character.](https://www.git-scm.com/docs/git-config/2.14.6#_configuration_file)_

**Comment by wshanks** [comment]
After some more testing, I found that git itself is insensitive to the capitalization of config entries. So I think the issue is that dulwich is treating the config entry as it is in the file rather without lower casing it first and that #1262 would be the right solution.

**Comment by jelmer** [comment]
Couli you create a new PR, ideally with a unit test that reproduces the issue?

**Comment by shcheklein** [comment]
I think the easiest, less intrusive fix is to change this:


```python
        for extension, _value in config.items((b"extensions",)):
            if extension not in (b"worktreeconfig",):
                raise UnsupportedExtension(extension)
```

to something like:

```python
        for extension, _value in config.items((b"extensions",)):
            if extension.lower() not in (b"worktreeconfig",):
                raise UnsupportedExtension(extension)
```

`dulwich` is actually using `CaseInsensitiveOrderedMultiDict` internally, but `items` is iterating on an actual (real) keys.

It would be great to see if `items()` can be changed to return a nomalized list, but most likely there was a good reason for this.

**Comment by 0x2b3bfa0** [comment]
> _I think the easiest, less intrusive fix is to change this_ [...] _to something like_ [...]

* See https://github.com/jelmer/dulwich/pull/1262 linked above.

**Comment by shcheklein** [comment]
@jelmer would a simple fix like in https://github.com/jelmer/dulwich/issues/1285#issuecomment-2070908589 work?  can we merge it (add test and merge)?

**Comment by jelmer** [comment]
Yeah, just calling .lower() seems fine

**Comment by wshanks** [comment]
Here is my attempt: https://github.com/jelmer/dulwich/pull/1286

**Comment by jelmer** [comment]
> It would be great to see if `items()` can be changed to return a nomalized list, but most likely there was a good reason for this.

ConfigFile doesn't know about the fields and their supported values. We can't just lowercase all values returned from ConfigFile since that would also impact fields where case matters such as user.name

**Comment by 0x2b3bfa0** [comment]
> _We can't just lowercase all values returned from ConfigFile since that would also impact fields where case matters such as user.name_

It's not about converting **values** to lowercase, but **keys**, which as per the Git documentation should be case-insensitive; see https://github.com/jelmer/dulwich/issues/1285#issuecomment-2070895215.

**Comment by 0x2b3bfa0** [comment]
* Fix attempt at https://github.com/jelmer/dulwich/pull/1288

**Comment by jelmer** [comment]
> > _We can't just lowercase all values returned from ConfigFile since that would also impact fields where case matters such as user.name_
> 
> It's not about converting **values** to lowercase, but **keys**, which as per the Git documentation should be case-insensitive; see https://github.com/jelmer/dulwich/issues/1285#issuecomment-2070895215.

Case insensitive is not the same as has no case, it just means comparisons should ignore case.

**Comment by 0x2b3bfa0** [comment]
@jelmer, some of the methods of `CaseInsensitiveOrderedMultiDict` already normalize keys to lowercase; see https://github.com/jelmer/dulwich/pull/1288#issuecomment-2071694651 for more information.

Please take a look to these two alternative solutions, depending of whether you'd prefer to normalize keys to lowercase everywhere or just allow case-insensitive comparison:

* https://github.com/jelmer/dulwich/pull/1288
* https://github.com/jelmer/dulwich/pull/1289

If you deem https://github.com/jelmer/dulwich/pull/1286 enough, feel free to close both of my pull requests. Still, please keep in mind that this issue might arise again in the future with other configuration keys if we don't write an universal solution.

**Comment by wshanks** [comment]
Besides consistency between `items()`, `__iter__()`, and `keys()`, I think there is the potential for a bug with how `items()` works now:

https://github.com/jelmer/dulwich/blob/ed1a145ad045ca321a3a510689e07cbc503c31d2/dulwich/config.py#L91-L102

`CaseInsensitiveOrderedMultiDict.items()` iterates on `self._real` and `CaseInsensitiveOrderedMultiDict.__setitem__()` appends to `self._real`. So if an item gets set twice, it will remain twice in `self._real` and be yielded twice by `items()` while only appearing once in `keys()` and `__iter__()`. Since configuration does not change usually, maybe this does not come up, but maybe it does with loading the repo config on top of the global config? (And also maybe `worktreeConfig` which I hadn't known about before running into this error :slightly_smiling_face: ).
