### ISSUE TITLE
Suggest feature : get the files list of one folder in Index object ?

### ISSUE THREAD

**Issue by harobed** [jelmer/dulwich#129]
Hi,

in Index object, I think it would be good to have a method to get all file of one folder.

Example : 

```
>>> [i for i in index]
['index.html', 'folder1/a.html', 'folder1/b.html', 'folder2/c.html']
>>> index['/']
['index.html', 'folder1', 'folder2']
>>> index['folder1']
['a.html', 'b.html']
```

What are your comment about it ?

Best regards,
Stephane

**Comment by jelmer** [comment]
FWIW you could already do this using e.g.:

     [p for p in index if p.startswith('docs/')]

**Comment by jelmer** [comment]
I'm closing this as this should be easily possible with what I suggested in the last comment. Patches still welcome, if you really think we need a separate method for this.
