### ISSUE TITLE
dulwich.io Website and Documentation Down 

### ISSUE THREAD

**Issue by DaveLak** [jelmer/dulwich#1301]
Hey, it looks like https://dulwich.io is down. I'm not sure how long it's been down but the last [Internet Archive snapshot is from 2024-04-29](https://web.archive.org/web/20240429030518/https://www.dulwich.io/) so perhaps it's somewhat recent?

The last mention of the site/docs doing down was in https://github.com/jelmer/dulwich/issues/981 from 2022 so I figured I'd open this incase you weren't aware.

**Comment by henning** [comment]
I can add that I have seen it being down sometime last week, but didn't get to report it here.

Then next day or so, it was up again - so there was nothing to report.

But now and today  it's down again.

**Comment by jelmer** [comment]
This should be back now.

**Comment by DaveLak** [comment]
> This should be back now.

Looks like it, thanks!
