### ISSUE TITLE
Support git config proxy settings

### ISSUE THREAD

**Issue by shcheklein** [jelmer/dulwich#1368]
Inspired by https://github.com/iterative/dvc/issues/10563

I think it would be great to automatically support:

```
$ git config --global http.proxy http://proxy.address.com:port/
$ git config --global https.proxy http://proxy.address.com:port/
```

the same way it support `HTTP_PROXY` and `HTTPS_PROXY` .

**Comment by jelmer** [comment]
This is already supported, see https://github.com/jelmer/dulwich/blob/master/dulwich%2Fclient.py#L2165

**Comment by jelmer** [comment]
How are you using the Dulwich client library? Is there config being passed in, do you have a custom client library?

**Comment by shcheklein** [comment]
Yes, you are right, and I see that we do have a custom HTTP client (probably bc this was not merged https://github.com/jelmer/dulwich/pull/976 ). Let me see if there is a way to all pass proxy_headers there ...

**Comment by shcheklein** [comment]
Since it's not related to dulwich, let me close the ticket for now. Thanks @jelmer !

**Comment by jelmer** [comment]
> Yes, you are right, and I see that we do have a custom HTTP client (probably bc this was not merged https://github.com/jelmer/dulwich/pull/976 ). Let me see if there is a way to all pass proxy_headers there ...

Ah, sorry - I think that slipped off my radar.
