### ISSUE TITLE
Publish Python 3.13 wheels

### ISSUE THREAD

**Issue by edgarrmondragon** [jelmer/dulwich#1372]
Python 3.13 was released and support was added in https://github.com/jelmer/dulwich/commit/2f84f64b52da52a7c231df425004d2dcc502d826, so it's hopefully a matter of cutting a release to PyPI.

Thanks!

**Comment by jelmer** [comment]
https://github.com/jelmer/dulwich/actions/runs/11255354731

**Comment by edgarrmondragon** [comment]
It seems the linux wheels timed out 😕 

https://github.com/jelmer/dulwich/actions/runs/11255354731/job/31315806312

**Comment by jelmer** [comment]
I've restarted; hopefully this addresses it. We might have to either split the wheels builds further.
