### ISSUE TITLE
GPG signature verification fails incorrectly for commits with empty message

### ISSUE THREAD

**Issue by castedo** [jelmer/dulwich#1429]
I've hit this problem in my messy dev environment. I figure I should make a PR for a nice clean repo case as a unit test. Do you have a recommendation on where commit signature verification test cases should go?

An example of a GPG signed commit that I am 95% sure will fail incorrectly is this one:

https://archive.softwareheritage.org/api/1/revision/92b3f55bcec30906a39796c90018475bc1cbabb7/

I think the problem is the calling of `_format_message` with an argument of `self._message` to the _body_ parameter:

https://github.com/jelmer/dulwich/blob/e7e83d6e97f306c5d2963be7e370f85fe9f6f263/dulwich/objects.py#L1576

When the commit message is empty, I believe this causes the newline on this line:

https://github.com/jelmer/dulwich/blob/e7e83d6e97f306c5d2963be7e370f85fe9f6f263/dulwich/objects.py#L730

that is inside the if statement (instead of above it) to not get output (when it should). But when a signature-less commit is generated on this line:

https://github.com/jelmer/dulwich/blob/e7e83d6e97f306c5d2963be7e370f85fe9f6f263/dulwich/objects.py#L1531

the GPG signature verification will fail when the commit has an empty commit message, because a newline will be missing at the end.

**Comment by jelmer** [comment]
Tests for signatures should probably just live in dulwich.objects, probably as a separate testcase that calls skipTest in its setUp() if the gpg module is not present.

**Comment by castedo** [comment]
I've got a nice clean reproduction case for this issue based on the unit test case I just added for PR #1438.

STEPS:

From PR #1438, inside tests/compat/test_porcelain.py CommitCreateSignTestCase.test_verify, change the message string `"foo"` to simply an empty string `""`.

RESULT:
the `commit.verify()` and the unit test will fail.
