### ISSUE TITLE
PyPI package dependent on optional C-extension

### ISSUE THREAD

**Issue by nicklasb** [jelmer/dulwich#236]
Hi,
I have encountered a serious problem trying to "pip install dulwich" when trying to deploy on a windows client.

It seems that the custom C-extensions, that are mentioned as "optional" on the download page (http://www.samba.org/~jelmer/dulwich/) seems to actually be required, because the install fails and no files turns up in site-packages.

As clients usually doesn't have Visual Studio installed (*that* would be a strange requirement) this basically means that the package is uninstallable on non-developer windows boxes.

**Comment by jelmer** [comment]
I've added some notes about the use of --pure to README.

I'll close this issue. As mentioned before, if you do find some concrete pure-python code that could be optimized don't hesitate to open a new issue for that.

**Comment by nicklasb** [comment]
Thanks, great!
