### ISSUE TITLE
Failing to install from pip or easy_install

### ISSUE THREAD

**Issue by interstar** [jelmer/dulwich#242]
This may not be the right place for this, but when I try to install dulwich with either pip or easy_install on my machine I'm getting 

```
Searching for dulwich
Reading https://pypi.python.org/simple/dulwich/
Reading http://launchpad.net/dulwich
Reading http://samba.org/~jelmer/dulwich
Reading https://samba.org/~jelmer/dulwich
Best match: dulwich 0.9.8
Downloading https://pypi.python.org/packages/source/d/dulwich/dulwich-0.9.8.tar.gz#md5=854f711ea4f52d7dd20d9661bd394fab
Processing dulwich-0.9.8.tar.gz
Writing /tmp/easy_install-JiuIQ1/dulwich-0.9.8/setup.cfg
Running dulwich-0.9.8/setup.py -q bdist_egg --dist-dir /tmp/easy_install-JiuIQ1/dulwich-0.9.8/egg-dist-tmp-7kR0ow
dulwich/_objects.c:20:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.
error: Setup script exited with error: command 'i686-linux-gnu-gcc' failed with exit status 1
```

Any ideas?

**Comment by jelmer** [comment]
On Tue, Jan 06, 2015 at 03:36:43AM -0800, phil jones wrote:
> This may not be the right place for this, but when I try to install dulwich with either pip or easy_install on my machine I'm getting 
> 
> ```
> Searching for dulwich
> Reading https://pypi.python.org/simple/dulwich/
> Reading http://launchpad.net/dulwich
> Reading http://samba.org/~jelmer/dulwich
> Reading https://samba.org/~jelmer/dulwich
> Best match: dulwich 0.9.8
> Downloading https://pypi.python.org/packages/source/d/dulwich/dulwich-0.9.8.tar.gz#md5=854f711ea4f52d7dd20d9661bd394fab
> Processing dulwich-0.9.8.tar.gz
> Writing /tmp/easy_install-JiuIQ1/dulwich-0.9.8/setup.cfg
> Running dulwich-0.9.8/setup.py -q bdist_egg --dist-dir /tmp/easy_install-JiuIQ1/dulwich-0.9.8/egg-dist-tmp-7kR0ow
> dulwich/_objects.c:20:20: fatal error: Python.h: No such file or directory
>  #include <Python.h>
>                     ^
> compilation terminated.
> error: Setup script exited with error: command 'i686-linux-gnu-gcc' failed with exit status 1
> ```
> 
> Any ideas?
You need to have the python development headers installed. On Debian/Ubuntu,
these live in the python2.X-dev package.

Cheers,

Jelmer

**Comment by jelmer** [comment]
Or alternatively, you can install with --pure (but performance will be significantly worse). See the README.md file for details.
