### ISSUE TITLE
Fail to push mercurial repository to git

### ISSUE THREAD

**Issue by m00nlight** [jelmer/dulwich#244]
With mercurial 2.8.2, dulwich 0.9.8, hg-git 0.7.0.  

When push the mercurial repository to git, I get the following error:
```shell
searching for changes
54 commits found
adding objects
abort: git remote error: unpack index-pack abnormal exit
warning: post-push hook exited with status 255
```

My repository configuration file is something like this

```
[paths]
default = ssh://hg@bitbucket.org/username/project
github = git+ssh://git@github.com:username/project.git

[ui]
username = aaa <bb@cc.com>
verbose = True

[extensions]
hgext.bookmarks =
hggit =

[hooks]
post-push = if [ $HG_ARGS = "push" ]; then hg push github; fi
```

**Comment by jelmer** [comment]
On Fri, Jan 16, 2015 at 05:17:05PM -0800, m00nlight wrote:
> With mercurial 2.8.2, dulwich 0.9.8, hg-git 0.7.0.  
> 
> When push the mercurial repository to git, I get the following error:
> ```shell
> searching for changes
> 54 commits found
> adding objects
> abort: git remote error: unpack index-pack abnormal exit
> warning: post-push hook exited with status 255
> ```
Can you reproduce this with just dulwich? If not, please file a bug
against hg-git.

Cheers,

Jelmer

**Comment by m00nlight** [comment]
@jelmer How to do this only with dulwich? I only find tutorial to push mercurial repository with hg-git and dulwich.

Thanks

**Comment by jelmer** [comment]
On Fri, Jan 16, 2015 at 06:49:31PM -0800, m00nlight wrote:
> @jelmer How to do this only with dulwich? I only find tutorial to push mercurial repository with hg-git and dulwich.
dulwich has a command-line utility that behaves like git that you can
use.

Alternatively, please file a bug with hg-git and they can help you
forward the issue to dulwich if they believe it is a dulwich bug.

(I don't know much about hg-git or how to use it)

**Comment by m00nlight** [comment]
@jelmer OK. Thanks
