### ISSUE TITLE
test_dest_overflow fails with pypy

### ISSUE THREAD

**Issue by jlec** [jelmer/dulwich#259]
======================================================================
ERROR: test_dest_overflow (dulwich.tests.test_pack.TestPackDeltas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "dulwich/tests/test_pack.py", line 197, in test_dest_overflow
    apply_delta, 'a'*0x10000, '\x80\x80\x04\x80\x80\x04\x80' + 'a'*0x10000)
  File "/usr/lib64/pypy/lib-python/2.7/unittest/case.py", line 473, in assertRaises
    callableObj(*args, **kwargs)
  File "dulwich/pack.py", line 1733, in apply_delta
    raise ApplyDeltaError('delta not empty: %r' % delta[index:])
ApplyDeltaError: delta not empty: ''

----------------------------------------------------------------------

**Comment by jelmer** [comment]
On Sun, Mar 22, 2015 at 08:27:55AM -0700, Justin wrote:
> ======================================================================
> ERROR: test_dest_overflow (dulwich.tests.test_pack.TestPackDeltas)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "dulwich/tests/test_pack.py", line 197, in test_dest_overflow
>     apply_delta, 'a'*0x10000, '\x80\x80\x04\x80\x80\x04\x80' + 'a'*0x10000)
>   File "/usr/lib64/pypy/lib-python/2.7/unittest/case.py", line 473, in assertRaises
>     callableObj(*args, **kwargs)
>   File "dulwich/pack.py", line 1733, in apply_delta
>     raise ApplyDeltaError('delta not empty: %r' % delta[index:])
> ApplyDeltaError: delta not empty: ''

Thanks.

This should now be fixed in HEAD.

Jelmer
