### ISSUE TITLE
dulwich broken on Windows by 23eaa9164c

### ISSUE THREAD

**Issue by sborho** [jelmer/dulwich#266]
Windows doesn't have os.uname(), but it does have os.name or sys.platform

**Comment by jelmer** [comment]
Thanks, fixed.

**Comment by jelmer** [comment]
Unfortunately we don't have a good story for QA on Windows at the moment - none of the core developers of Dulwich is on Windows. If you have any thoughts on how to improve this (e.g. QA setup like travis) or can help out, please let us know.
