### ISSUE TITLE
`IndexError: bytearray index out of range` due to escaped quote in config

### ISSUE THREAD

**Issue by garyvdm** [jelmer/dulwich#305]
I tried to run `dulwich commit`. I get this error. This happens in both python2 and python3:

    garyvdm@garyvdm ~/dev/dulwich (git)-[master] % dulwich commit  --message "bar"
    Traceback (most recent call last):
      File "/home/garyvdm/dev/dulwich/ve34/bin/dulwich", line 6, in <module>
        exec(compile(open(__file__).read(), __file__, 'exec'))
      File "/home/garyvdm/dev/dulwich/bin/dulwich", line 381, in <module>
        commands[cmd](sys.argv[2:])
      File "/home/garyvdm/dev/dulwich/bin/dulwich", line 187, in cmd_commit
        porcelain.commit(".", message=opts["--message"])
      File "/home/garyvdm/dev/dulwich/dulwich/porcelain.py", line 167, in commit
        committer=committer)
      File "/home/garyvdm/dev/dulwich/dulwich/repo.py", line 568, in do_commit
        committer = self._get_user_identity()
      File "/home/garyvdm/dev/dulwich/dulwich/repo.py", line 498, in _get_user_identity
        config = self.get_config_stack()
      File "/home/garyvdm/dev/dulwich/dulwich/repo.py", line 388, in get_config_stack
        backends = [self.get_config()] + StackedConfig.default_backends()
      File "/home/garyvdm/dev/dulwich/dulwich/config.py", line 382, in default_backends
        cf = ConfigFile.from_path(path)
      File "/home/garyvdm/dev/dulwich/dulwich/config.py", line 326, in from_path
        ret = cls.from_file(f)
      File "/home/garyvdm/dev/dulwich/dulwich/config.py", line 306, in from_file
        value = _parse_string(value)
      File "/home/garyvdm/dev/dulwich/dulwich/config.py", line 182, in _parse_string
        ret.extend(_unescape_value(block))
      File "/home/garyvdm/dev/dulwich/dulwich/config.py", line 214, in _unescape_value
        ret.append(table[value[i]])
    IndexError: bytearray index out of range

**Comment by garyvdm** [comment]
This was happening due to a section in my git config added by gitk's preferences dialog.

    [gui]
        fontdiff = -family \"Ubuntu Mono\" -size 11 -weight normal -slant roman -underline 0 -overstrike 0

I've written a test (https://github.com/garyvdm/dulwich/blob/issue305/dulwich/tests/test_config.py#L153)

(I'm glad this is not caused by our python3 porting work.)

**Comment by jelmer** [comment]
This seems to be fixed in master; I've cherry-picked your tests and it passes.

**Comment by jelmer** [comment]
Fixed in master.

**Comment by guanzo** [comment]
my gitconfig seems to be crashing `poetry install` :/

```
$ cat ~/.gitconfig
[alias]
  c = '!f() { \
    printf '[git commit -m \"%s\"]\n' \"$*\" && \
    git commit -m \"$*\"; \
  }; f'
```        

```
$ poetry install
Installing dependencies from lock file

Package operations: 3 installs, 0 updates, 0 removals

  • Installing algofi-py-sdk (1.1.1 904a14d)
  • Installing algofi-python-sdk (2.1.2 fe57cc5)
  • Installing tinyman-py-sdk (0.0.6 40ca553)

  IndexError

  bytearray index out of range

  at ~\AppData\Local\Programs\Python\Python310\lib\site-packages\dulwich\config.py:413 in _parse_string
      409│         c = value[i]
      410│         if c == ord(b"\\"):
      411│             i += 1
      412│             try:
    → 413│                 v = _ESCAPE_TABLE[value[i]]
      414│             except IndexError:
      415│                 raise ValueError(
      416│                     "escape character in %r at %d before end of string" % (value, i)
      417│                 )

The following error occurred when trying to handle this error:


  ValueError

  escape character in bytearray(b"\'!f() { \\") at 9 before end of string

  at ~\AppData\Local\Programs\Python\Python310\lib\site-packages\dulwich\config.py:415 in _parse_string
      411│             i += 1
      412│             try:
      413│                 v = _ESCAPE_TABLE[value[i]]
      414│             except IndexError:
    → 415│                 raise ValueError(
      416│                     "escape character in %r at %d before end of string" % (value, i)
      417│                 )
      418│             except KeyError:
      419│                 raise ValueError(
```

This gitconfig line seems to be the issue `c = '!f() { \`. 

I'm using poetry on Windows and git bash.

**Comment by jelmer** [comment]
Please create a new issue rather than commenting on an old unrelated issue, and do also include the version of dulwich you're using.
