### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by fabaff** [jelmer/dulwich#307]
I'm speaking as a packager at the moment. 

Changing the versioning schema is really not a smart move (this will break the spec files for the packages of most distributions) and diverging on different platforms (0.10.1a on PyPi, 0.10.1 on Github) neither. Especially, in times with CVEs around, doesn't make this the life of the packagers easier.   

Can you please make statement about how the versioning schema will look like in the future?  

Thanks

**Comment by jelmer** [comment]
The versioning schema hasn't changed. The letter merely indicates there was a rebuild of the tarball before the release, for pypi (as it doesn't allow removing tarballs - even if they were never public).
