### ISSUE TITLE
Backtrace when using paramiko

### ISSUE THREAD

**Issue by inducer** [jelmer/dulwich#363]
On d63456d5a8e, using paramiko to access another git client via SSH is broken. It crashes with the traceback like the following:

```
Traceback (most recent call last):
  File "/home/andreas/work/django/relate/course/versioning.py", line 164, in set_up_new_course
    remote_refs = client.fetch(remote_path, repo)
  File "/home/andreas/pack/dulwich/dulwich/client.py", line 233, in fetch
    progress)
  File "/home/andreas/pack/dulwich/dulwich/client.py", line 537, in fetch_pack
    proto, can_read = self._connect(b'upload-pack', path)
  File "/home/andreas/pack/dulwich/dulwich/client.py", line 983, in _connect
    port=self.port, username=self.username)
  File "/home/andreas/work/django/relate/course/versioning.py", line 79, in run_command
    channel.exec_command(*command)
  File "/usr/lib/python2.7/dist-packages/paramiko/channel.py", line 60, in _check
    return func(self, *args, **kwds)
TypeError: exec_command() takes exactly 2 arguments (3 given)
```
(Yes, I know there are bits of my own code caught up in the backtrace, but hear me out.)

The issue is that `paramiko.Channel.exec_command` takes exactly one argument:
http://docs.paramiko.org/en/1.15/api/channel.html#paramiko.channel.Channel.exec_command

Yet, in `ParamikoSSHVendor.run_command`:
https://github.com/jelmer/dulwich/blob/master/dulwich/client.py#L955

this is called like so:
```
channel.exec_command(*command)
```

Which means if `command` (a list) contains more than one element, you get a crash like the above. As of https://github.com/jelmer/dulwich/commit/8de9604a8336585eb1d85768eb567a8e9fd99dea, `command` now actually contains multiple elements, which leads to the crash.

Changing that line to
```
channel.exec_command(" ".join(command))
```
seems to make things slightly better.

**Comment by jelmer** [comment]
According to that page, the signature of exec_command is:

exec_command(*args, **kwargs)

which implies it takes more than one argument.

Can you reproduce this with "plain" dulwich, e.g. by running:

$ dulwich clone git+ssh://github.com/jelmer/dulwich /tmp/dw

Cheers,

Jelmer

**Comment by inducer** [comment]
Yes, I can reproduce this crash with just plain command-line dulwich:

```
$ dulwich clone git@github.com:jelmer/dulwich dw
/usr/lib/python2.7/gettext.py:49: ImportWarning: Not importing directory '/home/andreas/work/django/relate/locale': missing __init__.py
  import locale, copy, os, re, struct, sys
Traceback (most recent call last):
  File "/home/andreas/src/env/bin/dulwich", line 5, in <module>
    pkg_resources.run_script('dulwich==0.10.2', 'dulwich')
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 492, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 1350, in run_script
  File "/home/andreas/src/env/lib/python2.7/site-packages/dulwich-0.10.2-py2.7-linux-x86_64.egg/EGG-INFO/scripts/dulwich", line 392, in <module>
    commands[cmd](sys.argv[2:])
  File "/home/andreas/src/env/lib/python2.7/site-packages/dulwich-0.10.2-py2.7-linux-x86_64.egg/EGG-INFO/scripts/dulwich", line 181, in cmd_clone
    porcelain.clone(source, target, bare=("--bare" in opts))
  File "/home/andreas/src/env/local/lib/python2.7/site-packages/dulwich-0.10.2-py2.7-linux-x86_64.egg/dulwich/porcelain.py", line 235, in clone
    progress=errstream.write)
  File "/home/andreas/src/env/local/lib/python2.7/site-packages/dulwich-0.10.2-py2.7-linux-x86_64.egg/dulwich/client.py", line 233, in fetch
    progress)
  File "/home/andreas/src/env/local/lib/python2.7/site-packages/dulwich-0.10.2-py2.7-linux-x86_64.egg/dulwich/client.py", line 537, in fetch_pack
    proto, can_read = self._connect(b'upload-pack', path)
  File "/home/andreas/src/env/local/lib/python2.7/site-packages/dulwich-0.10.2-py2.7-linux-x86_64.egg/dulwich/client.py", line 989, in _connect
    port=self.port, username=self.username)
  File "/home/andreas/src/env/local/lib/python2.7/site-packages/dulwich-0.10.2-py2.7-linux-x86_64.egg/dulwich/client.py", line 961, in run_command
    channel.exec_command(*command)
  File "/usr/lib/python2.7/dist-packages/paramiko/channel.py", line 60, in _check
    return func(self, *args, **kwds)
TypeError: exec_command() takes exactly 2 arguments (3 given)
```

In order to do so, I need to make the following changes to dulwich itself:
```diff
diff --git a/dulwich/client.py b/dulwich/client.py
index f43d106..1e5be3a 100644
--- a/dulwich/client.py
+++ b/dulwich/client.py
@@ -929,6 +929,12 @@ else:
             self.channel.close()
             self.stop_monitoring()
 
+    class AutoAcceptPolicy(paramiko.client.MissingHostKeyPolicy):
+        def missing_host_key(self, client, hostname, key):
+            # simply accept the key
+            return
+
+
     class ParamikoSSHVendor(object):
 
         def __init__(self):
@@ -943,7 +949,7 @@ else:
 
             client = paramiko.SSHClient()
 
-            policy = paramiko.client.MissingHostKeyPolicy()
+            policy = AutoAcceptPolicy()
             client.set_missing_host_key_policy(policy)
             client.connect(host, username=username, port=port,
                            **self.ssh_kwargs)
@@ -959,7 +965,7 @@ else:
 
 
 # Can be overridden by users
-get_ssh_vendor = SubprocessSSHVendor
+get_ssh_vendor = ParamikoSSHVendor
 
 
 class SSHGitClient(TraditionalGitClient):
```

Also, I would be cautious with the assumption that the usage of `*args` implies that a function takes more than one argument. In general, I would say that it means that the function is either a wrapper or somehow needs to pick apart its argument list on its own. At any rate, in the documentation here:

http://docs.paramiko.org/en/1.15/api/channel.html#paramiko.channel.Channel.exec_command

there's nothing to suggest that `exec_command` accepts more than a single string argument.

**Comment by jelmer** [comment]
On Tue, Aug 18, 2015 at 02:40:23PM -0700, Andreas Klöckner wrote:
> Yes, I can reproduce this crash with just plain command-line dulwich:
> 
> ```
> $ dulwich clone git@github.com:jelmer/dulwich dw
> /usr/lib/python2.7/gettext.py:49: ImportWarning: Not importing directory '/home/andreas/work/django/relate/locale': missing __init__.py
>   import locale, copy, os, re, struct, sys
> Traceback (most recent call last):
>   File "/home/andreas/src/env/bin/dulwich", line 5, in <module>
>     pkg_resources.run_script('dulwich==0.10.2', 'dulwich')
>   File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 492, in run_script
>   File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 1350, in run_script
>   File "/home/andreas/src/env/lib/python2.7/site-packages/dulwich-0.10.2-py2.7-linux-x86_64.egg/EGG-INFO/scripts/dulwich", line 392, in <module>
>     commands[cmd](sys.argv[2:])
>   File "/home/andreas/src/env/lib/python2.7/site-packages/dulwich-0.10.2-py2.7-linux-x86_64.egg/EGG-INFO/scripts/dulwich", line 181, in cmd_clone
>     porcelain.clone(source, target, bare=("--bare" in opts))
>   File "/home/andreas/src/env/local/lib/python2.7/site-packages/dulwich-0.10.2-py2.7-linux-x86_64.egg/dulwich/porcelain.py", line 235, in clone
>     progress=errstream.write)
>   File "/home/andreas/src/env/local/lib/python2.7/site-packages/dulwich-0.10.2-py2.7-linux-x86_64.egg/dulwich/client.py", line 233, in fetch
>     progress)
>   File "/home/andreas/src/env/local/lib/python2.7/site-packages/dulwich-0.10.2-py2.7-linux-x86_64.egg/dulwich/client.py", line 537, in fetch_pack
>     proto, can_read = self._connect(b'upload-pack', path)
>   File "/home/andreas/src/env/local/lib/python2.7/site-packages/dulwich-0.10.2-py2.7-linux-x86_64.egg/dulwich/client.py", line 989, in _connect
>     port=self.port, username=self.username)
>   File "/home/andreas/src/env/local/lib/python2.7/site-packages/dulwich-0.10.2-py2.7-linux-x86_64.egg/dulwich/client.py", line 961, in run_command
>     channel.exec_command(*command)
>   File "/usr/lib/python2.7/dist-packages/paramiko/channel.py", line 60, in _check
>     return func(self, *args, **kwds)
> TypeError: exec_command() takes exactly 2 arguments (3 given)
Ah, I see what's happening now. Your fix is correct in principle
(though probably needs shell escaping when joining arguments).
Thanks for the bug report.

Can you try with master? That defaults to just using the
subprocess ssh implementation, which is tested better. I wonder if we
should ditch the paramiko support in lieu of unit tests.

**Comment by inducer** [comment]
git master with the subprocess SSH implementation works fine. Please let the paramiko SSH implementation live. [a project of mine](/inducer/relate) relies on it, because it has to do its own key management. Doing key management with the subprocess SSH implementation would be a royal pain, because it would involve messing around with files in the SSH configuration directory.

**Comment by jelmer** [comment]
Nice project :)

I'll keep the Paramiko implementation around. I've filed #364

**Comment by jelmer** [comment]
Fixed in master.

**Comment by inducer** [comment]
Thank you!
