### ISSUE TITLE
AttributeError: 'module' object has no attribute 'uname'

### ISSUE THREAD

**Issue by nareshchaudhary37** [jelmer/dulwich#366]
In the site-packages/dulwich/pack.py problem in line 60. when we have a window os, Os doen't have uname attribute, 

The below code try to check has_mmap true or false.
try:
    import mmap
except ImportError:
    has_mmap = False
else:
    has_mmap = True

if we installed properly, we have a mmap and it will be true. Nonetheless its tried to check os.uname that doen't into window, we can solved this is two ways.

1. Just add if condition like:

# For some reason the above try, except fails to set has_mmap = False
if not has_mmap:
	if os.uname()[0] == 'Plan9':
	    has_mmap = False

2.Put in try.. except

**Comment by jelmer** [comment]
This is already fixed in master.
