### ISSUE TITLE
client.fetch and thin packs

### ISSUE THREAD

**Issue by jsbain** [jelmer/dulwich#372]
It seems that this issue:
https://bugs.launchpad.net/dulwich/+bug/1025886
still exists in recent dulwich versions.  

I have a modified version which uses add-thin-pack instead of add-pack, however It is unclear to me whether this is the proper approach in all cases..

Is there any reason not to use add-thin-pack always?  (even for servers that do not support thin packs?). 
in other words, is the only difference between a thin and full pack the fact that not all refs are included?

 if not, is there a way to determine whether we have a thin or full pack from within fetch?

**Comment by jelmer** [comment]
On Fri, Sep 11, 2015 at 10:40:27PM -0700, jsbain wrote:
> It seems that this issue:
> https://bugs.launchpad.net/dulwich/+bug/1025886
> still exists in recent dulwich versions.  
> 
> I have a modified version which uses add-thin-pack instead of add-pack, however It is unclear to me whether this is the proper approach in all cases..
> 
> Is there any reason not to use add-thin-pack always?  (even for servers that do not support thin packs?). 
> in other words, is the only difference between a thin and full pack the fact that not all refs are included?
> 
>  if not, is there a way to determine whether we have a thin or full pack from within fetch?

What version of dulwich are you running, can you still reproduce this
with master?

**Comment by jsbain** [comment]
I believe I am using 0.9.9, but I think the offending line is still present master/client.py@230:

        f, commit, abort = target.object_store.add_pack()

If I understand, add_pack does not support thin-packs, while add_thin_pack does, but gets called a little differently.

**Comment by jelmer** [comment]
See bug #226 about this issue (still open)

**Comment by jelmer** [comment]
thin packs are slower, since they involve copying the resulting pack. We don't want to use add_thin_pack if it can be avoided.

**Comment by jsbain** [comment]
So, would the fix be to catch the KeyError, from add_pack, and then fallback to thin?  Is there a way to tell if the remote server sent us a thin pack, other then discovering missing objects?

**Comment by jelmer** [comment]
The proper fix would be to only call add_thin_pack if thin packs were negotiated with the server (if CAPABILITY_THIN_PACK exists in self._fetch_capabilities)
