### ISSUE TITLE
Missing 0.10.1 release on dulwich.io

### ISSUE THREAD

**Issue by karltk** [jelmer/dulwich#373]
Clicking on the link to the release tarball on dulwich.io brings me the URL https://www.dulwich.io/releases/dulwich-0.10.1.tar.gz, which is missing (404).

0.9.9 is the latest release where the URL works. The GPG key is present for all releases. It's "just" the actual tarball that's missing for 0.9.10, 0.10.0 and 0.10.1.

Incidentally, downloads work from https://www.samba.org/~jelmer/dulwich/

**Comment by jelmer** [comment]
Fixed, thanks.
