### ISSUE TITLE
subprocess.list2cmdline works on str, not bytes

### ISSUE THREAD

**Issue by inducer** [jelmer/dulwich#376]
Which means this is incorrect:

https://github.com/jelmer/dulwich/blob/83b17a313e0fbb4867f2839b13daa09af96582c2/dulwich/client.py#L971

**Comment by jelmer** [comment]
This works on python2, but unfortunately not on Python3. Unfortunately this kind of issue is likely to appear until issue #364 is addressed.

**Comment by inducer** [comment]
#377 fixes this for me. But yes, agreed. Tests would be awesome.

**Comment by jelmer** [comment]
Is it not possible to just decode the bytes and invoke subprocess.list2cmdline() before passing them to paramiko?

This escaping is not secure, you can cause errors by e.g. including a backslash at the end of a string.

**Comment by inducer** [comment]
(Moving discussion back to #377)
