### ISSUE TITLE
KeyError when pulling via Paramiko SSH--only on Py3

### ISSUE THREAD

**Issue by inducer** [jelmer/dulwich#378]
Another good reason for #364 I suspect... Any clue why I might be getting this on Py3 (but not on Py2)?

```
Traceback (most recent call last):
  File "/home/andreas/work/django/relate/course/versioning.py", line 468, in update_course
    "prevent_discarding_revisions"])
  File "/home/andreas/work/django/relate/course/versioning.py", line 315, in run_course_update_command
    remote_refs = client.fetch(remote_path, repo)
  File "/home/andreas/pack/dulwich/dulwich/client.py", line 240, in fetch
    commit()
  File "/home/andreas/pack/dulwich/dulwich/object_store.py", line 639, in commit
    return self.move_in_pack(path)
  File "/home/andreas/pack/dulwich/dulwich/object_store.py", line 617, in move_in_pack
    entries = p.sorted_entries()
  File "/home/andreas/pack/dulwich/dulwich/pack.py", line 1159, in sorted_entries
    ret = list(self.iterentries(progress=progress))
  File "/home/andreas/pack/dulwich/dulwich/pack.py", line 1147, in iterentries
    for i, result in enumerate(indexer):
  File "/home/andreas/pack/dulwich/dulwich/pack.py", line 1288, in _walk_all_chains
    for result in self._walk_ref_chains():
  File "/home/andreas/pack/dulwich/dulwich/pack.py", line 1298, in _walk_ref_chains
    self._ensure_no_pending()
  File "/home/andreas/pack/dulwich/dulwich/pack.py", line 1294, in _ensure_no_pending
    raise KeyError([sha_to_hex(s) for s in self._pending_ref])
KeyError: [b'c4b75168699c5ce96b596f630eb517db359d0444', b'347a788b2685809da6c4cd06d8a48afd555120a2']
```

**Comment by jelmer** [comment]
On Sun, Sep 13, 2015 at 02:10:36PM -0700, Andreas Klöckner wrote:
> Another good reason for #364 I suspect... Any clue why I might be getting this on Py3 (but not on Py2)?
> 
> ```
> Traceback (most recent call last):
>   File "/home/andreas/work/django/relate/course/versioning.py", line 468, in update_course
>     "prevent_discarding_revisions"])
>   File "/home/andreas/work/django/relate/course/versioning.py", line 315, in run_course_update_command
>     remote_refs = client.fetch(remote_path, repo)
>   File "/home/andreas/pack/dulwich/dulwich/client.py", line 240, in fetch
>     commit()
>   File "/home/andreas/pack/dulwich/dulwich/object_store.py", line 639, in commit
>     return self.move_in_pack(path)
>   File "/home/andreas/pack/dulwich/dulwich/object_store.py", line 617, in move_in_pack
>     entries = p.sorted_entries()
>   File "/home/andreas/pack/dulwich/dulwich/pack.py", line 1159, in sorted_entries
>     ret = list(self.iterentries(progress=progress))
>   File "/home/andreas/pack/dulwich/dulwich/pack.py", line 1147, in iterentries
>     for i, result in enumerate(indexer):
>   File "/home/andreas/pack/dulwich/dulwich/pack.py", line 1288, in _walk_all_chains
>     for result in self._walk_ref_chains():
>   File "/home/andreas/pack/dulwich/dulwich/pack.py", line 1298, in _walk_ref_chains
>     self._ensure_no_pending()
>   File "/home/andreas/pack/dulwich/dulwich/pack.py", line 1294, in _ensure_no_pending
>     raise KeyError([sha_to_hex(s) for s in self._pending_ref])
> KeyError: [b'c4b75168699c5ce96b596f630eb517db359d0444', b'347a788b2685809da6c4cd06d8a48afd555120a2']
> ```

I suspect this is just a bytes vs str error and a situation we don't
unit-test for.

Cheers,

Jelmer

**Comment by jelmer** [comment]
Can you still reproduce this with current master?

**Comment by inducer** [comment]
I've been using Dulwich on Py3 in production for a year, with no issues. Thanks for checking!

**Comment by jelmer** [comment]
Thanks!
