### ISSUE TITLE
Different behaviour of 'as_dict' for bare and non-bare repositories

### ISSUE THREAD

**Issue by jonashaag** [jelmer/dulwich#383]
See test case https://github.com/jonashaag/dulwich/commit/31ee97a1003e90546ec0f80432c8401ed440e1b8:

```py
repo.as_dict('refs/tags/') == repo.as_dict('refs/tags')
```

for non-bare but not for bare repositories.

**Comment by jelmer** [comment]
Thanks, fixed in master.
