### ISSUE TITLE
'name' must be bytestring, not unicode

### ISSUE THREAD

**Issue by ypit** [jelmer/dulwich#387]
Please, help me!
I use: Python (ver.2.7.9) and Django (ver.1.8.4).
When i select file in git repo error:
Exception Location:	/opt/ng/web2/python/lib/python2.7/dulwich/repo.py in __getitem__, line 448:
'name' must be bytestring, not unicode  (where name is - refs/heads/master)

**Comment by jelmer** [comment]
On Tue, Oct 27, 2015 at 05:27:58PM -0700, ypit wrote:
> Please, help me!
> I use: Python (ver.2.7.9) and Django (ver.1.8.4).
> When i select file in git repo error:
> Exception Location:	/opt/ng/web2/python/lib/python2.7/dulwich/repo.py in __getitem__, line 448:
> 'name' must be bytestring, not unicode  (where name is - refs/heads/master)

That's correct. You need to pass in a regular stirng, not a unicode string. If you have a unicode string object, you should first encode it before passing it to Dulwich.

Jelmer

**Comment by jelmer** [comment]
Closing as this is working as intended.
