### ISSUE TITLE
TraditionalGitClient.fetch_pack returns all refs when wants=[]

### ISSUE THREAD

**Issue by crbunney** [jelmer/dulwich#390]
Hi

I did a fetch using this code:
```python
client.fetch(path, repo, determine_wants=lambda x: [])
```
I expected to get no refs, since determine_wants returned a list containing no refs, but instead got all of them.

I think this may be happening because of these lines from `client.TraditionalGitClient.fetch_pack` ([lines 563-565 in dulwich 0.11.2](https://github.com/jelmer/dulwich/blob/upstream/0.11.2/dulwich/client.py#L563)):
```python
            if not wants:
                proto.write_pkt_line(None)
                return refs
```
I think it can be resolved by changing this code to return `None` (similar to what it does on [line 554](https://github.com/jelmer/dulwich/blob/upstream/0.11.2/dulwich/client.py#L552) if refs is `None`):
```python
            if not wants:
                proto.write_pkt_line(None)
                return None
```

I've worked around this issue by ensuring my determine_wants function always contains at least 1 item, even if it doesn't want any.

**EDIT:** *Actually my original assessment appears incorrect, as it seems no matter what I get `determine_wants` to return, I still get all the refs returned from my `client.fetch` call*

**Comment by jelmer** [comment]
On Fri, Nov 27, 2015 at 08:52:10AM -0800, Chris Bunney wrote:
> I did a fetch using this code:
> ```python
> client.fetch(path, repo, determine_wants=lambda x: [])
> ```
> I expected to get no refs, since determine_wants returned a list containing no refs, but instead got all of them.
fetch() returns all local refs, not just those that were fetched.

Cheers,

Jelmer

**Comment by crbunney** [comment]
Thanks for the response, perhaps the docstring could be amended, as it currently says it returns the remote refs? 

I'll go back over the code for `dulwich.porcelein.pull` as it looks like `dulwich.client.TraditionalGitClient` writes the commits to disk but not into the index (is that right?), but `pull` shows how to update the refs as well as write to disk, which is what I'm trying to do (or at least part of it).

**Comment by jelmer** [comment]
Sorry, that was a typo in my previous comment. It should be returning all *remote* refs, not all local refs. I've clarified the docstrings.
