### ISSUE TITLE
Can I get branches in the order those were created ?

### ISSUE THREAD

**Issue by lahirug** [jelmer/dulwich#392]

**Comment by jelmer** [comment]
You will need to parse the reflog to find out when branches were created. At the moment, dulwich doesn't provide any support for that.

**Comment by jelmer** [comment]
There is now also a reflog module that you can use to find the age of branches.

**Comment by jelmer** [comment]
You would have to read the reflog for that. At the moment, Dulwich
does not have an interface for reading the reflog but it should be
fairly easy to add one.
