### ISSUE TITLE
Is there a way to find commits only belong to the given branch

### ISSUE THREAD

**Issue by lahirug** [jelmer/dulwich#395]
Right now dulwich returns all the commits in the branch came from ancestor branch, if I want to find the commit only belong to that branch how do I do ? Is there a logic I can follow with the help of dulwich ?

**Comment by jelmer** [comment]
This isn't a bug in Dulwich; please use the user mailing list for general questions (http://lists.launchpad.net/dulwich-users)

What do you mean exactly by "belonging to a branch" ? All commits that are a part of the ancestry of the head of a branch are "on the branch".
