### ISSUE TITLE
porcelain.clone error

### ISSUE THREAD

**Issue by hanbeibei** [jelmer/dulwich#401]
Hello, 

my link is http://ok231456@kkk.kkkt.net/git/~ok231456/IPC.git, in this form(sorry for modify internal info) if I use porcelain.clone(my_url, repo_name), it will raise an error: urllib.error.URLError: <urlopen error [Errno 11003] getaddrinfo failed>

but it is fined if I use git clone command

**Comment by jelmer** [comment]
Can you be more specific? I also get a URLError for that URL, but because the host does not resolve (which is expected).

**Comment by hanbeibei** [comment]
I was trying to use dulwich on my internal stash/gitblit environment, and get that error,

**Comment by jelmer** [comment]
can please paste the *full* error message? This is a perfectly reasonable error if the host name can't be resolved, for example.

**Comment by hanbeibei** [comment]
the url is like this: http://ok231456@kkk.kkkt.net/git/~ok231456/IPC.git

just take the ok231456 and kkk.kkkt.net as internal user id and internal url. I will post the whole error message tomorrow, thanks!

**Comment by jelmer** [comment]
FTR, that fails here too and is working as intended:

morgaine:/tmp% ~/src/dulwich/bin/dulwich clone http://ok231456@kkk.kkkt.net/git/~ok231456/IPC.git /tmp/ipc
Traceback (most recent call last):
  File "/home/jelmer/src/dulwich/bin/dulwich", line 421, in <module>
    commands[cmd](sys.argv[2:])
  File "/home/jelmer/src/dulwich/bin/dulwich", line 181, in cmd_clone
    porcelain.clone(source, target, bare=("--bare" in opts))
  File "/usr/lib/python2.7/dist-packages/dulwich/porcelain.py", line 253, in clone
    progress=errstream.write)
  File "/usr/lib/python2.7/dist-packages/dulwich/client.py", line 242, in fetch
    progress)
  File "/usr/lib/python2.7/dist-packages/dulwich/client.py", line 1064, in fetch_pack
    b"git-upload-pack", url)
  File "/usr/lib/python2.7/dist-packages/dulwich/client.py", line 978, in _discover_references
    resp = self._http_request(url, headers)
  File "/usr/lib/python2.7/dist-packages/dulwich/client.py", line 963, in _http_request
    resp = self.opener.open(req)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno -2] Name or service not known>

**Comment by hanbeibei** [comment]
please refer to my error message:


Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\dulwich-0.12.1-py3.4.egg\dulwich\client.
y", line 249, in fetch
    progress)
  File "C:\Anaconda3\lib\site-packages\dulwich-0.12.1-py3.4.egg\dulwich\client.
y", line 1069, in fetch_pack
    b"git-upload-pack", url)
  File "C:\Anaconda3\lib\site-packages\dulwich-0.12.1-py3.4.egg\dulwich\client.
y", line 983, in _discover_references
    resp = self._http_request(url, headers)
  File "C:\Anaconda3\lib\site-packages\dulwich-0.12.1-py3.4.egg\dulwich\client.
y", line 968, in _http_request
    resp = self.opener.open(req)
  File "C:\Anaconda3\lib\urllib\request.py", line 455, in open
    response = self._open(req, data)
  File "C:\Anaconda3\lib\urllib\request.py", line 473, in _open
    '_open', req)
  File "C:\Anaconda3\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Anaconda3\lib\urllib\request.py", line 1215, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Anaconda3\lib\urllib\request.py", line 1192, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11003] getaddrinfo failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "clone.py", line 18, in <module>
    porcelain.clone(args[1], args[2])
  File "C:\Anaconda3\lib\site-packages\dulwich-0.12.1-py3.4.egg\dulwich\porcela
n.py", line 258, in clone
    progress=errstream.write)
  File "C:\Anaconda3\lib\site-packages\dulwich-0.12.1-py3.4.egg\dulwich\client.
y", line 251, in fetch
    abort()
UnboundLocalError: local variable 'abort' referenced before assignment

**Comment by hanbeibei** [comment]
I think it might caused by proxy, please refer to these link:

http://stackoverflow.com/questions/5041067/gitolite-git-clone-error
https://confluence.atlassian.com/display/STASHKB/Wrong+Git+Clone+URL+When+Using+Proxy

this is answered by stash dev:
http://stackoverflow.com/questions/19589532/clone-git-repository-from-stash-via-https-fails

**Comment by jelmer** [comment]
Ah, interesting. IIUC that means this is working as intended then?

**Comment by hanbeibei** [comment]
still not yet, I will try to argue with SA to enable ssh access key function

**Comment by hanbeibei** [comment]
thanks for your attention.

**Comment by ctismer** [comment]
@jelmer I just got a similar error.
```
porcelain.clone('git://github.com/sigmavirus24/github3.py.git', 'cloned_repo', True)
```
```
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-21-a87448bb4fdc> in <module>()
----> 1 porcelain.clone('git://github.com/sigmavirus24/github3.py.git', 'cloned_repo', True)

/Users/tismer/src/ansi-test/lib/python2.7/site-packages/dulwich/porcelain.pyc in clone(source, target, bare, checkout, errstream, outstream)
    256         remote_refs = client.fetch(host_path, r,
    257             determine_wants=r.object_store.determine_wants_all,
--> 258             progress=errstream.write)
    259         r[b"HEAD"] = remote_refs[b"HEAD"]
    260         if checkout:

/Users/tismer/src/ansi-test/lib/python2.7/site-packages/dulwich/client.pyc in fetch(self, path, target, determine_wants, progress)
    249                 progress)
    250         except:
--> 251             abort()
    252             raise
    253         else:

UnboundLocalError: local variable 'abort' referenced before assignment
```
An UnboundLocalError is by definition never intended and always a serious bug.

**Comment by jelmer** [comment]
On Wed, Feb 24, 2016 at 09:42:12AM -0800, Christian Tismer wrote:
> @jelmer I just got a similar error.
> ```
> porcelain.clone('git://github.com/sigmavirus24/github3.py.git', 'cloned_repo', True)
> ```
> ```
> ---------------------------------------------------------------------------
> UnboundLocalError                         Traceback (most recent call last)
> <ipython-input-21-a87448bb4fdc> in <module>()
> ----> 1 porcelain.clone('git://github.com/sigmavirus24/github3.py.git', 'cloned_repo', True)
> 
> /Users/tismer/src/ansi-test/lib/python2.7/site-packages/dulwich/porcelain.pyc in clone(source, target, bare, checkout, errstream, outstream)
>     256         remote_refs = client.fetch(host_path, r,
>     257             determine_wants=r.object_store.determine_wants_all,
> --> 258             progress=errstream.write)
>     259         r[b"HEAD"] = remote_refs[b"HEAD"]
>     260         if checkout:
> 
> /Users/tismer/src/ansi-test/lib/python2.7/site-packages/dulwich/client.pyc in fetch(self, path, target, determine_wants, progress)
>     249                 progress)
>     250         except:
> --> 251             abort()
>     252             raise
>     253         else:
> 
> UnboundLocalError: local variable 'abort' referenced before assignment
> ```
> An UnboundLocalError is by definition never intended and always a serious bug.
Agreed, but that should already be fixed.

Can you reproduce the UnboundLocalError with current master?

Cheers,

Jelmer
