### ISSUE TITLE
in client.py

### ISSUE THREAD

**Issue by hanbeibei** [jelmer/dulwich#402]
hello,

due to the http proxy method I can not get around, so I added ssh access key, and the it's works in my computer, without input password, but I still can not use it in porcelain.clone, after read the related code, I fount in line 1101:
def get_transport_and_path_from_url(url, config=None, **kwargs):

there are no code handle the parsed.scheme =='ssh', only 'git','git+ssh','http','https','file'.

here is the error log:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Anaconda3\lib\site-packages\dulwich-0.12.1-py3.4.egg\dulwich\porcelain.py", lin
e 243, in clone
    client, host_path = get_transport_and_path(source)
  File "c:\Anaconda3\lib\site-packages\dulwich-0.12.1-py3.4.egg\dulwich\client.py", line 1
153, in get_transport_and_path
    (hostname, path) = location.split(':')
ValueError: too many values to unpack (expected 2)
```
anyway, this error log is not import at all, the code should be handled at line 1142, but it finally raise an error at line 1155.

i hope I had explained this 'bug' clear: we missed one condition: parsed.scheme == 'ssh' under function: def get_transport_and_path_from_url(url, config=None, **kwargs)

Best regards
Beibei

**Comment by jelmer** [comment]
fixed in master

**Comment by hanbeibei** [comment]
Thanks Jemer
