### ISSUE TITLE
repo.do_commit errors on Python 3.5

### ISSUE THREAD

**Issue by meatballs** [jelmer/dulwich#403]
Whenever I try to use Repo.do_commit on Python 3.5, I get the following error:
```
...../dulwich/repo.py:550: in do_commit
    c.tree = index.commit(self.object_store)
...../dulwich/index.py:309: in commit
    return commit_tree(object_store, self.iterblobs())
...../dulwich/index.py:349: in commit_tree
    return build_tree(b'')
...../dulwich/index.py:343: in build_tree
    sha = build_tree(pathjoin(path, basename))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

path = b'private'

    def build_tree(path):
        tree = Tree()
>       for basename, entry in trees[path].items():
E       KeyError: b'private'

...../dulwich/index.py:340: KeyError
```

If I create blobs, tree and commit objects myself, it all works fine.

**Comment by jelmer** [comment]
On Mon, Jan 04, 2016 at 12:16:21PM -0800, Owen Campbell wrote:
> Whenever I try to use Repodo_commit on Python 35, I get the following error:
> ```
> /dulwich/repopy:550: in do_commit
>     ctree = indexcommit(selfobject_store)
> /dulwich/indexpy:309: in commit
>     return commit_tree(object_store, selfiterblobs())
> /dulwich/indexpy:349: in commit_tree
>     return build_tree(b'')
> /dulwich/indexpy:343: in build_tree
>     sha = build_tree(pathjoin(path, basename))
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> 
> path = b'private'
> 
>     def build_tree(path):
>         tree = Tree()
> >       for basename, entry in trees[path]items():
> E       KeyError: b'private'
> 
> /dulwich/indexpy:340: KeyError
> ```
> 
> If I create blobs, tree and commit objects myself, it all works fine
Do you have a script that reproduces this? The tests that run
do_commit() in the testsuite pass fine.

Cheers,

Jelmer

**Comment by meatballs** [comment]
Having written one to paste, here, it has shown up my own error! I was passing paths to repo.stage with the repo path itself included, rather than relative to the repo path.

Sorry to bother you all!
