### ISSUE TITLE
Submodule suport

### ISSUE THREAD

**Issue by nbecker** [jelmer/dulwich#411]
Trying to use hg-git to clone a git repo, which apparently uses dulwich.  I have 
dulwich                   - Python Git Library
  INSTALLED: 0.12.0 (latest)

The repo is:
https://github.com/syl20bnr/spacemacs

```
hg clone .emacs.d stuff
importing git objects into hg
importing [>                                                                                       ]   98/5567** unknown exception encountered, please report by visiting
** https://mercurial-scm.org/wiki/BugTracker
** Python 2.7.10 (default, Sep  8 2015, 17:20:17) [GCC 5.1.1 20150618 (Red Hat 5.1.1-4)]
** Mercurial Distributed SCM (version 3.6.2)
** Extensions loaded: hgk, rebase, convert, hggit, evolve, transplant, shelve
Traceback (most recent call last):
  File "/usr/bin/hg", line 43, in <module>
    mercurial.dispatch.run()
  File "/usr/lib64/python2.7/site-packages/mercurial/dispatch.py", line 54, in run
    sys.exit((dispatch(request(sys.argv[1:])) or 0) & 255)
  File "/usr/lib64/python2.7/site-packages/mercurial/dispatch.py", line 116, in dispatch
    ret = _runcatch(req)
  File "/usr/lib64/python2.7/site-packages/mercurial/dispatch.py", line 187, in _runcatch
    return _dispatch(req)
  File "/usr/lib64/python2.7/site-packages/mercurial/dispatch.py", line 920, in _dispatch
    cmdpats, cmdoptions)
  File "/usr/lib64/python2.7/site-packages/mercurial/dispatch.py", line 679, in runcommand
    ret = _runcommand(ui, options, cmd, d)
  File "/usr/lib64/python2.7/site-packages/mercurial/dispatch.py", line 1051, in _runcommand
    return checkargs()
  File "/usr/lib64/python2.7/site-packages/mercurial/dispatch.py", line 1011, in checkargs
    return cmdfunc()
  File "/usr/lib64/python2.7/site-packages/mercurial/dispatch.py", line 917, in <lambda>
    d = lambda: util.checksignature(func)(ui, *args, **cmdoptions)
  File "/usr/lib64/python2.7/site-packages/mercurial/util.py", line 801, in check
    return func(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/mercurial/commands.py", line 1453, in clone
    shareopts=opts.get('shareopts'))
  File "/usr/lib64/python2.7/site-packages/mercurial/hg.py", line 555, in clone
    destpeer.local().clone(srcpeer, heads=revs, stream=stream)
  File "/usr/lib64/python2.7/site-packages/mercurial/localrepo.py", line 1852, in clone
    streamclonerequested=stream)
  File "/usr/lib64/python2.7/site-packages/mercurial/extensions.py", line 183, in closure
    return func(*(args + a), **kw)
  File "/home/nbecker/hg-git/hggit/util.py", line 52, in inner
    return f(*args, **kwargs)
  File "/home/nbecker/hg-git/hggit/__init__.py", line 331, in exchangepull
    pullop.cgresult = repo.githandler.fetch(remote.path, heads)
  File "/home/nbecker/hg-git/hggit/git_handler.py", line 267, in fetch
    imported = self.import_git_objects(remote_name, filteredrefs)
  File "/home/nbecker/hg-git/hggit/git_handler.py", line 725, in import_git_objects
    self.import_git_commit(commit)
  File "/home/nbecker/hg-git/hggit/git_handler.py", line 799, in import_git_commit
    gitmodules = self.parse_gitmodules(git_commit_tree)
  File "/home/nbecker/hg-git/hggit/git_handler.py", line 1520, in parse_gitmodules
    sm_path = tt.get(section, 'path')
  File "/usr/lib64/python2.7/site-packages/dulwich/config.py", line 151, in get
    return self._values[(section[0],)][name]
KeyError: ('submodule',)
```

**Comment by jelmer** [comment]
On Wed, Feb 10, 2016 at 08:35:41AM -0800, ndbecker wrote:
> Trying to use hg-git to clone a git repo, which apparently uses dulwich.  I have 
> dulwich                   - Python Git Library
>   INSTALLED: 0.12.0 (latest)
> 
> The repo is:
> https://github.com/syl20bnr/spacemacs
> 
> ```
> hg clone .emacs.d stuff
> importing git objects into hg
> importing [>                                                                                       ]   98/5567** unknown exception encountered, please report by visiting
> ** https://mercurial-scm.org/wiki/BugTracker
> ** Python 2.7.10 (default, Sep  8 2015, 17:20:17) [GCC 5.1.1 20150618 (Red Hat 5.1.1-4)]
> ** Mercurial Distributed SCM (version 3.6.2)
> ** Extensions loaded: hgk, rebase, convert, hggit, evolve, transplant, shelve
> Traceback (most recent call last):
>   File "/usr/bin/hg", line 43, in <module>
>     mercurial.dispatch.run()
>   File "/usr/lib64/python2.7/site-packages/mercurial/dispatch.py", line 54, in run
>     sys.exit((dispatch(request(sys.argv[1:])) or 0) & 255)
>   File "/usr/lib64/python2.7/site-packages/mercurial/dispatch.py", line 116, in dispatch
>     ret = _runcatch(req)
>   File "/usr/lib64/python2.7/site-packages/mercurial/dispatch.py", line 187, in _runcatch
>     return _dispatch(req)
>   File "/usr/lib64/python2.7/site-packages/mercurial/dispatch.py", line 920, in _dispatch
>     cmdpats, cmdoptions)
>   File "/usr/lib64/python2.7/site-packages/mercurial/dispatch.py", line 679, in runcommand
>     ret = _runcommand(ui, options, cmd, d)
>   File "/usr/lib64/python2.7/site-packages/mercurial/dispatch.py", line 1051, in _runcommand
>     return checkargs()
>   File "/usr/lib64/python2.7/site-packages/mercurial/dispatch.py", line 1011, in checkargs
>     return cmdfunc()
>   File "/usr/lib64/python2.7/site-packages/mercurial/dispatch.py", line 917, in <lambda>
>     d = lambda: util.checksignature(func)(ui, *args, **cmdoptions)
>   File "/usr/lib64/python2.7/site-packages/mercurial/util.py", line 801, in check
>     return func(*args, **kwargs)
>   File "/usr/lib64/python2.7/site-packages/mercurial/commands.py", line 1453, in clone
>     shareopts=opts.get('shareopts'))
>   File "/usr/lib64/python2.7/site-packages/mercurial/hg.py", line 555, in clone
>     destpeer.local().clone(srcpeer, heads=revs, stream=stream)
>   File "/usr/lib64/python2.7/site-packages/mercurial/localrepo.py", line 1852, in clone
>     streamclonerequested=stream)
>   File "/usr/lib64/python2.7/site-packages/mercurial/extensions.py", line 183, in closure
>     return func(*(args + a), **kw)
>   File "/home/nbecker/hg-git/hggit/util.py", line 52, in inner
>     return f(*args, **kwargs)
>   File "/home/nbecker/hg-git/hggit/__init__.py", line 331, in exchangepull
>     pullop.cgresult = repo.githandler.fetch(remote.path, heads)
>   File "/home/nbecker/hg-git/hggit/git_handler.py", line 267, in fetch
>     imported = self.import_git_objects(remote_name, filteredrefs)
>   File "/home/nbecker/hg-git/hggit/git_handler.py", line 725, in import_git_objects
>     self.import_git_commit(commit)
>   File "/home/nbecker/hg-git/hggit/git_handler.py", line 799, in import_git_commit
>     gitmodules = self.parse_gitmodules(git_commit_tree)
>   File "/home/nbecker/hg-git/hggit/git_handler.py", line 1520, in parse_gitmodules
>     sm_path = tt.get(section, 'path')
>   File "/usr/lib64/python2.7/site-packages/dulwich/config.py", line 151, in get
>     return self._values[(section[0],)][name]
> KeyError: ('submodule',)
It looks like hg-git has its own submodule support; this looks like an issue in parse_gitmodules in hg-git.

Jelmer

**Comment by jelmer** [comment]
Actually, this repository doesn't seem to have any submodules so I don't think this is a dulwich bug. Why is hg-git trying to read submodules?

Can you still reproduce this?

**Comment by czarkoff** [comment]
`hggit` doesn't handle submodules.

**Comment by jelmer** [comment]
It has at least have some support for gitmodules, as it has a parse_gitmodules() function (see the traceback).

**Comment by jordigh** [comment]
I believe this is a problem in dulwich itself, as it's not handling malformed submodule entries correctly. Git simply ignores incomplete submodule entries.

**Comment by jelmer** [comment]
I'm pretty sure #1224 fixes a different issue than this bug; in the original bug the missing key was "submodule" - not "path" or "url".

It was also in the parse_submodules() function in hg-git (which it since seems to have switched away from in favour of the dulwich one) - see the backtrace in https://github.com/jelmer/dulwich/issues/411#issuecomment-182507529.

**Comment by jordigh** [comment]
The test I added in #1224 ends up raising at the same spot (without my included fix, of course). The problem is that the initial key error is swallowed in the `get` function, and a second, different indexing is then attempted, which also fails, but obscurely, in a different way.

**Comment by jelmer** [comment]
The logic may be similar in both places, at the time that this bug was filed there was no parse_submodules() function in dulwich - that wasn't introduced until several months later in e557e763e2b4b9dd7c78af0e78f67ffbb6e43c9f

the code in mercurial at the time was https://foss.heptapod.net/mercurial/hg-git/-/blob/be0d1413a06f054b965a739bc511bed8dc9e65b8/hggit/git_handler.py#L1521

This may be splitting hairs - I think your fix is correct - but I did want to clarify that at the time this issue was correctly closed.
