### ISSUE TITLE
Dulwich as setup.py dependency w/o compiler on Windows

### ISSUE THREAD

**Issue by MatthiasKauer** [jelmer/dulwich#416]
Hi,
I'm trying to use dulwich for a git backend in a project of mine.
I'm wondering how I should add it to the install_requires in setup.py.

On Windows, compiler availability cannot be assumed and I don't foresee performance issues with the ```--pure``` option.
However, this option cannot be added to setup.py easily. If I understand correctly this is only possible from pip 7.0 onward which is not in Ubuntu < 16.04.

If there was a wheel installation for Windows, that would work too of course. There is some discussion https://github.com/jelmer/dulwich/issues/222 https://github.com/jelmer/dulwich/pull/304 that sort of looks like someone implemented that. Nevertheless
```
pip install dulwich
```
fails on my Windows machine (because gcc is missing).
What is the status of that wheel installation right now?

What is [dulwich-windows on PyPI](https://pypi.python.org/pypi/dulwich-windows)? It doesn't explain much and just links back to the regular home page. Is it the aforementioned wheel build?

Are there other options that I haven't considered yet? Can you suggest a project that builds on top of dulwich and that I should look at for inspiration?

Kind regards,
Matthias

PS: On a side note, the --pure command has issues here https://www.dulwich.io/docs/index.html
I had to untangle the two dashes first.

**Comment by jelmer** [comment]
Hi Mathias,

On Thu, Mar 24, 2016 at 07:44:32AM -0700, MatthiasKauer wrote:
> I'm trying to use dulwich for a git backend in a project of mine.
> I'm wondering how I should add it to the install_requires in setup.py.
> 
> On Windows, compiler availability cannot be assumed and I don't foresee performance issues with the ```--pure``` option.
> However, this option cannot be added to setup.py easily. If I understand correctly this is only possible from pip 7.0 onward which is not in Ubuntu < 16.04.
> 
> If there was a wheel installation for Windows, that would work too of course. There is some discussion https://github.com/jelmer/dulwich/issues/222 https://github.com/jelmer/dulwich/pull/304 that sort of looks like someone implemented that. Nevertheless
> ```
> pip install dulwich
> ```
> fails on my Windows machine (because gcc is missing).
> What is the status of that wheel installation right now?
Unfortunately that bug has the latest status; Gary was working on
Windows support, but he has been inactive for a while. I don't think
there is anything building the wheel.

> What is [dulwich-windows on PyPI](https://pypi.python.org/pypi/dulwich-windows)? It doesn't explain much and just links back to the regular home page. Is it the aforementioned wheel build?
I have no idea what that project is; it is unaffiliated to the Dulwich
project itself.

> Are there other options that I haven't considered yet? Can you suggest a project that builds on top of dulwich and that I should look at for inspiration?
hg-git is probably a good source for inspiration.

Hope this helps,

Jelmer

**Comment by jelmer** [comment]
Closing this in favor of #222.
