### ISSUE TITLE
porcelain.clone does not support Github url with token

### ISSUE THREAD

**Issue by lmazuel** [jelmer/dulwich#428]
The syntax:

``` bash
git clone https://githubtoken@github.com/user/repo
```

allows to clone the repo, pre-configuring the repo to push using the token owner account.
https://github.com/blog/1270-easier-builds-and-deployments-using-git-over-https-and-oauth

Got this exception using `porcelain.clone`

``` python
URLError: <urlopen error [Errno 11003] getaddrinfo failed>
```

Seems like an url parsing error

**Comment by jelmer** [comment]
This should have been fixed along with #445. Please reopen if you can still reproduce it.
