### ISSUE TITLE
How to retrieve Tag objects

### ISSUE THREAD

**Issue by jonashaag** [jelmer/dulwich#430]
```
>>> r = dulwich.repo.Repo(...)
>>> r.refs.as_dict()
{..., b'refs/tags/foo': b'2f8ddefe50c776b758ecd6c7b483df7aad855bf9'}
>>> r[r.refs[b'refs/tags/foo']]
<Commit b'2f8ddefe50c776b758ecd6c7b483df7aad855bf9'>
>>> r[b'refs/tags/foo']
<Commit b'2f8ddefe50c776b758ecd6c7b483df7aad855bf9'>
```

How do I retrieve a `Tag` object instead?

**Comment by jelmer** [comment]
Not all tags have tags have Tag objects associated with them, only annotated tags do. This is a property of Git, not Dulwich. Non-annotated tags are just refs with a special name that point at Commit (or Blob or Tree) objects.

**Comment by jonashaag** [comment]
OK, thanks, we'll have to do a case distinction then.
