### ISSUE TITLE
self-tests don't work in ASCII environment

### ISSUE THREAD

**Issue by 0-wiz-0** [jelmer/dulwich#433]
When running the self-tests in an ASCII environment, they stop with:
````
======================================================================
ERROR: test_non_ascii (dulwich.tests.test_refs.DiskRefsContainerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch/devel/py-dulwich/work/dulwich-0.13.0/dulwich/tests/test_refs.py", line 443, in test_non_ascii
    encoded_ref = u'refs/tags/sch\xf6n'.encode(sys.getfilesystemencoding())
UnicodeEncodeError: 'ascii' codec can't encode character '\xf6' in position 13: ordinal not in range(128)

----------------------------------------------------------------------
````

**Comment by jelmer** [comment]
This test should be skipped if the filesystem encoding is ASCII.

On 6 June 2016 13:05:47 BST, Thomas Klausner <notifications@github.com> wrote:
>When running the self-tests in an ASCII environment, they stop with:
>````
>======================================================================
>ERROR: test_non_ascii (dulwich.tests.test_refs.DiskRefsContainerTests)
>----------------------------------------------------------------------
>Traceback (most recent call last):
>File
>"/scratch/devel/py-dulwich/work/dulwich-0.13.0/dulwich/tests/test_refs.py",
>line 443, in test_non_ascii
>encoded_ref = u'refs/tags/sch\xf6n'.encode(sys.getfilesystemencoding())
>UnicodeEncodeError: 'ascii' codec can't encode character '\xf6' in
>position 13: ordinal not in range(128)
>
>----------------------------------------------------------------------
>````
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jelmer/dulwich/issues/433

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jelmer** [comment]
Fixed, thanks!
