### ISSUE TITLE
fetch_pack via SSHGitClient hangs, Python3.5 / connecting to a BitBucket server

### ISSUE THREAD

**Issue by jeroenroosen** [jelmer/dulwich#434]
The process simply hangs after entering client.read_pkt_refs when running on Python 3.5. On Python 2.7 the same code runs just fine.

``` python
c, p = get_transport_and_path_from_url("ssh://git@our.bitbucket.server/project/repository.git")
r = Repo.init_bare("repo")
c.fetch(p.encode(), r,
        determine_wants=r.object_store.determine_wants_all,
        progress=logging.getLogger("git").debug)
```

**Comment by jeroenroosen** [comment]
Just in case, here's the exception caused by the remote host timing out:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/dulwich/client.py", line 580, in fetch_pack
    proto, negotiated_capabilities, graph_walker, pack_data, progress)
  File "/usr/local/lib/python3.5/site-packages/dulwich/client.py", line 436, in _handle_upload_pack_tail
    pkt = proto.read_pkt_line()
  File "/usr/local/lib/python3.5/site-packages/dulwich/protocol.py", line 152, in read_pkt_line
    raise HangupException()
dulwich.errors.HangupException: The remote server unexpectedly closed the connection.
```

**Comment by jelmer** [comment]
On Thu, Jun 16, 2016 at 02:59:03AM -0700, Jeroen Roosen wrote:
> The process simply hangs after entering client.read_pkt_refs when running on Python 3.5. On Python 2.7 the same code runs just fine.
> 
> ```python
> c, p = get_transport_and_path_from_url("ssh://git@our.bitbucket.server/project/repository.git")
> r = Repo.init_bare("repo")
> c.fetch(p.encode(), r,
>         determine_wants=r.object_store.determine_wants_all,
>         logging.getLogger("git").debug)
^         progress=

> ```
What output if any do you get if you set ._stderr on the client object to e.g.
sys.stderr?

FWIW this runs fine for me if I specify
ssh://git@github.com/jelmer/dulwich

Jelmer

**Comment by jeroenroosen** [comment]
`progress=` got lost in the copy paste, my bad.

I set `c._stderr` and there is no output at all, so no help there unfortunately.

The behaviour is very much like what I get when trying to ssh to github, which is blocked by company firewall. However, this is consistent between Python 2.7 and 3.5, whereas our internal bitbucket server can be reached just fine from 2.7 and blocks/hangs from 3.5.

**Comment by jelmer** [comment]
I have reproduced it now as well. As this is not caught by any of the tests I suspect it must be in the SSH specific code.

On 16 June 2016 10:59:03 BST, Jeroen Roosen <notifications@github.com> wrote:
>The process simply hangs after entering client.read_pkt_refs when
>running on Python 3.5. On Python 2.7 the same code runs just fine.
>
>```python
>c, p =
>get_transport_and_path_from_url("ssh://git@our.bitbucket.server/project/repository.git")
>r = Repo.init_bare("repo")
>c.fetch(p.encode(), r,
>        determine_wants=r.object_store.determine_wants_all,
>        logging.getLogger("git").debug)
>```
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jelmer/dulwich/issues/434

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
