### ISSUE TITLE
Inconsistent type requirement for client.fetch(...) in Python 3

### ISSUE THREAD

**Issue by jeroenroosen** [jelmer/dulwich#435]
Running into a small issue with Python 3:

``` python
from dulwich import client

c, p = client.get_transport_and_path_from_url(...)
c.fetch(p, ...)
```
- for `file://...` urls client.fetch requires a `str` to function (or else: `TypeError("Can't mix strings and bytes in path components")` by `os.path.join`
- for "ssh://" it requires a `bytes` (or else: `TypeError(p) in _connect(...)`)

**Comment by jelmer** [comment]
This is indeed a bug, though it is not clear what the right solution is here. Python URLs are strings. Paths are strings and a optionally bytestrings. The path that is sent to the remote host is a bytestring, and we have no way of knowing what encoding the remote host is using.



On 21 June 2016 15:57:08 BST, Jeroen Roosen <notifications@github.com> wrote:
>Running into a small issue with Python 3:
>```python
>from dulwich import client
>
>c, p = client.get_transport_and_path_from_url(...)
>c.fetch(p, ...)
>```
>* for `file://...` urls client.fetch requires a `str` to function (or
>else: `TypeError("Can't mix strings and bytes in path components")` by
>`os.path.join`
>* for "ssh://" it requires a `bytes` (or else: `TypeError(p) in
>_connect(...)`)
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jelmer/dulwich/issues/435

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jelmer** [comment]
This should be fixed in master.
