### ISSUE TITLE
Cannot delete tags using porcelain.push

### ISSUE THREAD

**Issue by Julian** [jelmer/dulwich#437]
(Filing as per IRC)

Given a remote repo with a tag `foo`,

```
        porcelain.push(
            repo,
            remote_url,
            refspecs=[":refs/tags/foo"],
        )
```

does not delete it in the remote.

**Comment by Julian** [comment]
The commit here seems to cause a bunch of unrelated failures in my test suite. I'll try to somehow reduce them to a minimum reproducer.

**Comment by Julian** [comment]
Minimal reproducer is just:

```
import dulwich.porcelain, dulwich.repo
r = dulwich.repo.Repo("./test2")
r.do_commit(message="stuff", ref="refs/heads/master")
dulwich.porcelain.push(r, "./test", refspecs="master")
print dulwich.porcelain.ls_remote("./test")
```

with two fresh repos test and test2. After this commit, pushing doesn't create any refs and prints `{}`.

**Comment by jelmer** [comment]
Thanks. I've found the issue, commit coming up once I have a test.

**Comment by jelmer** [comment]
Done in master.

**Comment by Julian** [comment]
Awesome, fixed, thanks!
