### ISSUE TITLE
Add a way to get the current branch / get a parsed symbolic ref

### ISSUE THREAD

**Issue by Julian** [jelmer/dulwich#438]
`repo.refs.read_ref["HEAD"]` will return a symbolic ref for the current branch, but it would be nice to be able to either parse the returned ref, or have an even easier way of asking what the current branch is.

**Comment by jelmer** [comment]
Implemented repo.refs.follow().

**Comment by Julian** [comment]
This seems a bit clumsy if I may :/ -- I'm not sure I see what this function actually looks like for this use case. I see what it returns, but I'd be doing something like:

`refs, _ = repo.refs.follow("HEAD"); current_branch, = [ref for ref in refs if ref != "HEAD"]`

?

**Comment by jelmer** [comment]
Shorter would be:

    current_branch = repo.refs.follow('HEAD')[0][-1]

Note that symbolic refs can be more than one level. E.g. HEAD can point at refs/heads/master and  refs/heads/master can then point at refs/heads/foo. This function returns all relevant refs in the chain.

**Comment by jelmer** [comment]
I'm open to other suggestions or convenience wrappers; the problem though is that the concept of a 'current branch' is a bit vague.

**Comment by Julian** [comment]
Hrm, alright, sorry, I'm sure I'm just underinformed about git internals, but e.g. `git status` reports a branch, which I presume is just the (parsed) contents of .git/HEAD -- even if ref/heads/master and refs/heads/bla happen to be the same ref, ref/heads/master would be the relevant ref for what I suspect is most use cases here, including mine, which is "if someone makes commits to the local repo using the git client and doesn't specify a branch, what branch ref will move"? In the case you're describing then I presume that the last ref in the list might not in fact be the one I'm looking for? Basically I want the same output as `git status` for my use case -- although I've seen http://stackoverflow.com/questions/6245570/how-to-get-the-current-branch-name-in-git which shows that yeah this seems to be a mess and there are lots of wrong things there, which is maybe a reason not to have anything called "Current branch" :/

(I also want to know "which remote branch tracks the branch" in the same way git status shows, so that I can go check whether it's up to date, but I haven't gotten quite there yet).

**Comment by jelmer** [comment]
So, it sounds like in that case what you want is the first branch in the chain, e.g.

current_branch_ref = repo.refs.follow('HEAD')[0][1]

**Comment by Julian** [comment]
Makes sense, thanks!
