### ISSUE TITLE
client.fetch does not work with remote repository and tags

### ISSUE THREAD

**Issue by mjmaenpaa** [jelmer/dulwich#450]
remote_refs returned with dulwich.client.fetch does not contain all remote references when remote
repository contains tags. Additionally it includes tags twice with second reference containing
extra characters **^{}**. When fetching from local repository everything works fine. At least HttpGitClient and SSHGitClient with ParamikoSSHVendor are affected.

Tested with Python 2.7, Python 3.4. Dulwich versions 0.14.1 and latest from master.

Example:

First clone with normal git:
```bash
$ git clone https://github.com/mjmaenpaa/tag_test.git
$ cd tag_test
$ git tag
Hi
$ cd ..
$ python
```

Then fetch from remote with dulwich:

```python
>>> import dulwich
>>> import dulwich.client
>>> from dulwich.repo import MemoryRepo
>>> repo = MemoryRepo()
>>> client = dulwich.client.HttpGitClient("https://github.com")

>>> remote_refs = client.fetch("mjmaenpaa/tag_test.git", repo)
>>> # Missing remote refs and extra tag refs
>>> for ref, sha1 in remote_refs.items():
           print(ref + b': ' + sha1)
refs/tags/Hi^{}: 80fca9837c62f9c1c1fd3cd03c76075aef867f9b
refs/heads/master: 80fca9837c62f9c1c1fd3cd03c76075aef867f9b
HEAD: 80fca9837c62f9c1c1fd3cd03c76075aef867f9b
refs/tags/Hi: e87ba668c50a3863c601508b4e006b865adbd66c
```

Then fetch from previously cloned local  with dulwich:

```python
>>> repo2 = MemoryRepo()
>>> client2 = dulwich.client.LocalGitClient()
>>> local_refs = client2.fetch("tag_test", repo2)
>>> # No missing refs
>>> for ref, sha1 in local_refs.items():
           print(ref + b': ' + sha1)
refs/tags/Hi: e87ba668c50a3863c601508b4e006b865adbd66c
HEAD: 80fca9837c62f9c1c1fd3cd03c76075aef867f9b
refs/remotes/origin/HEAD: 80fca9837c62f9c1c1fd3cd03c76075aef867f9b
refs/remotes/origin/master: 80fca9837c62f9c1c1fd3cd03c76075aef867f9b
refs/heads/master: 80fca9837c62f9c1c1fd3cd03c76075aef867f9b

**Comment by jelmer** [comment]
On Thu, Aug 18, 2016 at 01:42:34PM -0700, mjmaenpaa wrote:
> remote_refs returned with dulwich.client.fetch does not contain all remote references when remote
> repository contains tags. Additionally it includes tags twice with second reference containing
> extra characters **^{}**. When fetching from local repository everything works fine. At least HttpGitClient and SSHGitClient with ParamikoSSHVendor are affected.
> 
> Tested with Python 2.7, Python 3.4. Dulwich versions 0.14.1 and latest from master.
> 
> Example:
> 
> First clone with normal git:
> ```bash
> $ git clone https://github.com/mjmaenpaa/tag_test.git
> $ cd tag_test
> $ git tag
> Hi
> $ cd ..
> $ python
> ```
> 
> Then fetch from remote with dulwich:
> 
> ```python
> >>> import dulwich
> >>> import dulwich.client
> >>> from dulwich.repo import MemoryRepo
> >>> repo = MemoryRepo()
> >>> client = dulwich.client.HttpGitClient("https://github.com")
> 
> >>> remote_refs = client.fetch("mjmaenpaa/tag_test.git", repo)
> >>> # Missing remote refs and extra tag refs
> >>> for ref, sha1 in remote_refs.items():
>            print(ref + b': ' + sha1)
> refs/tags/Hi^{}: 80fca9837c62f9c1c1fd3cd03c76075aef867f9b
> refs/heads/master: 80fca9837c62f9c1c1fd3cd03c76075aef867f9b
> HEAD: 80fca9837c62f9c1c1fd3cd03c76075aef867f9b
> refs/tags/Hi: e87ba668c50a3863c601508b4e006b865adbd66c
> ```
This is correct and intentional; remote fetch operations return
"peeled" refs. We should probably document it better in the API docs
though.

> Then fetch from previously cloned local  with dulwich:
> 
> ```python
> >>> repo2 = MemoryRepo()
> >>> client2 = dulwich.client.LocalGitClient()
> >>> local_refs = client2.fetch("tag_test", repo2)
> >>> # No missing refs
> >>> for ref, sha1 in local_refs.items():
>            print(ref + b': ' + sha1)
> refs/tags/Hi: e87ba668c50a3863c601508b4e006b865adbd66c
> HEAD: 80fca9837c62f9c1c1fd3cd03c76075aef867f9b
> refs/remotes/origin/HEAD: 80fca9837c62f9c1c1fd3cd03c76075aef867f9b
> refs/remotes/origin/master: 80fca9837c62f9c1c1fd3cd03c76075aef867f9b
> refs/heads/master: 80fca9837c62f9c1c1fd3cd03c76075aef867f9b
This is #408.

Jelmer
