### ISSUE TITLE
HTTPS error on https://www.dulwich.io/

### ISSUE THREAD

**Issue by haypo** [jelmer/dulwich#455]
Hi,

Firefox denies to open https://www.dulwich.io/ because of a SSL_ERROR_RX_RECORD_TOO_LONG error.

Moreover, the clear text version http://www.dulwich.io/ displays the " Apache2 Debian Default Page" :-/

Victor

**Comment by jelmer** [comment]
Looks like one of the two servers is having disk issues.

Try https://rhonwyn.dulwich.io/ for now

**Comment by jelmer** [comment]
I've removed the AAAA for the problematic server, problem should disappear once that record disappears from DNS caches in about an hour.
