### ISSUE TITLE
startswith first arg must be bytes or a tuple of bytes, not str in walk.py at line 259

### ISSUE THREAD

**Issue by TomasHubelbauer** [jelmer/dulwich#457]
Windows 10 Home, Python 3.5.2, latest `dulwich` you get with `pip install`

```python
from dulwich.repo import Repo

r = Repo(".")
w = r.get_walker(paths=[".gitignore"], max_entries=1)
c = next(iter(w)).commit
print(c)
```

The `.gitignore` file exists in the repo.

```
Traceback (most recent call last):                                                                                                                                      
  File "test.py", line 5, in <module>                                                                                                                                   
    c = next(iter(w)).commit                                                                                                                                            
  File "C:\Users\Tom\AppData\Local\Programs\Python\Python35-32\lib\site-packages\dulwich\walk.py", line 323, in _next                                                   
    if self._should_return(entry):                                                                                                                                      
  File "C:\Users\Tom\AppData\Local\Programs\Python\Python35-32\lib\site-packages\dulwich\walk.py", line 309, in _should_return                                          
    if self._change_matches(change):                                                                                                                                    
  File "C:\Users\Tom\AppData\Local\Programs\Python\Python35-32\lib\site-packages\dulwich\walk.py", line 271, in _change_matches                                         
    if self._path_matches(new_path):                                                                                                                                    
  File "C:\Users\Tom\AppData\Local\Programs\Python\Python35-32\lib\site-packages\dulwich\walk.py", line 259, in _path_matches                                           
    if (changed_path.startswith(followed_path) and                                                                                                                      
TypeError: startswith first arg must be bytes or a tuple of bytes, not str 
```

The line numbers in the traceback are off by one or two in most cases because I've manually introduced `print` within the file while tracing this. 

https://github.com/jelmer/dulwich/blob/master/dulwich/walk.py#L257

Here, `changed_path` is bytes while `followed_path` is str.

I don't want to dig much deeper into this (lazy and do not know Python), hope you are able to figure this out with this information. My lazy attempt to overcome this was to add a bytes array into `w = r.get_walker(paths=[".gitignore"], max_entries=1)` instead of a str array:

```python
w = r.get_walker(paths=[".gitignore".encode("utf-8")], max_entries=1)
```

But that's just silly and of course didn't work at all.

**Comment by jelmer** [comment]
Paths in Git repositories are bytestrings, so this behaviour is correct - though the error message should arguably be better.

See also https://github.com/jelmer/dulwich/issues/79 for an earlier discussion about this.

**Comment by jelmer** [comment]
Why didn't encoding the path before passing it in not work?

**Comment by TomasHubelbauer** [comment]
I understand what you said about Git (although I didn't know that), but I still couldn't get Dulwich to work with Python 3 so I downgraded to Python 2 temporarily tomorrow.

I will have time to look into why it didn't work with encoded path tonight.

**Comment by TomasHubelbauer** [comment]
Yeah, I can't repro this, I must have derped out elsewhere and misunderstand the error to mean it comes from Dulwich. I'll make sure to open an issue if I run to anything else, but right now Dulwich works perfectly for me. Sorry.

**Comment by jelmer** [comment]
On Tue, Oct 25, 2016 at 03:59:57AM -0700, Tomáš Hübelbauer wrote:
> Yeah, I can't repro this, I must have derped out elsewhere and misunderstand the error to mean it comes from Dulwich. I'll make sure to open an issue if I run to anything else, but right now Dulwich works perfectly for me. Sorry.
:-) Thanks for confirming!

**Comment by jelmer** [comment]
On Mon, Oct 24, 2016 at 02:25:32PM -0700, Tomáš Hübelbauer wrote:
> Python 3.5.2, latest `dulwich` you get with `pip install`
> 
> ```python
> from dulwich.repo import Repo
> 
> r = Repo(".")
> w = r.get_walker(paths=[".gitignore"], max_entries=1)
> c = next(iter(w)).commit
> print(c)
> ```
> 
> ```
> Traceback (most recent call last):                                                                                                                                      
>   File "test.py", line 5, in <module>                                                                                                                                   
>     c = next(iter(w)).commit                                                                                                                                            
>   File "C:\Users\Tom\AppData\Local\Programs\Python\Python35-32\lib\site-packages\dulwich\walk.py", line 323, in _next                                                   
>     if self._should_return(entry):                                                                                                                                      
>   File "C:\Users\Tom\AppData\Local\Programs\Python\Python35-32\lib\site-packages\dulwich\walk.py", line 309, in _should_return                                          
>     if self._change_matches(change):                                                                                                                                    
>   File "C:\Users\Tom\AppData\Local\Programs\Python\Python35-32\lib\site-packages\dulwich\walk.py", line 271, in _change_matches                                         
>     if self._path_matches(new_path):                                                                                                                                    
>   File "C:\Users\Tom\AppData\Local\Programs\Python\Python35-32\lib\site-packages\dulwich\walk.py", line 259, in _path_matches                                           
>     if (changed_path.startswith(followed_path) and                                                                                                                      
> TypeError: startswith first arg must be bytes or a tuple of bytes, not str 
> ```
> 
> The line numbers in the traceback are off by one or two in most cases because I've manually introduced `print` within the file while tracing this. 
> 
> https://github.com/jelmer/dulwich/blob/master/dulwich/walk.py#L257
> 
> Here, `changed_path` is bytes while `followed_path` is str.
> 
> I don't want to dig much deeper into this, hope you are able to figure this out with this information. My lazy attempt to overcome this was to add a bytes array into `w = r.get_walker(paths=[".gitignore"], max_entries=1)` instead of a str array:
> 
> ```
> w = r.get_walker(paths=[".gitignore"], max_entries=1)
> ```
Paths in Git repositories are bytestrings, so this behaviour is
correct - though the error message should arguably be better.

Cheers,

Jelmer
