### ISSUE TITLE
ValueError when port specified for SSH

### ISSUE THREAD

**Issue by rasathus** [jelmer/dulwich#465]
At the requested of @jelmer Im raising a ticket in the parent module, in relation to [gittle#91](https://github.com/FriendCode/gittle/issues/91) .

When using the SSH protocol on a non-standard port, with a url such as this ...

ssh://git@server:7999/dply/stuff.git

A ValueError is thrown when it tries to unpack the three components into just a host and path ...

```
Traceback (most recent call last):
  File "git_test.py", line 9, in <module>
    repo = Gittle.clone(repo_url, repo_path, auth=auth)
  File "/usr/lib/python2.7/site-packages/gittle/gittle.py", line 440, in clone
    repo.fetch(bare=bare)
  File "/usr/lib/python2.7/site-packages/gittle/gittle.py", line 407, in fetch
    remote_refs = self.fetch_remote(origin_uri)
  File "/usr/lib/python2.7/site-packages/gittle/gittle.py", line 364, in fetch_remote
    client, remote_path = self.get_client(origin_uri=origin_uri)
  File "/usr/lib/python2.7/site-packages/gittle/gittle.py", line 328, in get_client
    client, remote_path = get_transport_and_path(origin_uri, **client_kwargs)
  File "/usr/lib64/python2.7/site-packages/dulwich/client.py", line 1115, in get_transport_and_path
    user_host, path = location.split(':')
ValueError: too many values to unpack
```

I started to have a look at the change, but wasn't quite sure what approach to take as I am unfamiliar with the project's codebase.

**Comment by jelmer** [comment]
On Mon, Nov 14, 2016 at 02:37:23AM -0800, Rasathus wrote:
> At the requested of @jelmer Im raising a ticket in the parent module, in relation to [gittle#91](https://github.com/FriendCode/gittle/issues/91) .
> 
> When using the SSH protocol on a non-standard port, which a url such as this ...
> 
> ssh://git@server:7999/dply/stuff.git
> 
> A ValueError is thrown when it tries to unpack the three components into just a host and path ...
> 
> ```
> Traceback (most recent call last):
>   File "git_test.py", line 9, in <module>
>     repo = Gittle.clone(repo_url, repo_path, auth=auth)
>   File "/usr/lib/python2.7/site-packages/gittle/gittle.py", line 440, in clone
>     repo.fetch(bare=bare)
>   File "/usr/lib/python2.7/site-packages/gittle/gittle.py", line 407, in fetch
>     remote_refs = self.fetch_remote(origin_uri)
>   File "/usr/lib/python2.7/site-packages/gittle/gittle.py", line 364, in fetch_remote
>     client, remote_path = self.get_client(origin_uri=origin_uri)
>   File "/usr/lib/python2.7/site-packages/gittle/gittle.py", line 328, in get_client
>     client, remote_path = get_transport_and_path(origin_uri, **client_kwargs)
>   File "/usr/lib64/python2.7/site-packages/dulwich/client.py", line 1115, in get_transport_and_path
>     user_host, path = location.split(':')
> ValueError: too many values to unpack
> ```
> 

FWIW it's easy to reproduce this using:

from dulwich.client import get_transport_and_path
get_transport_and_path("ssh://git@server:7999/dply/stuff.git")

**Comment by jelmer** [comment]
Fixed in master.
