### ISSUE TITLE
porcelain.clone() does not add remote

### ISSUE THREAD

**Issue by nicklasb** [jelmer/dulwich#466]
Maybe I am not really getting it here, but I am thought that the `porcelain.clone()`-function should behave like the usual git clone command. 

Because if you do a `git clone`, it automatically adds the remote repository to remotes.
But when I use `porcelain.clone()`, it doesn't. Is this intended behaviour?

Personally, I find the default behaviour quite useful, so I would prefer that..

**Comment by jelmer** [comment]
On Mon, Nov 21, 2016 at 04:11:35PM -0800, Nicklas Börjesson wrote:
> Maybe I am not really getting it here, but I am thought that the `porcelain.clone()`-function should behave like the usual git clone command. 
> 
> Because if you do a `git clone`, it automatically adds the remote repository to remotes.
> But when I use `porcelain.clone()`, it doesn't. Is this intended behaviour?
> 
> Personally, I find the default behaviour quite useful, so I would prefer that..

Yes, Dulwich should be modifying the remote. The porcelain module is still
quite young so this is missing functionality. See also
https://github.com/jelmer/dulwich/blob/master/dulwich/porcelain.py#L49 :)

Jelmer

**Comment by nicklasb** [comment]
A timid and humble person such as myself would never go so far as to do something as presumptuous, vulgar even, as pointing that out. :-)

**Comment by jelmer** [comment]
Fixed in master.
