### ISSUE TITLE
checkout on windows results in dirty index due to incorrect handling of permissions

### ISSUE THREAD

**Issue by sonologic** [jelmer/dulwich#469]
On windows, os.chmod (and probably os.stat / os.lstat) does not work, or more succinctly:

> Note
> 
> Although Windows supports chmod(), you can only set the file’s read-only flag with it (via the stat.S_IWRITE and stat.S_IREAD constants or a corresponding integer value). All other bits are ignored. 

When checking out with dulwich on windows, more than likely all files will be included in the 'modified' section of the porcelain.status result, because the permissions obtained via os.lstat do not match those in the index.

I'm contemplating fixing this bug by applying a mapping akin to what cygwin does (https://cygwin.com/cygwin-ug-net/ntsec.html, section 'File permissions') and using the win32security module in python on windows. 

This involves writing a dulwich wrapper around os.{chmod,lstat}, and depending on the os it is running on have that call os.{chmod,lstat} directly.

One issue I haven't quite thought through / researched is how to detect the platform. Maybe I will just switch based on the availability of the win32security module.

**Comment by jelmer** [comment]
Other parts of Dulwich check if the value of system.platform == 'win32'. Note that windows support is a bit of a second class citizen at the moment; we don't regularly run the testsuite on Windows since Gary, who was maintaining windows support, went AWOL.

What does cgit do on Windows for permissions? We'd ideally want to replicate its behaviour.

**Comment by sonologic** [comment]
You might want to help me out here with a link to cgit, I assume you're not referring to cgit the web interface to git?

I'd be happy to implement any scheme, as long as I end up with a clean check-out on windows. So far dulwich works fine for me on windows, except for the permission bit. I'm a bit new to windows myself, I'm still wrapping my head around the case-insensitivity of filenames on windows. Endless fun :)

**Comment by jelmer** [comment]
Sorry, the term is a bit confusing. With cgit I meant the original implementation of git in C, aka https://github.com/git/git

Dulwich tries to be compatible with c git when possible.

**Comment by sonologic** [comment]
Right, yes, that makes sense. I will dig into the git code, and find out what they do so we can replicate.

**Comment by sonologic** [comment]
So, git itself isn't for windows, there's a companion project that provides git for windows: https://github.com/git-for-windows/git - i'll take my queues from that.

**Comment by sonologic** [comment]
And git-for-windows is built on msys2, which again is built on top of cygwin, so we come full-circle to my initial approach of doing what cygwin does.

Some references:

- https://git-scm.com/book/en/v2/Getting-Started-Installing-Git - see section 'Installing on Windows'
- https://github.com/git-for-windows/git/wiki/Building-Git - building git for windows, using the msys2 based sdk
- https://msys2.github.io/ - 'MSYS2 is an independent rewrite of MSYS, based on modern Cygwin (POSIX compatibility layer) and MinGW-w64 with the aim of better interoperability with native Windows software.'

**Comment by jelmer** [comment]
Thanks for doing that research :) Matching Cygwin behaviour seems reasonable to me in that case FWIW.

**Comment by sonologic** [comment]
Well, scratch all that. MSYS2 is a minimal version of cygwin, with an important difference: file modes are ignored. Some rudimentary reporting of filemodes (through stat i presume) is faked: all read bits will be set, write bit for the user is set depending on the state of the dos 'read-only' flag and all executables are set if the file itself is an executable file (determined by the contents / extension or when it starts with #!).

Also when git-for-windows clones / inits a repo, core.filemode is set to false.

So to remain compatible with git-for-windows, i guess the above is what needs to be replicated. Now, dulwich already seems to react to core.filemode somewhat, but i'm gonna see why that doesn't result in a checkout that has no modifications according to status()

**Comment by sonologic** [comment]
From man git-config:

core.fileMode

    Tells Git if the executable bit of files in the working tree is to be honored.

    Some filesystems lose the executable bit when a file that is marked as executable is checked out, or checks out an non-executable file with executable bit on. git-clone[1] or git-init[1] probe the filesystem to see if it handles the executable bit correctly and this variable is automatically set as necessary.

    A repository, however, may be on a filesystem that handles the filemode correctly, and this variable is set to true when created, but later may be made accessible from another environment that loses the filemode (e.g. exporting ext4 via CIFS mount, visiting a Cygwin created repository with Git for Windows or Eclipse). In such a case it may be necessary to set this variable to false. See git-update-index[1].

    The default is true (when core.filemode is not specified in the config file).

**Comment by sonologic** [comment]
Pull request created: https://github.com/jelmer/dulwich/pull/472

**Comment by jelmer** [comment]
Did #472 address all the problems covered by this issue?

**Comment by sonologic** [comment]
Yep, this ticket can be closed now!
