### ISSUE TITLE
dulwich.errors.GitProtocolError: Length of pkt read 04a0 does not match length prefix 2005

### ISSUE THREAD

**Issue by koenfugro** [jelmer/dulwich#473]
I've been trying to clone a large-ish repository over http (from a slightly outdated gitlab instance), and keep getting this error. Full strack-trace below. It occurs with variations of the first length (04a0), the latter length seems to always be the same.

Tried on linux as well as windows, both give me this error. Using native git (on both windows and linux) i am able to clone the repository without errors consistently.

`dulwich.porcelain.clone('http://internal/repo.git', '/tmp/testgit')
Counting objects: 4287, done.
Compressing objects: 100% (2693/2693), done.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/dulwich/porcelain.py", line 280, in clone
    progress=errstream.write)
  File "/usr/local/lib/python2.7/dist-packages/dulwich/client.py", line 280, in fetch
    progress)
  File "/usr/local/lib/python2.7/dist-packages/dulwich/client.py", line 1212, in fetch_pack
    graph_walker, pack_data, progress)
  File "/usr/local/lib/python2.7/dist-packages/dulwich/client.py", line 487, in _handle_upload_pack_tail
    SIDE_BAND_CHANNEL_PROGRESS: progress}
  File "/usr/local/lib/python2.7/dist-packages/dulwich/client.py", line 354, in _read_side_band64k_data
    for pkt in proto.read_pkt_seq():
  File "/usr/local/lib/python2.7/dist-packages/dulwich/protocol.py", line 210, in read_pkt_seq
    pkt = self.read_pkt_line()
  File "/usr/local/lib/python2.7/dist-packages/dulwich/protocol.py", line 172, in read_pkt_line
    'Length of pkt read %04x does not match length prefix %04x' % (len(pkt_contents) + 4, size))
dulwich.errors.GitProtocolError: Length of pkt read 04a0 does not match length prefix 2005`

(ps, this is my corporate identity, my more permanent presence on github is user 'sonologic')

**Comment by koenfugro** [comment]
I'm going to have to dive into this, i'm not too well-versed on the protocol, but it seems to me that upon such a failure a retry may be in order (if at all possible). Any hints regarding the possibility of retrying are appreciated.

Sometimes (1 in 10 times approximately) I don't get the error and I can fetch the data just fine.

Most likely, some retarted corporate proxy between me and the repo is cutting off connections after some threshold or something like that, but that is speculation on my end.

**Comment by jelmer** [comment]
On Wed, Jan 04, 2017 at 01:45:03AM -0800, koenfugro wrote:
> I've been trying to clone a large-ish repository over http (from a slightly outdated gitlab instance), and keep getting this error. Full strack-trace below. It occurs with variations of the first length (04a0), the latter length seems to always be the same.
> 
> Tried on linux as well as windows, both give me this error. Using native git (on both windows and linux) i am able to clone the repository without errors consistently.
> 
> `dulwich.porcelain.clone('http://internal/repo.git', '/tmp/testgit')
> Counting objects: 4287, done.
> Compressing objects: 100% (2693/2693), done.
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python2.7/dist-packages/dulwich/porcelain.py", line 280, in clone
>     progress=errstream.write)
>   File "/usr/local/lib/python2.7/dist-packages/dulwich/client.py", line 280, in fetch
>     progress)
>   File "/usr/local/lib/python2.7/dist-packages/dulwich/client.py", line 1212, in fetch_pack
>     graph_walker, pack_data, progress)
>   File "/usr/local/lib/python2.7/dist-packages/dulwich/client.py", line 487, in _handle_upload_pack_tail
>     SIDE_BAND_CHANNEL_PROGRESS: progress}
>   File "/usr/local/lib/python2.7/dist-packages/dulwich/client.py", line 354, in _read_side_band64k_data
>     for pkt in proto.read_pkt_seq():
>   File "/usr/local/lib/python2.7/dist-packages/dulwich/protocol.py", line 210, in read_pkt_seq
>     pkt = self.read_pkt_line()
>   File "/usr/local/lib/python2.7/dist-packages/dulwich/protocol.py", line 172, in read_pkt_line
>     'Length of pkt read %04x does not match length prefix %04x' % (len(pkt_contents) + 4, size))
> dulwich.errors.GitProtocolError: Length of pkt read 04a0 does not match length prefix 2005`

Do you see anything unusual in e.g. a TCP dump of this request with C git versus Dulwich?

I'm wondering if this is a short read.

Jelmer

**Comment by koenfugro** [comment]
> Do you see anything unusual in e.g. a TCP dump of this request with C git versus Dulwich?
>
> I'm wondering if this is a short read.

Indeed, that was going to be my first course of action. I've ran a few traces, but it's a lot of data to compare. Will be on that today for a bit, although for our current purposes i've implemented an ugly work-around (just retry the entire fetch if a GitProtocolError) as i've been spending a disproportionate amount of time on the whole git bit already .. 

Will keep you posted on anything I find.

**Comment by koenfugro** [comment]
Interestingly, cgit now also seems to have problems, so perhaps this is not a bug in dulwich afterall but just something I need to slap our network department with:

C:\TEMP>git clone 'http://internal/repo.git' testcgit
Cloning into 'testcgit'...
remote: Counting objects: 4322, done.
remote: Compressing objects: 100% (2728/2728), done.
fatal: The remote end hung up unexpectedly9 MiB | 3.16 MiB/s
fatal: early EOF
fatal: index-pack failed

C:\TEMP>

**Comment by jelmer** [comment]
that does look very much like the same issue, albeit with a different error message

**Comment by koenfugro** [comment]
I'm putting this down as 'network issue on our end' for now, and will close this ticket.
