### ISSUE TITLE
Concurrent access to a repository on Windows sometimes fails

### ISSUE THREAD

**Issue by wme-at-contact-de** [jelmer/dulwich#482]
I have been testing Dulwich as a Git-Server on Windows, using multiple clients cloning and pushing the same repository concurrently. Most of the time, this works fine.
However, sometimes cloning fails with a traceback like this:
[traceback.txt](https://github.com/jelmer/dulwich/files/698672/traceback.txt)

The setup is Apache 2.4.6 with mod_wsgi on Windows 7.
I'm using a minimal WSGI application created with "make_wsgi_chain" (from dulwich/web.py).

Any idea what could be the problem, or whether this is a bug?

**Comment by jelmer** [comment]
As far as I can tell, the order in which Dulwich writes files is correct.

This might be caused by a lack of filesystem syncs.
