### ISSUE TITLE
config file parser does not support multi-line aliases

### ISSUE THREAD

**Issue by dhellmann** [jelmer/dulwich#495]
My ~/.gitconfig contains several aliases that span multiple lines. For example:

```
[alias]
    who = "!who() {\
        git log --no-merges --pretty=format:'%an - %ae' $@ | sort | uniq -c | sort -rn;\
    };\
    who"
```

The parser fails because it believes the first line of the alias should end with "

**Comment by jelmer** [comment]
Fixed in master.
