### ISSUE TITLE
porcelain.clone from repository without master branch does'nt work

### ISSUE THREAD

**Issue by ShibataTakao** [jelmer/dulwich#501]
## Expected outcome
I'd like to do `porcelain.clone` from repository without master branch, especially `bare=True` .

Because I can do `git clone --bare` from repository without master branch using git binary.
It does'nt cause error.

## Actual result
`porcelain.clone` cause following error.

```
Traceback (most recent call last):
  File "run.py", line 6, in clone
    porcelain.clone("/tmp/remote", target="/tmp/local2", bare=True)
  File "/home/ubuntu/dulwich/dulwich/porcelain.py", line 283, in clone
    r[b"HEAD"] = remote_refs[b"HEAD"]
KeyError: 'HEAD'
```

## Step to reproduce
Fisrt, Create repository which has only `develop` branch.
Remote repository is `/tmp/remote`, local repository is `/tmp/local` .

```
cd /tmp/remote
git init --bare

cd /tmp/local
git clone /tmp/remote
git echo "test" > test.txt
git add test.txt
git checkout -b develop
git branch -D master
git push origin develop
```

Next, Try to clone above repository using dulwich.
Run following script.

```python
# coding: utf-8

from dulwich import porcelain

if __name__ == "__main__":
    porcelain.clone("/tmp/remote", target="/tmp/local2", bare=True)
```

But it does'nt work.

```
Traceback (most recent call last):
  File "run.py", line 6, in clone
    porcelain.clone("/tmp/remote", target="/tmp/local2", bare=True)
  File "/home/ubuntu/dulwich/dulwich/porcelain.py", line 283, in clone
    r[b"HEAD"] = remote_refs[b"HEAD"]
KeyError: 'HEAD'
```

**Comment by ShibataTakao** [comment]
I use dulwich on b5402b602764b1888a19c4d5dd9c1737cf83fd1d .

**Comment by jelmer** [comment]
Fixed in master.

**Comment by samuelharmer** [comment]
Has this regressed? I'm using 0.18.6 and seeing exactly this error. Cloning a repo as bare using Git, then opening with Dulwich I get a `r[b'HEAD']`, but if I clone with using `porcelain.clone` results in `KeyError: b'HEAD'`.

**Comment by jelmer** [comment]
On Sat, Dec 02, 2017 at 01:33:38PM +0000, Samuel Harmer wrote:
> Has this regressed? I'm using 0.18.6 and seeing exactly this error. Cloning a repo as bare using Git, then opening with Dulwich I get a `r[b'HEAD']`, but if I clone with using `porcelain.clone` results in `KeyError: b'HEAD'`.
This is a bug in the fix. I've pushed a fix for this to master.

-- 
Jelmer Vernooĳ <jelmer@jelmer.uk>
PGP Key: https://www.jelmer.uk/D729A457.asc

**Comment by samuelharmer** [comment]
That works perfectly. Thanks Jelmer.

**Comment by adam-grant-hendry** [comment]
@jelmer This seems to have regressed again. Please see [`poetry` Issue #6873](https://github.com/python-poetry/poetry/issues/6873).

**Comment by jelmer** [comment]
@adam-grant-hendry I don't think this is a regression, standalone dulwich does fine cloning that repository/branch.

**Comment by adam-grant-hendry** [comment]
> Looking at poetry's src/poetry/vcs/git/backend.py, it does most of the mangling around refs (including resolving HEAD itself)...Reading the sourcecode, it's not entirely clear how you could get into that state with poetry though.

Neither am I...deleting the old `venv` and reinstalling with `poetry` worked, but I've posed the problem to `poetry` as I think the heart of the problem should be identified. If it's related to dependency updating, that could cause some grief with CI and `dependabot` for end users.
