### ISSUE TITLE
Using Repo.clone into bare repository fails if folder doesn't exist

### ISSUE THREAD

**Issue by cool-RR** [jelmer/dulwich#504]
For some reason the `mkdir` flag to Repo.clone doesn't get passed forward if the repo is a bare one, so `_init_maybe_bare` fails when it tries to create `foo/branches` when the `foo` directory doesn't exist.

**Comment by jelmer** [comment]
On Fri, Feb 24, 2017 at 01:22:53PM -0800, Ram Rachum wrote:
> For some reason the `mkdir` flag to Repo.clone doesn't get passed forward if the repo is a bare one, so `_init_maybe_bare` fails when it tries to create `foo/branches` when the `foo` directory doesn't exist.

That does look like a bug. Care to send a pull request?

Jelmer
