### ISSUE TITLE
Error using a private repository with porcelain

### ISSUE THREAD

**Issue by nir0s** [jelmer/dulwich#507]
When I try to clone or push to a private repository:

```
porcelain.clone('http://user:password@github.com/org/repo')
```

I get the following:

```
...
/home/nir0s/.virtualenvs/test/lib/python2.7/site-packages/dulwich/porcelain.pyc in clone(source, target, bare, checkout, errstream, outstream, origin)
    276         remote_refs = client.fetch(host_path, r,
    277             determine_wants=r.object_store.determine_wants_all,
--> 278             progress=errstream.write)
    279         r.refs.import_refs(
    280             b'refs/remotes/' + origin,

/home/nir0s/.virtualenvs/test/lib/python2.7/site-packages/dulwich/client.pyc in fetch(self, path, target, determine_wants, progress)
    278             result = self.fetch_pack(
    279                 path, determine_wants, target.get_graph_walker(), f.write,
--> 280                 progress)
    281         except:
    282             abort()

/home/nir0s/.virtualenvs/test/lib/python2.7/site-packages/dulwich/client.pyc in fetch_pack(self, path, determine_wants, graph_walker, pack_data, progress)
   1205         url = self._get_url(path)
   1206         refs, server_capabilities = self._discover_references(
-> 1207             b"git-upload-pack", url)
   1208         negotiated_capabilities = self._fetch_capabilities & server_capabilities
   1209         wants = determine_wants(refs)

/home/nir0s/.virtualenvs/test/lib/python2.7/site-packages/dulwich/client.pyc in _discover_references(self, service, url)
   1101             headers["Content-Type"] = "application/x-%s-request" % (
   1102                 service.decode('ascii'))
-> 1103         resp = self._http_request(url, headers)
   1104         try:
   1105             content_type = resp.info().gettype()

/home/nir0s/.virtualenvs/test/lib/python2.7/site-packages/dulwich/client.pyc in _http_request(self, url, headers, data)
   1088         except urllib2.HTTPError as e:
   1089             if e.code == 404:
-> 1090                 raise NotGitRepository()
   1091             if e.code != 200:
   1092                 raise GitProtocolError("unexpected http response %d" % e.code)

NotGitRepository: 

```

When I try adding .git:

```
porcelain.clone('http://user:password@github.com/org/repo.git')
```

I get the following:

```
...
/home/nir0s/.virtualenvs/test/lib/python2.7/site-packages/dulwich/porcelain.pyc in clone(source, target, bare, checkout, errstream, outstream, origin)
    276         remote_refs = client.fetch(host_path, r,
    277             determine_wants=r.object_store.determine_wants_all,
--> 278             progress=errstream.write)
    279         r.refs.import_refs(
    280             b'refs/remotes/' + origin,

/home/nir0s/.virtualenvs/test/lib/python2.7/site-packages/dulwich/client.pyc in fetch(self, path, target, determine_wants, progress)
    278             result = self.fetch_pack(
    279                 path, determine_wants, target.get_graph_walker(), f.write,
--> 280                 progress)
    281         except:
    282             abort()

/home/nir0s/.virtualenvs/test/lib/python2.7/site-packages/dulwich/client.pyc in fetch_pack(self, path, determine_wants, graph_walker, pack_data, progress)
   1224             resp_proto = Protocol(resp.read, None)
   1225             self._handle_upload_pack_tail(resp_proto, negotiated_capabilities,
-> 1226                 graph_walker, pack_data, progress)
   1227             return refs
   1228         finally:

/home/nir0s/.virtualenvs/test/lib/python2.7/site-packages/dulwich/client.pyc in _handle_upload_pack_tail(self, proto, capabilities, graph_walker, pack_data, progress, rbufsize)
    470         :param rbufsize: Read buffer size
    471         """
--> 472         pkt = proto.read_pkt_line()
    473         while pkt:
    474             parts = pkt.rstrip(b'\n').split(b' ')

/home/nir0s/.virtualenvs/test/lib/python2.7/site-packages/dulwich/protocol.pyc in read_pkt_line(self)
    156             sizestr = read(4)
    157             if not sizestr:
--> 158                 raise HangupException()
    159             size = int(sizestr, 16)
    160             if size == 0:

HangupException: The remote server unexpectedly closed the connection.

```

In both cases, folders get created.

This fails also when trying to push to a private repository:

```

/home/nir0s/.virtualenvs/test/lib/python2.7/site-packages/dulwich/porcelain.pyc in push(repo, remote_location, refspecs, outstream, errstream)
    684         try:
    685             client.send_pack(path, update_refs,
--> 686                 r.object_store.generate_pack_contents, progress=errstream.write)
    687             errstream.write(b"Push to " + remote_location_bytes +
    688                             b" successful.\n")

/home/nir0s/.virtualenvs/test/lib/python2.7/site-packages/dulwich/client.pyc in send_pack(self, path, determine_wants, generate_pack_contents, progress, write_pack)
   1167             self._report_status_parser = ReportStatusParser()
   1168 
-> 1169         new_refs = determine_wants(dict(old_refs))
   1170         if new_refs is None:
   1171             # Determine wants function is aborting the push.

/home/nir0s/.virtualenvs/test/lib/python2.7/site-packages/dulwich/porcelain.pyc in update_refs(refs)
    670 
    671         def update_refs(refs):
--> 672             selected_refs.extend(parse_reftuples(r.refs, refs, refspecs))
    673             new_refs = {}
    674             # TODO: Handle selected_refs == {None: None}

/home/nir0s/.virtualenvs/test/lib/python2.7/site-packages/dulwich/objectspec.pyc in parse_reftuples(lh_container, rh_container, refspecs)
    113     # TODO: Support * in refspecs
    114     for refspec in refspecs:
--> 115         ret.append(parse_reftuple(lh_container, rh_container, refspec))
    116     return ret
    117 

/home/nir0s/.virtualenvs/test/lib/python2.7/site-packages/dulwich/objectspec.pyc in parse_reftuple(lh_container, rh_container, refspec)
     73     :raise KeyError: If one of the refs can not be found
     74     """
---> 75     if refspec.startswith(b"+"):
     76         force = True
     77         refspec = refspec[1:]

AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by jelmer** [comment]
What version of dulwich is this with, and with what version of Python? Can you reproduce this on non-authenticated repositories?

**Comment by miguelslobo** [comment]
Hello,

I'm having the same problem when trying to push to repo:

AttributeError: 'NoneType' object has no attribute 'startswith'

I'm using python 2.7 and dulwich 0.17.3

**Comment by jelmer** [comment]
On Wed, Mar 29, 2017 at 04:57:23AM -0700, miguelslobo wrote:
> Hello,
> 
> I'm having the same problem when trying to push to repo:
> 
> AttributeError: 'NoneType' object has no attribute 'startswith'
> 
> I'm using python 2.7 and dulwich 0.17.3

What's the exact code you're using to push?

**Comment by miguelslobo** [comment]
@jelmer, thanks for your help.
This is the code I'm using. Very simple and plain before starting to compose it more for what I want:

from dulwich import porcelain

repo = "git@private_git_server.com:group/testingt.git"
name = "testing"
file_name = "stuff.txt"

def git_status(r):
    repo_status = porcelain.status(r)
    print repo_status

def git_clone(repo, name):
    porcelain.clone(repo, name)

def git_open(repo):
    r = porcelain.open_repo(name)
    return r

def git_add(repo, file):
    porcelain.add(repo, file)

def git_commit(repo, commit_msg):
    porcelain.commit(repo, commit_msg)

def git_log(repo):
    r = porcelain.log(repo)
    print r

def git_push(repo, remote_location):
    porcelain.push(repo, remote_location)

r = git_open(repo)
git_add(r, file_name)
git_commit(r, 'commit test')
git_push(r, repo)

----------

I can clone, add and commit without problems, but when trying to push to it to the repo, I get this error:

...
  File "/usr/local/lib/python2.7/site-packages/dulwich/porcelain.py", line 686, in push
    r.object_store.generate_pack_contents, progress=errstream.write)
  File "/usr/local/lib/python2.7/site-packages/dulwich/client.py", line 547, in send_pack
    new_refs = orig_new_refs = determine_wants(dict(old_refs))
  File "/usr/local/lib/python2.7/site-packages/dulwich/porcelain.py", line 672, in update_refs
    selected_refs.extend(parse_reftuples(r.refs, refs, refspecs))
  File "/usr/local/lib/python2.7/site-packages/dulwich/objectspec.py", line 115, in parse_reftuples
    ret.append(parse_reftuple(lh_container, rh_container, refspec))
  File "/usr/local/lib/python2.7/site-packages/dulwich/objectspec.py", line 75, in parse_reftuple
    if refspec.startswith(b"+"):
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by jelmer** [comment]
On Wed, Mar 29, 2017 at 06:37:38AM -0700, miguelslobo wrote:
> @jelmer, thanks for your help.
> This is the code I'm using. Very simple and plain before starting to compose it more for what I want:
> 
> from dulwich import porcelain
> 
> repo = "git@private_git_server.com:group/testingt.git"
> name = "testing"
> file_name = "stuff.txt"
> 
> def git_status(r):
>     repo_status = porcelain.status(r)
>     print repo_status
> 
> def git_clone(repo, name):
>     porcelain.clone(repo, name)
> 
> def git_open(repo):
>     r = porcelain.open_repo(name)
>     return r
> 
> def git_add(repo, file):
>     porcelain.add(repo, file)
> 
> def git_commit(repo, commit_msg):
>     porcelain.commit(repo, commit_msg)
> 
> def git_log(repo):
>     r = porcelain.log(repo)
>     print r
> 
> def git_push(repo, remote_location):
>     porcelain.push(repo, remote_location)
> 
> r = git_open(repo)
> git_add(r, file_name)
> git_commit(r, 'commit test')
> git_push(r, repo)
> 
> ----------
> 
> I can clone, add and commit without problems, but when trying to push to it to the repo, I get this error:
> 
> ...
>   File "/usr/local/lib/python2.7/site-packages/dulwich/porcelain.py", line 686, in push
>     r.object_store.generate_pack_contents, progress=errstream.write)
>   File "/usr/local/lib/python2.7/site-packages/dulwich/client.py", line 547, in send_pack
>     new_refs = orig_new_refs = determine_wants(dict(old_refs))
>   File "/usr/local/lib/python2.7/site-packages/dulwich/porcelain.py", line 672, in update_refs
>     selected_refs.extend(parse_reftuples(r.refs, refs, refspecs))
>   File "/usr/local/lib/python2.7/site-packages/dulwich/objectspec.py", line 115, in parse_reftuples
>     ret.append(parse_reftuple(lh_container, rh_container, refspec))
>   File "/usr/local/lib/python2.7/site-packages/dulwich/objectspec.py", line 75, in parse_reftuple
>     if refspec.startswith(b"+"):
> AttributeError: 'NoneType' object has no attribute 'startswith'
The third argument to porcelain.push() is not supposed to be optional yet. I'll see if I can fix it this weekend.

You'd want something like:

porcelain.push(repo, remote_location, repo.get_refs())

Jelmer

**Comment by miguelslobo** [comment]
I was able to get it to work, but not with your suggestions - repo.get_refs() - I've got this error:

```
   File "/usr/local/lib/python2.7/site-packages/dulwich/objectspec.py", line 75, in parse_reftuple
     if refspec.startswith(b"+"):
 AttributeError: 'Dict' object has no attribute 'startswith'
```
For the 3rd argument I've put the branch for where I wanted to push the commit. These are the changes I've made:
```
...
file_name = "stuff.txt"
branch = 'master'
...
def git_push(repo, remote_location, branch):
    print repo.get_refs()
    porcelain.push(repo, remote_location, branch)
...
git_push(r, repo, branch)
```
This way, all works as expected!
