### ISSUE TITLE
porecelain.add(files=None) adds files from root rather than os.getcwd()

### ISSUE THREAD

**Issue by fviolette** [jelmer/dulwich#521]
Hello,

Small issue with porcelain.add() not adding all modified/new files.

Tested with python 3.6 and dulwich (0.17.3), following syntax:

- porcelain.add(base_repo, paths=None)
- porcelain.add(base_repo)

porcelain.get_tree_changes(base_repo) returns {'add': [], 'delete': [], 'modify': []} in this case.

Thanks in advance for your help.

**Comment by jelmer** [comment]
Do you have some code that reproduces this? Dulwich has some tests for add without explicit paths specified and those pass. What platform are you on?

**Comment by fviolette** [comment]
Windows
Python 3.6.1
dulwich (0.17.3)

What I would like to use:
```
porcelain.open_repo(base_dir)
base_dir = os.path.join(script_dir, '../..')
porcelain.add(base_dir, paths=None)
```
What is working for me at the moment:
```
porcelain.open_repo(base_dir)
porcelain.add(base_dir, paths=[
    'reuse/metadata_Modules.dita',
    'reuse/metadata_Tasks.dita',
    'reuse/metadata_Products.dita',
    'common/taxonomy/' + rdf,
    'common/taxonomy/subjectscheme.ditamap',
    ...
])

**Comment by fviolette** [comment]
Retrying now, still with `paths=None` and I can get it to work _sometimes_ but I don't understand why.

I've checked for lockfiles, LF vs CRLF, closed my SourceTree instance and other Git processes that are running. Everything seems fine.

When it does move the files to the staging area, it's quite long (almost 30,000 files in the repo - only 20 should move up) and running `git status` takes ages after that. Likely that this is an issue with my setup but just to confirm that the repo does not need to be closed after all other operations?

More important, other files are promoted too:

- From the same base folder (e.g. `build/html/upload.py` - my script which runs is `build/taxonomy/taxonomy.py` and does affect the upload.py in any way by itself).
- From .gitignore'd subfolders (/out or /temp)

When it does not add any file, Traceback just gives `NoneType: None`.

**Comment by jelmer** [comment]
Yes, there shouldn't be a need to reopn the repo after running add.

What do you mean with "promoted" ?

**Comment by fviolette** [comment]
I do not reopen after add so this is fine.

For promoted, I meant other files that are not modified/added by my script or files that Git usually ignores are moved to the staging area.

For those under build/, it's the same content but all lines are replaced (.sh, .bat and .py files. The line endings are unchanged and OK). For those under out/ or temp/, these are new files created by script which get added. But they shouldn't.

**Comment by jelmer** [comment]
Dulwich currently doesn't support ignore files, files=None will add recursively from the repository root - not from the $PWD. That last bit should be easy to fix though. 

Does that match what you're seeing?

**Comment by fviolette** [comment]
Yes, it does behave as you describe.

**Comment by jelmer** [comment]
I've filed #524 about the lack of .gitignore support. The issue about recursing from $PWD is easy to fix, I'll change this bug to be about that.
