### ISSUE TITLE
No documentation for determine_wants in send_pack()

### ISSUE THREAD

**Issue by detly** [jelmer/dulwich#523]
I'm using the [`send_pack()`](https://github.com/jelmer/dulwich/blob/master/dulwich/client.py#L539) `client` method, and it takes an argument `determine_wants`. This isn't mentioned in the docs, and I can't discern what it's meant to do from the code (apart from be a function that returns a dict in the form `ref: sha`). It appears to be different from other `determine_wants` arguments in other classes.

Currently my `determine_wants()` function ignores the argument it gets and just returns a dict of all the refs I want to send, always the same. This seems to work, mostly, but I have no idea if it's correct.

Can you please clarify what this argument is?

**Comment by jsbain** [comment]
Check out https://github.com/jelmer/dulwich/blob/master/dulwich/porcelain.py#L683, which has an example that is used a few lines later on 697.

**Comment by detly** [comment]
Should the docs say `sha=None for deletions`? Because if I try that I get: `TypeError: old sha1 for b'refs/heads/magic' is not a bytestring None`. Should it be `ZERO_SHA` instead?

**Comment by jelmer** [comment]
Yes, indeed. FIxed now, thanks.
