### ISSUE TITLE
Using porcelain with proxy

### ISSUE THREAD

**Issue by akbargumbira** [jelmer/dulwich#545]
Hi @jelmer, how do one use porcelain and clone a repository using http proxy behind?

Thank you

**Comment by jelmer** [comment]
On Fri, Aug 04, 2017 at 01:57:21PM +0000, Akbar Gumbira wrote:
> Hi @jelmer, how do one use porcelain and clone a repository using http proxy behind?

Hi Akbar,

You should be able to set the regular proxy settings in the config, and Dulwich will pick those up.

[http]
proxy = http://some-proxy:3128/

If you'd like to avoid changing the config, you can also pass in a
custom urllib2 opener. See dulwich.client.default_urllib2_opener() for
an example.

Jelmer

**Comment by akbargumbira** [comment]
@jelmer thanks for the reply. For porcelain, I think it won't pick up since it doesn't pass config https://github.com/jelmer/dulwich/blob/master/dulwich/porcelain.py#L286 (the method called can be pased config though)

**Comment by jelmer** [comment]
Ah, that's a good point. I'll add some changes to have it road the right configs.

**Comment by akbargumbira** [comment]
@jelmer thanks for the fix. But right now if the proxy is not defined in the config, it will throw this error:
```
			  File "/home/akbar/.qgis2/python/plugins/qgis_resource_sharing-dev/resource_sharing/repository_handler/remote_git_handler.py", line 125, in download_collection
			    b'refs/heads/master'
			  File "/home/akbar/.qgis2/python/plugins/qgis_resource_sharing-dev/ext_libs/dulwich/porcelain.py", line 809, in pull
			    remote_location, config=r.get_config_stack())
			  File "/home/akbar/.qgis2/python/plugins/qgis_resource_sharing-dev/ext_libs/dulwich/client.py", line 1431, in get_transport_and_path
			    return get_transport_and_path_from_url(location, **kwargs)
			  File "/home/akbar/.qgis2/python/plugins/qgis_resource_sharing-dev/ext_libs/dulwich/client.py", line 1411, in get_transport_and_path_from_url
			    parsed, config=config, **kwargs), parsed.path
			  File "/home/akbar/.qgis2/python/plugins/qgis_resource_sharing-dev/ext_libs/dulwich/client.py", line 1218, in from_parsedurl
			    password=password, username=username, **kwargs)
			  File "/home/akbar/.qgis2/python/plugins/qgis_resource_sharing-dev/ext_libs/dulwich/client.py", line 1194, in __init__
			    self.opener = default_urllib2_opener(config)
			  File "/home/akbar/.qgis2/python/plugins/qgis_resource_sharing-dev/ext_libs/dulwich/client.py", line 1168, in default_urllib2_opener
			    proxy_server = config.get("http", "proxy")
			  File "/home/akbar/.qgis2/python/plugins/qgis_resource_sharing-dev/ext_libs/dulwich/config.py", line 429, in get
			    raise KeyError(name)
			KeyError: 'proxy'			
```

**Comment by jelmer** [comment]
Ah, sorry. I'm surprised the tests didn't catch that.

I'll commit a fix tonight.

**Comment by jelmer** [comment]
On Mon, Aug 14, 2017 at 11:19:21AM +0000, Akbar Gumbira wrote:
> @jelmer thanks for the fix. But right now if the proxy is not defined in the config, it will throw this error:
> ```
> 			  File "/home/akbar/.qgis2/python/plugins/qgis_resource_sharing-dev/resource_sharing/repository_handler/remote_git_handler.py", line 125, in download_collection
> 			    b'refs/heads/master'
> 			  File "/home/akbar/.qgis2/python/plugins/qgis_resource_sharing-dev/ext_libs/dulwich/porcelain.py", line 809, in pull
> 			    remote_location, config=r.get_config_stack())
> 			  File "/home/akbar/.qgis2/python/plugins/qgis_resource_sharing-dev/ext_libs/dulwich/client.py", line 1431, in get_transport_and_path
> 			    return get_transport_and_path_from_url(location, **kwargs)
> 			  File "/home/akbar/.qgis2/python/plugins/qgis_resource_sharing-dev/ext_libs/dulwich/client.py", line 1411, in get_transport_and_path_from_url
> 			    parsed, config=config, **kwargs), parsed.path
> 			  File "/home/akbar/.qgis2/python/plugins/qgis_resource_sharing-dev/ext_libs/dulwich/client.py", line 1218, in from_parsedurl
> 			    password=password, username=username, **kwargs)
> 			  File "/home/akbar/.qgis2/python/plugins/qgis_resource_sharing-dev/ext_libs/dulwich/client.py", line 1194, in __init__
> 			    self.opener = default_urllib2_opener(config)
> 			  File "/home/akbar/.qgis2/python/plugins/qgis_resource_sharing-dev/ext_libs/dulwich/client.py", line 1168, in default_urllib2_opener
> 			    proxy_server = config.get("http", "proxy")
> 			  File "/home/akbar/.qgis2/python/plugins/qgis_resource_sharing-dev/ext_libs/dulwich/config.py", line 429, in get
> 			    raise KeyError(name)
> 			KeyError: 'proxy'			
> ```

This should now be fixed in master.

**Comment by akbargumbira** [comment]
ok, thanks a lot @jelmer!
