### ISSUE TITLE
Release new dulwich version

### ISSUE THREAD

**Issue by Trane9991** [jelmer/dulwich#547]
Hello, 
could you, please, create new release version with the fixed issues (#543 to be precise).

Thank you.

**Comment by Trane9991** [comment]
@jelmer any updates on this?

**Comment by jelmer** [comment]
I'll probably do a release this week or next week.

**Comment by jelmer** [comment]
You should be able to run Dulwich out of Git. Is this not an option?

Alternatively, I can try and do a release this weekend.

**Comment by Trane9991** [comment]
Yeah, probably it would work, I will try later.

**Comment by jelmer** [comment]
e.g. pip should be able to install directly from git; if this doesn't work for Dulwich for some reason, please file a bug.

**Comment by jelmer** [comment]
Does that mean you managed to install from git?

**Comment by Trane9991** [comment]
Yes, it works, thanks.
