### ISSUE TITLE
Client fetch - exceptions.IOError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by earlchew** [jelmer/dulwich#549]
I encountered this error using commit 9511201. I looked at the differences between this and master, but was not able to discern any change that might have significantly changed the situation, but then again my knowledge of the code base is limited.

```
   File "dulwich/client.py", line 282, in fetch
     progress)
   File "dulwich/client.py", line 624, in fetch_pack
     proto, negotiated_capabilities, graph_walker, wants, can_read)
   File "dulwich/client.py", line 460, in _handle_upload_pack_head
     have = next(graph_walker)
   File "dulwich/object_store.py", line 1107, in next
     ps = self.get_parents(ret)
   File "dulwich/repo.py", line 372, in get_parents
     commit = self[sha]
   File "dulwich/repo.py", line 470, in __getitem__
     return self.object_store[name]
   File "dulwich/object_store.py", line 118, in __getitem__
     type_num, uncomp = self.get_raw(sha)
   File "dulwich/object_store.py", line 367, in get_raw
     return pack.get_raw(sha)
   File "dulwich/pack.py", line 1914, in get_raw
     obj_type, obj = self.data.get_object_at(offset)
   File "dulwich/pack.py", line 1840, in data
     self._data = self._data_load()
   File "dulwich/pack.py", line 1811, in <lambda>
     self._data_load = lambda: PackData(self._data_path)
   File "dulwich/pack.py", line 994, in __init__
     self._file = GitFile(self._filename, 'rb')
   File "dulwich/file.py", line 89, in GitFile
     return io.open(filename, mode, bufsize)
 exceptions.IOError: [Errno 24] Too many open files: 'master.git/objects/pack/pack-b9c8098c1e6b95c3724fde0f72ce2bb422c11d7c.pack'

2017-08-12 05:35:43Z:16284: lr-x------ 1 earl earl 64 2017-08-11 22:35:43.361756 559 -0700 10 -> /master.git/objects/pack/pack-b3f4c34cd71f52fd4e11ca32dbc3347aaeccdb23.pack
2017-08-12 05:35:43Z:16284: lr-x------ 1 earl earl 64 2017-08-11 22:35:43.361756 559 -0700 1000 -> //master.git/objects/pack/pack-fd4a2a0fc6735c28f6fefad8f01d92e18723f3c4.pack
2017-08-12 05:35:43Z:16284: lr-x------ 1 earl earl 64 2017-08-11 22:35:43.361756 559 -0700 1001 -> /master.git/objects/pack/pack-952b40e7156374ce9bb828394859b8be4083e93d.pack
...
```

Each instance of `class Pack` lazily populates itself with an instance of `class PackData` retaining it until the method `close()` is called. In turn each instance of `class PackData` holds a file descriptor via `class GitFile`.

This means that the number of file descriptors is directly related to the number of active pack objects, which I suppose is related to the graph walking algorithms and the structure of the git metadata. Without detailed knowledge of either, I was wondering whether it's worth loosening the relationship between these and the number of active file descriptors to avoid the chance of EMFILE entirely.

In particular, I notice that `class PackData` only reads the underlying file. Furthermore, apart from its effect on performance, the only other reason to hold the file open is to guard against file name being removed, renamed, etc, and I do not think this reason is key in this scenario.

So I have two thoughts in order to avoid the number of open files scale with the number of active packs:
* Only open the file when `class PackData` needs to read data, and then close the file thereafter
* If performance is a concern, and there is some notion of locality, provide `class PackData` with a small cache of files

Is this still an issue on master?

Does the above make sense, or is another approach suggested?

**Comment by jelmer** [comment]
On Sat, Aug 12, 2017 at 09:08:33AM -0700, earlchew wrote:
> I encountered this error using commit 9511201. I looked at the differences between this and master, but was not able to discern any change that might have significantly changed the situation, but then again my knowledge of the code base is limited.
> 
> ```
>    File "dulwich/client.py", line 282, in fetch
>      progress)
>    File "dulwich/client.py", line 624, in fetch_pack
>      proto, negotiated_capabilities, graph_walker, wants, can_read)
>    File "dulwich/client.py", line 460, in _handle_upload_pack_head
>      have = next(graph_walker)
>    File "dulwich/object_store.py", line 1107, in next
>      ps = self.get_parents(ret)
>    File "dulwich/repo.py", line 372, in get_parents
>      commit = self[sha]
>    File "dulwich/repo.py", line 470, in __getitem__
>      return self.object_store[name]
>    File "dulwich/object_store.py", line 118, in __getitem__
>      type_num, uncomp = self.get_raw(sha)
>    File "dulwich/object_store.py", line 367, in get_raw
>      return pack.get_raw(sha)
>    File "dulwich/pack.py", line 1914, in get_raw
>      obj_type, obj = self.data.get_object_at(offset)
>    File "dulwich/pack.py", line 1840, in data
>      self._data = self._data_load()
>    File "dulwich/pack.py", line 1811, in <lambda>
>      self._data_load = lambda: PackData(self._data_path)
>    File "dulwich/pack.py", line 994, in __init__
>      self._file = GitFile(self._filename, 'rb')
>    File "dulwich/file.py", line 89, in GitFile
>      return io.open(filename, mode, bufsize)
>  exceptions.IOError: [Errno 24] Too many open files: 'master.git/objects/pack/pack-b9c8098c1e6b95c3724fde0f72ce2bb422c11d7c.pack'
> ```
How many files are there in master.git/objects/pack ?

Jelmer

**Comment by earlchew** [comment]
```
$ ulimit -a
...
open files                      (-n) 1024
```

```
$ ls -1 ~/Development/jaybot-dev/master.git/objects/pack | wc -l
1238
```

At termination, the process has `*.pack` and `*.idx` files open:

```
2017-08-17 09:30:44Z:13547: python  13547 earl  txt    REG  252,1  3341384   6946836 /usr/bin/python2.7
2017-08-17 09:30:44Z:13547: python  13547 earl  mem    REG  252,1     1212    542258 /master.git/objects/pack/pack-3b221c543215d11aa47215b54cb967c21d2da7f3.idx
2017-08-17 09:30:44Z:13547: python  13547 earl  mem    REG  252,1     1156    547344 /master.git/objects/pack/pack-0144c02b3e006c6e5a83e8d26923407bfc14e60b.idx
...
2017-08-17 09:30:44Z:13547: python  13547 earl 1021r   REG  252,1     2712    546012 /master.git/objects/pack/pack-d9155108c8946d99569591cab269ae77ce6c0235.pack
2017-08-17 09:30:44Z:13547: python  13547 earl 1022r   REG  252,1     2527    534477 /master.git/objects/pack/pack-428ef0bb615726b789f8a031a01d52aabf78e33c.pack
2017-08-17 09:30:44Z:13547: python  13547 earl 1023r   REG  252,1     5913    530100 /master.git/objects/pack/pack-e8b01ef42794e9073c568a5a0216b289237e4201.pack
```

**Comment by jelmer** [comment]
On Thu, Aug 17, 2017 at 08:14:57AM -0700, earlchew wrote:
> ```
> $ ulimit -a
> ...
> open files                      (-n) 1024
> ```
> 
> ```
> $ ls -1 ~/Development/jaybot-dev/master.git/objects/pack | wc -l
> 1238
> ```
> 
> At termination, the process has `*.pack` and `*.idx` files open:
> 
> ```
> 2017-08-17 09:30:44Z:13547: python  13547 earl  txt    REG  252,1  3341384   6946836 /usr/bin/python2.7
> 2017-08-17 09:30:44Z:13547: python  13547 earl  mem    REG  252,1     1212    542258 /master.git/objects/pack/pack-3b221c543215d11aa47215b54cb967c21d2da7f3.idx
> 2017-08-17 09:30:44Z:13547: python  13547 earl  mem    REG  252,1     1156    547344 /master.git/objects/pack/pack-0144c02b3e006c6e5a83e8d26923407bfc14e60b.idx
> ...
> 2017-08-17 09:30:44Z:13547: python  13547 earl 1021r   REG  252,1     2712    546012 /master.git/objects/pack/pack-d9155108c8946d99569591cab269ae77ce6c0235.pack
> 2017-08-17 09:30:44Z:13547: python  13547 earl 1022r   REG  252,1     2527    534477 /master.git/objects/pack/pack-428ef0bb615726b789f8a031a01d52aabf78e33c.pack
> 2017-08-17 09:30:44Z:13547: python  13547 earl 1023r   REG  252,1     5913    530100 /master.git/objects/pack/pack-e8b01ef42794e9073c568a5a0216b289237e4201.pack
> ```

Does C git work on this repository? I think the main issue here is that the repository isn't regularly repacked (#296).

Jelmer

**Comment by earlchew** [comment]
> Does C git work on this repository?

Yes, it does, and the result seems to confirm your supposition that https://github.com/jelmer/dulwich/issues/296 is the main problem:

```
$ ls -1 objects/pack | wc
   1238    1238   63138
$ git fetch origin
remote: Counting objects: 272, done.
...
 * [new branch] ...
...
 * [new tag] ...
...
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
$ find objects/pack -type f | wc
      2       2     127
```

Earlier, I found https://github.com/jelmer/dulwich/issues/281, so after each successful fetch, I call:
```
            self.__repo.object_store.pack_loose_objects()
```

That does not seem to mitigate https://github.com/jelmer/dulwich/issues/296, and until https://github.com/jelmer/dulwich/issues/296 is fixed it seems to me that the only way to mitigate its absence is to either be more frugal with the use of file descriptors, or discard and re-clone the repository.

Can you suggest any other options?

**Comment by jelmer** [comment]
I've added a really basic repack implementation (repo.object_store.repack) in master which you can call. 

This still has various limitations, most notably:
 * it currently caches all objects in memory while it repacks
 * it's not triggered automatically, you have to call it manually
