### ISSUE TITLE
When committing a pack, file should be flushed prior to fsync() of fd

### ISSUE THREAD

**Issue by earlchew** [jelmer/dulwich#556]
```
        def commit():
            os.fsync(fd)
            f.close()
```

**Comment by jelmer** [comment]
On Sat, Aug 26, 2017 at 07:58:51AM -0700, earlchew wrote:
> ```
>         def commit():
>             os.fsync(fd)
>             f.close()
> ```

There are probably a few places like this where Dulwich relies on
ext3 data=ordered behaviour. We need a more holistic approach to this:

When writing refs, packs, objects and the index, flush + fsync
before closing: perhaps just do this in GitFile.close ?

**Comment by earlchew** [comment]
I think you are proposing that `add_pack()` just use `class GitFile` directly (rather than resorting to `tempfile.mkstemp()`), and that the flush-fsync-close semantics be applied to `class GitFile`.

Is that what you are suggesting?

**Comment by jelmer** [comment]
On Tue, Aug 29, 2017 at 01:14:06AM +0000, earlchew wrote:
> I think you are proposing that `add_pack()` just use `class GitFile` directly (rather than resorting to `tempfile.mkstemp()`), and that the flush-fsync-close semantics be applied to `class GitFile`.

> Is that what you are suggesting?
Yep, I am indeed suggesting the flush-fsync-close semantics are added to GitFile.

We can't use GitFile directly in add_pack(), because it requires the
name of the file be known upfront - and the name of a pack file isn't
known until the file is completely written (as it includes a SHA of
all of the objects inside).

**Comment by earlchew** [comment]
> because it requires the name of the file be known upfront 

Well, that's true, but I think the name is not actually required until the file is closed, so if a `rename()` method were to be supported, the correct name could be imposed at any time prior to that.

Additionally, the current temporary flie semantics could be supported by allowing for an additional argument to the `GitFile` constructor:

```
def GitFile(...., fd=None):
    ...
    if fd is None:
        fd = os.open(...)
    self._file = os.fdopen(fd, ...)
```

**Comment by jelmer** [comment]
On Tue, Aug 29, 2017 at 03:21:29PM +0000, earlchew wrote:
> > because it requires the name of the file be known upfront 
> 
> Well, that's true, but I think the name is not actually required until the file is closed, so if a `rename()` method were to be supported, the correct name could be imposed at any time prior to that.
> 
> Additionally, the current temporary flie semantics could be supported by allowing for an additional argument to the `GitFile` constructor:
> 
> ```
> def GitFile(...., fd=None):
>     ...
>     if fd is None:
>         fd = os.open(...)
>     self._file = os.fdopen(fd, ...)
> ```
I'd rather avoid overloading the interface of GitFile, but I guess
that's not too bad.

**Comment by jelmer** [comment]
On Tue, Aug 29, 2017 at 03:21:29PM +0000, earlchew wrote:
> > because it requires the name of the file be known upfront 
> 
> Well, that's true, but I think the name is not actually required until the file is closed, so if a `rename()` method were to be supported, the correct name could be imposed at any time prior to that.
> 
> Additionally, the current temporary flie semantics could be supported by allowing for an additional argument to the `GitFile` constructor:
> 
> ```
> def GitFile(...., fd=None):
>     ...
>     if fd is None:
>         fd = os.open(...)
>     self._file = os.fdopen(fd, ...)
> ```
I'd rather avoid overloading the interface of GitFile too much, but I
guess just that is not not too bad.

**Comment by jelmer** [comment]
ping, any news on this?

**Comment by earlchew** [comment]
@jelmer I think we had a mis-communication. I recall I saw a related commit from you, and thought that you were not interested in doing this any more.

**Comment by jelmer** [comment]
On Sun, Nov 05, 2017 at 06:09:07PM +0000, earlchew wrote:
> @jelmer I think we had a mis-communication. I recall I saw a related commit from you, and thought that you were not interested in doing this any more.
Ah, sorry. Yes, I am definitely interested in addressing this, though
we should be careful with where we add syncs since they have a way to
slow things down unnecessarily and it's easy to miss a spot.

-- 
Jelmer Vernooĳ <jelmer@jelmer.uk>
PGP Key: https://www.jelmer.uk/D729A457.asc

**Comment by jelmer** [comment]
This is now implemented.
