### ISSUE TITLE
add folder to repository fail

### ISSUE THREAD

**Issue by albus12138** [jelmer/dulwich#564]
When I try to stage a empty folder to my repository, I got this Traceback. Should I use another method?

> Traceback (most recent call last):
>  File "<input>", line 1, in <module>
>  File "C:\Users\Project\.env\lib\site-packages\dulwich\repo.py", line 872, in stage
>    blob = blob_from_path_and_stat(full_path, st)
>  File "C:\Users\Project\.env\lib\site-packages\dulwich\index.py", line 555, in blob_from_path_and_stat
>    with open(fs_path, 'rb') as f:
>PermissionError: [Errno 13] Permission denied: b'backup\\111'

"111" is an empty folder. I think the reason of this exception is that "open" function cannot handle a directory. But I don't found another methods to solve this from api document.

**Comment by jelmer** [comment]
Directories don't need to be explicitly staged. Dulwich should probably ignore requests to stage directories.
