### ISSUE TITLE
'origin' parameter in porcelain.clone() doesn't correctly set the origin

### ISSUE THREAD

**Issue by minddrive** [jelmer/dulwich#565]
Using dulwich 0.18.4, Python 3.6, macOS 10.12 (Sierra)

An attempt to use porcelain.clone() and set the origin to something other than 'origin' via the parameter fails to do so; a 'git remote -v' after the fact still shows it named 'origin'.  The errant code in question can be found at https://github.com/jelmer/dulwich/blob/master/dulwich/porcelain.py#L326-L329

**Comment by jelmer** [comment]
Fixed in master
