### ISSUE TITLE
Auth bearer token support in porcelain

### ISSUE THREAD

**Issue by rockkickerdeluxe** [jelmer/dulwich#569]
Attempting to connect to a VSO repo (https://www.visualstudio.com/vso), and I get the following error:

> File "C:\Program Files\Python36\lib\site-packages\dulwich\porcelain.py", line 1060, in ls_remote
>     return client.get_refs(host_path)
>   File "C:\Program Files\Python36\lib\site-packages\dulwich\client.py", line 1429, in get_refs
>     b"git-upload-pack", url)
>   File "C:\Program Files\Python36\lib\site-packages\dulwich\client.py", line 1282, in _discover_references
>     resp, read = self._http_request(url, headers, allow_compression=True)
>   File "C:\Program Files\Python36\lib\site-packages\dulwich\client.py", line 1261, in _http_request
>     resp = self.opener.open(req)
>   File "C:\Program Files\Python36\lib\urllib\request.py", line 532, in open
>     response = meth(req, response)
>   File "C:\Program Files\Python36\lib\urllib\request.py", line 642, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "C:\Program Files\Python36\lib\urllib\request.py", line 564, in error
>     result = self._call_chain(*args)
>   File "C:\Program Files\Python36\lib\urllib\request.py", line 504, in _call_chain
>     result = func(*args)
>   File "C:\Program Files\Python36\lib\urllib\request.py", line 1028, in http_error_401
>     url, req, headers)
>   File "C:\Program Files\Python36\lib\urllib\request.py", line 972, in http_error_auth_reqed
>     scheme)
> ValueError: AbstractBasicAuthHandler does not support the following scheme: 'Bearer'
> 

My code snippet is:

porcelain.ls_remote("https://username:password@VSORepo")

**Comment by jelmer** [comment]
The default urllib opener in Dulwich only handles basic authentication. You'd need to pass in a custom urllib opener that handles this kind of authentication.

**Comment by rockkickerdeluxe** [comment]
@jelmer Is this possible using Porcelain?

**Comment by jelmer** [comment]
Alas, no. Though it should be easy to plumb through the "opener" argument to ls_remote().

You can also directly call the client:

    config = StackedConfig.default()
    client, host_path = get_transport_and_path(remote, config=config, opener=opener)
    print client.get_refs(host_path)

**Comment by rockkickerdeluxe** [comment]
Sorry, but i'm a bit confused. Is there an API doc that shows "opener" as an argument to ls_remote? The only place I see ls_remote is in porcelain.

I'll be working with VSO, so I guess i'll be relying on the client. Is there any doc or something similar that shows some Dulwich equivalents to the Porcelain methods? Just looking for the basics, clone/add/push etc.

**Comment by jelmer** [comment]
porcelain.ls_remote is a really trivial wrapper around GitClient.get_refs() - see https://github.com/jelmer/dulwich/blob/master/dulwich/porcelain.py#L1052.

You can use the tiny bit of code I pasted above to get the refs of a remote URL while being able to pass in an opener object.

**Comment by jelmer** [comment]
Actually, you are probably also able to call urllib.request.install_opener(opener) and then use the porcelain methods.

**Comment by rockkickerdeluxe** [comment]
Thanks. I managed to get it to work with the following:

```
opener = urllib.request.build_opener()
opener.addheaders = [('Authorization', 'Basic MY_TOKEN')]

config = dulwich.config.StackedConfig.default()
client, host_path = dulwich.client.get_transport_and_path(
    "VSORepo",
    config=config,
    opener=opener)
print(client.get_refs(host_path))
```

I'd really like to use porcelain though since I don't think I can use Dulwich by itself. I tried the following, but I get a 401 (doesn't look like the opener is getting used)

```
opener = urllib.request.build_opener()
opener.addheaders = [('Authorization', 'Basic MY_TOKEN')]
urllib.request.install_opener(opener)
porcelain.ls_remote("VSORepo")
```

Any thoughts or ideas how I could get this to work with Porcleain?

**Comment by jelmer** [comment]
Please try the 'porcelain-pass-kwargs' branch. It should allow you to pass a keyword argument called 'opener' to porcelain.ls_remote.

**Comment by rockkickerdeluxe** [comment]
Yes, that seems to work! Tested with clone as well. Thanks!

**Comment by jelmer** [comment]
Ah, great. I'll see if I can get this into master as well then.

**Comment by rockkickerdeluxe** [comment]
@jelmer  Any estimates on when this will get into master?

**Comment by jelmer** [comment]
Merged!

**Comment by rockkickerdeluxe** [comment]
@jelmer  Sorry if i'm missing something, but I don't see that it's merged.

**Comment by ianseyer** [comment]
Would just like to add visibility - this is not merged in master. Would be great to be able to pass `opener` args to porcelain.

**Comment by tejasvi** [comment]
@ianseyer It is merged. See https://github.com/dulwich/dulwich/tree/porcelain-pass-kwargs The opener argument trickles down using **kwargs
