### ISSUE TITLE
Cannot create a new branch on an empty repo

### ISSUE THREAD

**Issue by MattSable** [jelmer/dulwich#571]
On Git, I can do the following:

```
git init
git checkout -b testBranch
```

Which will create testBranch. If I try to replicate this in Porcelain with the following:

```
repo = dulwich.porcelain.init("./testDir")
dulwich.porcelain.branch_create(repo, b"testBranch")
```

I get this error:
```
  File "C:\Program Files\Python36\lib\site-packages\dulwich\porcelain.py", line 1019, in branch_create
    object = parse_object(r, objectish)
  File "C:\Program Files\Python36\lib\site-packages\dulwich\objectspec.py", line 39, in parse_object
    return repo[objectish]
  File "C:\Program Files\Python36\lib\site-packages\dulwich\repo.py", line 476, in __getitem__
    return self.object_store[self.refs[name]]
  File "C:\Program Files\Python36\lib\site-packages\dulwich\refs.py", line 256, in __getitem__
    raise KeyError(name)
```

**Comment by MattSable** [comment]
Realizing this is likely intentional, and that a commit is required first. @jelmer, can you confirm?

**Comment by jelmer** [comment]
On Thu, Nov 02, 2017 at 06:28:38PM +0000, Matt wrote:
> Realizing this is likely intentional, and that a commit is required first. @jelmer, can you confirm?
Yeah, this is not a valid operation in C git either:

~% cd /tmp 
/tmp% git init blah
Initialized empty Git repository in /tmp/blah/.git/
/tmp% cd blah
/tmp/blah% git branch foo
fatal: Not a valid object name: 'master'.

You could change the name of the nascent branch that "HEAD" refers to? What are
you trying to do exactly? What's the C git command you're trying to match?

**Comment by MattSable** [comment]
I was originally just trying to imitate my powershell git workflow, but there's no reason to. Will close this.
