### ISSUE TITLE
Porcelain push broken

### ISSUE THREAD

**Issue by MattSable** [jelmer/dulwich#572]
If I try to push with the following code:

```
repo_url = "MY_REPO" #MY_REPO is a repo with just a master branch and README.md
r = dulwich.porcelain.clone(repo_url, "./test_dir")
with open("./test_dir" + "/text.txt", "w") as fo:
    fo.write("Foo")
dulwich.porcelain.add(r)
dulwich.porcelain.commit(r, b"bar!")
dulwich.porcelain.push(r, repo_url, "master")
```

I get the following error:

```
  File "C:\Program Files\Python36\lib\site-packages\dulwich\porcelain.py", line 775, in push
    progress=errstream.write)
  File "C:\Program Files\Python36\lib\site-packages\dulwich\client.py", line 1361, in send_pack
    new_refs = update_refs(dict(old_refs))
  File "C:\Program Files\Python36\lib\site-packages\dulwich\porcelain.py", line 760, in update_refs
    selected_refs.extend(parse_reftuples(r.refs, refs, refspecs))
  File "C:\Program Files\Python36\lib\site-packages\dulwich\objectspec.py", line 130, in parse_reftuples
    ret.append(parse_reftuple(lh_container, rh_container, refspec))
  File "C:\Program Files\Python36\lib\site-packages\dulwich\objectspec.py", line 90, in parse_reftuple
    if refspec.startswith(b"+"):
TypeError: startswith first arg must be str or a tuple of str, not bytes
```

I got the push syntax from (https://www.dulwich.io/docs/tutorial/porcelain.html). If I instead do it like found in test_porcelain.py, like this:

`dulwich.porcelain.push(r, repo_url, b"HEAD:refs/heads/master")`
or
`dulwich.porcelain.push(r, repo_url, b"refs/heads/master")`

then I get the following:

```
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\dulwich\porcelain.py", line 775, in push
    progress=errstream.write)
  File "C:\Program Files\Python36\lib\site-packages\dulwich\client.py", line 1381, in send_pack
    resp_proto, negotiated_capabilities, progress)
  File "C:\Program Files\Python36\lib\site-packages\dulwich\client.py", line 520, in _handle_receive_pack_tail
    self._report_status_parser.check()
  File "C:\Program Files\Python36\lib\site-packages\dulwich\client.py", line 151, in check
    raise SendPackError(self._pack_status)
dulwich.errors.SendPackError: b"unpack error The tree object f14e86be8c84129eff25a25bfcd97615e84f8f03 was rejected: The tree contains an entry with an invalid entry name of '..'."
```

**Comment by jelmer** [comment]
On Thu, Nov 02, 2017 at 06:26:48PM +0000, Matt wrote:
> If I try to push with the following code:
> 
> ```
> repo_url = "MY_REPO"
> r = dulwich.porcelain.clone(repo_url, "./test_dir")
> with open("./test_dir" + "/text.txt", "w") as fo:
>     fo.write("Foo")
> dulwich.porcelain.add(r)
> dulwich.porcelain.commit(r, b"bar!")
> dulwich.porcelain.push(r, repo_url, "master")
> ```
> 
> I get the following error:
> 
> ```
>   File "C:\Program Files\Python36\lib\site-packages\dulwich\porcelain.py", line 775, in push
>     progress=errstream.write)
>   File "C:\Program Files\Python36\lib\site-packages\dulwich\client.py", line 1361, in send_pack
>     new_refs = update_refs(dict(old_refs))
>   File "C:\Program Files\Python36\lib\site-packages\dulwich\porcelain.py", line 760, in update_refs
>     selected_refs.extend(parse_reftuples(r.refs, refs, refspecs))
>   File "C:\Program Files\Python36\lib\site-packages\dulwich\objectspec.py", line 130, in parse_reftuples
>     ret.append(parse_reftuple(lh_container, rh_container, refspec))
>   File "C:\Program Files\Python36\lib\site-packages\dulwich\objectspec.py", line 90, in parse_reftuple
>     if refspec.startswith(b"+"):
> TypeError: startswith first arg must be str or a tuple of str, not bytes
> ```
> 
> I got the push syntax from (https://www.dulwich.io/docs/tutorial/porcelain.html). If I instead do it like found in test_porcelain.py, like this:
> 
> `dulwich.porcelain.push(r, repo_url, b"HEAD:refs/heads/master")`
> 
> then I get the following:
> 
> ```
> Traceback (most recent call last):
>   File "C:\Program Files\Python36\lib\site-packages\dulwich\porcelain.py", line 775, in push
>     progress=errstream.write)
>   File "C:\Program Files\Python36\lib\site-packages\dulwich\client.py", line 1381, in send_pack
>     resp_proto, negotiated_capabilities, progress)
>   File "C:\Program Files\Python36\lib\site-packages\dulwich\client.py", line 520, in _handle_receive_pack_tail
>     self._report_status_parser.check()
>   File "C:\Program Files\Python36\lib\site-packages\dulwich\client.py", line 151, in check
>     raise SendPackError(self._pack_status)
> dulwich.errors.SendPackError: b"unpack error The tree object f14e86be8c84129eff25a25bfcd97615e84f8f03 was rejected: The tree contains an entry with an invalid entry name of '..'."
> ```

What version of Dulwich are you running?

**Comment by MattSable** [comment]
Version: 0.18.5

**Comment by jelmer** [comment]
I've pushed an error check to master that should be clearer.

**Comment by tiny-dancer** [comment]
i'm encountering same issue for the below code - is there a link to PR, updated docs, etc?

```python
porcelain.push(tar_name, f"https://${username}:{token}@github.optum.com/CommercialCloud-Redbox-Azure/mgrose3-04.git", "master")
```

**Comment by tiny-dancer** [comment]
Update:

switching to `b"refs/heads/master"` solved issue. not sure if tutorial code if this expected as tutorial docs use `master`?

**Comment by jelmer** [comment]
Oops, that looks like a regression. Fixed in master
