### ISSUE TITLE
tar archive: Set gzip 'mtime' header

### ISSUE THREAD

**Issue by jonashaag** [jelmer/dulwich#577]
From jonashaag/klaus#203: Tarball downloads always have different file hashes because the [gzip file modification time header field](http://www.onicos.com/staff/iz/formats/gzip.html) is set in Python's tarfile implementation to `time.time()` (see [source code](https://github.com/python/cpython/blob/0e163d2ced28ade8ff526e8c663faf03c2c0b168/Lib/tarfile.py#L425)).

This is an open bug in CPython: https://bugs.python.org/issue31526

We could work around this be manually overwriting the gzip header field with the `mtime` argument in `dulwich.archive.tar_stream`.

If you're not interested in having this in Dulwich, I can also put it into klaus. Although I think this might be interesting for other Dulwich users as well.

**Comment by jelmer** [comment]
Yeah, that seems like a useful thing to do in tar_stream.
