### ISSUE TITLE
Unable to delete cloned repo from within same Python process

### ISSUE THREAD

**Issue by MattSable** [jelmer/dulwich#584]
If I clone a repo and then try to delete it, I get:

`PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Temp\\tmp2mjvpymq\\.git\\objects\\pack\\pack-acc7c293230a64c24a6c46faa4fdf8f2f3fe9a12.idx`

This can be seen with the following code:

```
from dulwich import porcelain
import shutil

repo_path = "./to_delete"
porcelain.clone("https://github.com/jelmer/dulwich.git", repo_path)
shutil.rmtree(repo_path)

```

**Comment by jelmer** [comment]
On Thu, Nov 16, 2017 at 10:35:45PM +0000, Matt wrote:
> If I clone a repo and then try to delete it, I get:
> 
> PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Temp\\tmp2mjvpymq\\.git\\objects\\pack\\pack-acc7c293230a64c24a6c46faa4fdf8f2f3fe9a12.idx'
Can you provide some code that reproduces this?

-- 
Jelmer Vernooĳ <jelmer@jelmer.uk>
PGP Key: https://www.jelmer.uk/D729A457.asc

**Comment by MattSable** [comment]
Updated the OP. My actual goal is to just get the files from a repo, without any association to git. I'm trying to do this by cloning the repo and removing the .git folder. Is there any other way to do this?

**Comment by jelmer** [comment]
Ah, thanks. Can you try calling .close() on the object returned by porcelain.clone() before calling rmtree() ?

**Comment by MattSable** [comment]
That works. Thanks!

**Comment by moresayali246** [comment]
> Ah, thanks. Can you try calling .close() on the object returned by porcelain.clone() before calling rmtree() ?

can u please elaborate
