### ISSUE TITLE
porcelain reset doesn't work

### ISSUE THREAD

**Issue by MattSable** [jelmer/dulwich#588]
```
directory = "./test_dir"

file_path_1 = os.path.join(directory, "text.txt")
r = porcelain.init(directory)
with open(file_path_1, "w") as fo:
    fo.write("Foo")
porcelain.add(r, [file_path_1])
commit = porcelain.commit(r, b"foo!")


file_path_2 = os.path.join(directory, "text2.txt")
with open(file_path_2, "w") as fo:
    fo.write("Bar!")
porcelain.add(r, [file_path_2])
porcelain.commit(r, b"bar!")

porcelain.reset(r, "hard", commit)

```

The reset statement doesn't actually seem to do anything.

**Comment by jelmer** [comment]
On Mon, Nov 27, 2017 at 10:20:56PM +0000, Matt wrote:
> ```
> directory = "./test_dir"
> 
> file_path_1 = os.path.join(directory, "text.txt")
> r = porcelain.init(directory)
> with open(file_path_1, "w") as fo:
>     fo.write("Foo")
> porcelain.add(r, [file_path_1])
> commit = porcelain.commit(r, b"foo!")
> 
> 
> file_path_2 = os.path.join(directory, "text2.txt")
> with open(file_path_2, "w") as fo:
>     fo.write("Bar!")
> porcelain.add(r, [file_path_2])
> porcelain.commit(r, b"bar!")
> 
> porcelain.reset(r, "hard", commit)
> 
> ```
> 
> The reset statement doesn't actually seem to do anything.
The reset statement currently doesn't remove old versioned files due
to #452. But otherwise, it should funciton fine. Does 'git tsatus'
report 'text2' as unknown after running reset() ?

-- 
Jelmer Vernooĳ <jelmer@jelmer.uk>
PGP Key: https://www.jelmer.uk/D729A457.asc

**Comment by MattSable** [comment]
git status reports "nothing to commit". 
git log shows both commits.

**Comment by MattSable** [comment]
@jelmer Funny enough, for my specific use case, I don't care about the reset. My goal is that given a repo and a commit's sha, I want the files on disk to match what the contents of the repo were at that specific commit. Is there any other way to do this?

**Comment by MattSable** [comment]
Interestingly enough, i'm unable to get build_index_from_tree to work correctly anymore. I don't remember when I last saw it working and if it's possibly a regression in 0.18.6. Unless I was doing something different earlier and don't remember, the following also used to work for me but has stopped:

```
    def checkout(repo, branch_to_switch_to):        
	dulwich.index.build_index_from_tree(
		repo.path,
		repo.index_path(),
		repo.object_store,
		repo[b"refs/remotes/origin/" + branch_to_switch_to.encode()].tree)
	porcelain.update_head(repo, "refs/remotes/origin/"+branch_to_switch_to)
```

**Comment by MattSable** [comment]
Sorry, I think I may have just misunderstood something. You said reset doesn't remove old files, but should build_index_from_tree()? If not, is there anyway to do that without manually deleting all files in the repo (except the .git folder) and then doing a build_index_from_tree()?

**Comment by jsbain** [comment]
I use the following in my version of checkout, which builds the working copy, then deletes files which were in the old tree, but not the new one (thus, files which were untracked are not deleted).

``` 
dulwich.index.build_index_from_tree(repo.path,
                                  repo.index_path(),
                                  repo.object_store, 
                                  repo[branch_ref].tree)
            try:
                oldtree=repo[repo['HEAD'].tree]
                newtree=repo[repo[branch_ref].tree]
                for f in repo.object_store.iter_tree_contents(oldtree.id):
                   if f.path not in newtree:
                       #delete files that were in old branch, but not new
                       os.remove(os.path.join(repo.path,f.path))
            except KeyError:
                sys.stderr.write('could not delete files')
```

**Comment by MattSable** [comment]
Great, that seems to work. How do I actually get the index to be in the same state as a hard reset though? Running your code combined with my snippet produces this when running 'git status'

```
On branch master

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        new file:   text.txt

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    text2.txt
```

**Comment by jelmer** [comment]
On Fri, Dec 01, 2017 at 07:42:22AM -0800, Matt wrote:
> Great, that seems to work. How do I actually get the index to be in the same state as a hard reset though? Running your code combined with my snippet produces this when running 'git status'
> 
> ```
> On branch master
> 
> Changes to be committed:
>   (use "git reset HEAD <file>..." to unstage)
> 
>         new file:   text.txt
> 
> Changes not staged for commit:
>   (use "git add/rm <file>..." to update what will be committed)
>   (use "git checkout -- <file>..." to discard changes in working directory)
> 
>         deleted:    text2.txt
> ```
You'd also need to update the "HEAD" ref accordingly.

-- 
Jelmer Vernooĳ <jelmer@jelmer.uk>
PGP Key: https://www.jelmer.uk/D729A457.asc

**Comment by MattSable** [comment]
Sorry, I edited the post shortly after I originally made it. I was already doing `r[b'HEAD'] = commit` which I think is what you mean by ]updating the "HEAD' ref. This does point the head to the correct commit, but I still see the changes show up in status.

**Comment by jelmer** [comment]
On Fri, Dec 01, 2017 at 06:12:13PM +0000, Matt wrote:
> Sorry, I edited the post shortly after I originally made it. I was already doing `r[b'HEAD'] = commit` which I think is what you mean by ]updating the "HEAD' ref. This does point the head to the correct commit, but I still see the changes show up in status.
Are you testing on Windows or on Linux?

-- 
Jelmer Vernooĳ <jelmer@jelmer.uk>
PGP Key: https://www.jelmer.uk/D729A457.asc

**Comment by MattSable** [comment]
Windows. Here's the exact code snippet i'm using if you could run it on unix:

```
directory = "./delete_this"
file_path_1 = os.path.join(directory, "text.txt")
file_path_2 = os.path.join(directory, "text2.txt")
r = porcelain.init(directory)

with open(file_path_1, "w") as fo:
    fo.write("Foo")
porcelain.add(r, [file_path_1])
commit = porcelain.commit(r, b"Foo")

with open(file_path_2, "w") as fo:
    fo.write("Bar!")
os.remove(file_path_1)
porcelain.add(r, [file_path_2, file_path_1])
porcelain.commit(r, b"Bar!")

dulwich.index.build_index_from_tree(r.path,
                                    r.index_path(),
                                    r.object_store,
                                    r[commit].tree)

oldtree = r[r[b'HEAD'].tree]
newtree = r[r[commit].tree]
for f in r.object_store.iter_tree_contents(oldtree.id):
    if f.path not in newtree:
        os.remove(os.path.join(r.path, f.path.decode()))

r[b'HEAD'] = commit
```

```
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        new file:   text2.txt

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    text2.txt
```

**Comment by jelmer** [comment]
FWIW I can reproduce this on Linux. I think the issue is that you don't just need to remove text2.txt from disk, but also from the index. E.g. after the os.remove call, add something like:

    del index[f.path]

You probably want to open the index before the loop with something like:

    index = r.open_index()

and then save it after the loop with:

    index.write()

**Comment by MattSable** [comment]
That worked!
