### ISSUE TITLE
porcelain.clone raises DeprecationWarning

### ISSUE THREAD

**Issue by samuelharmer** [jelmer/dulwich#590]
[`porcelain.clone`](https://github.com/jelmer/dulwich/blob/4ca089c69ef9e5d34d043fec453526946d491bf4/dulwich/porcelain.py#L268) raises two `DeprecationWarning`s when called. They stem from `remote_refs.items` on lines [313](https://github.com/jelmer/dulwich/blob/4ca089c69ef9e5d34d043fec453526946d491bf4/dulwich/porcelain.py#L313) and [317](https://github.com/jelmer/dulwich/blob/4ca089c69ef9e5d34d043fec453526946d491bf4/dulwich/porcelain.py#L317).

**Comment by jelmer** [comment]
On Sat, Dec 02, 2017 at 11:18:27AM +0000, Samuel Harmer wrote:
> [`porcelain.clone`](https://github.com/jelmer/dulwich/blob/4ca089c69ef9e5d34d043fec453526946d491bf4/dulwich/porcelain.py#L268) raises two `DeprecationWarning`s when called. They stem from `remote_refs.items` on lines [313](https://github.com/jelmer/dulwich/blob/4ca089c69ef9e5d34d043fec453526946d491bf4/dulwich/porcelain.py#L313) and [317](https://github.com/jelmer/dulwich/blob/4ca089c69ef9e5d34d043fec453526946d491bf4/dulwich/porcelain.py#L317).
Thanks, fixed in master.

-- 
Jelmer Vernooĳ <jelmer@jelmer.uk>
PGP Key: https://www.jelmer.uk/D729A457.asc
