### ISSUE TITLE
porcelain.clone()/.pull()

### ISSUE THREAD

**Issue by n0way0ut** [jelmer/dulwich#591]
is it possible to redirect the output of porcelain.clone() and .pull() to os.devnull? outstream param is not supported or is not working.

**Comment by jelmer** [comment]
On Sat, Dec 02, 2017 at 10:15:45PM +0000, nvm wrote:
> is it possible to redirect the output of porcelain.clone() and .pull() to os.devnull? outstream param is not supported or is not working.
There's also errstream. Is that perhaps what you're looking for?

-- 
Jelmer Vernooĳ <jelmer@jelmer.uk>
PGP Key: https://www.jelmer.uk/D729A457.asc

**Comment by n0way0ut** [comment]
with errstream I still see:
$ ./clone.py
Counting objects: 5756, done.
Total 5756 (delta 0), reused 0 (delta 0), pack-reused 5756

$ ./pull.py
   porcelain.pull(l_path, r_path, b'refs/heads/master', errstream=f)
  File "/usr/lib/python3.6/site-packages/dulwich/porcelain.py", line 818, in pull
    path, r, progress=errstream.write, determine_wants=determine_wants)
  File "/usr/lib/python3.6/site-packages/dulwich/client.py", line 363, in fetch
    progress)
  File "/usr/lib/python3.6/site-packages/dulwich/client.py", line 1420, in fetch_pack
    progress)
  File "/usr/lib/python3.6/site-packages/dulwich/client.py", line 605, in _handle_upload_pack_tail
    SIDE_BAND_CHANNEL_PROGRESS: progress}
  File "/usr/lib/python3.6/site-packages/dulwich/client.py", line 448, in _read_side_band64k_data
    cb(pkt)
TypeError: write() argument must be str, not bytes

where f is just open(os.devnull, 'w')

**Comment by jelmer** [comment]
On Sun, Dec 03, 2017 at 06:14:10PM +0000, nvm wrote:
> with errstream I still see:
> $ ./clone.py
> Counting objects: 5756, done.
> Total 5756 (delta 0), reused 0 (delta 0), pack-reused 5756
> 
> $ ./pull.py
>    porcelain.pull(l_path, r_path, b'refs/heads/master', errstream=f)
>   File "/usr/lib/python3.6/site-packages/dulwich/porcelain.py", line 818, in pull
>     path, r, progress=errstream.write, determine_wants=determine_wants)
>   File "/usr/lib/python3.6/site-packages/dulwich/client.py", line 363, in fetch
>     progress)
>   File "/usr/lib/python3.6/site-packages/dulwich/client.py", line 1420, in fetch_pack
>     progress)
>   File "/usr/lib/python3.6/site-packages/dulwich/client.py", line 605, in _handle_upload_pack_tail
>     SIDE_BAND_CHANNEL_PROGRESS: progress}
>   File "/usr/lib/python3.6/site-packages/dulwich/client.py", line 448, in _read_side_band64k_data
>     cb(pkt)
> TypeError: write() argument must be str, not bytes
> 
> where f is just open(os.devnull, 'w')
You'd need to pass in something that allows writing bytes. In the case
of opening devnull, use 'wb' rather than 'w'.

Jelmer

-- 
Jelmer Vernooĳ <jelmer@jelmer.uk>
PGP Key: https://www.jelmer.uk/D729A457.asc

**Comment by n0way0ut** [comment]
it works, thanks
