### ISSUE TITLE
cloning a github repo without '.git' at the end fails

### ISSUE THREAD

**Issue by MattSable** [jelmer/dulwich#592]
The following fails

```
from dulwich import porcelain
porcelain.clone("https://github.com/jelmer/dulwich", "./foo")
```

with error:
```
  File "C:\Program Files\Python36\lib\site-packages\dulwich\client.py", line 1264, in _http_request
    raise NotGitRepository()
dulwich.errors.NotGitRepository
```

It works if you add .git at the end like:  `https://github.com/jelmer/dulwich.git`

Trying to do `git clone https://github.com/jelmer/dulwich ./foo` works fine though, so i'd expect porcelain to handle it as well.

**Comment by jelmer** [comment]
I can't reproduce this with Python3 on Linux, it works fine here. What version of Dulwich are you using?

**Comment by rockkickerdeluxe** [comment]
Updated to 0.18.6 and this got fixed!

**Comment by MattSable** [comment]
Updated to 0.18.6 and this was fixed!
