### ISSUE TITLE
Constructing an SSH client from a full URL is a pain

### ISSUE THREAD

**Issue by detly** [jelmer/dulwich#595]
Say I have an SSH URL from Gitlab's API like: `gitlab@gitlab.something.net:detly/some-project.git` (accessed via the `Gitlab.getproject()` dict result with key `ssh_url_to_repo`). It's not trivial to get this into a a form that Dulwich will accept.

My first attempt was:

```python
dulwich.client.SSHGitClient.from_parsedurl(
        urllib.parse.urlparse('ssh://{:s}'.format(gitlab_ssh_url))
    )
```

But this fails because `urlparse()` thinks `detly` is the port:

```text
(Pdb) urllib.parse.urlparse('ssh://{:s}'.format(gitlab_ssh_url)).port
*** ValueError: invalid literal for int() with base 10: 'detly'
```

At this point I think I have to parse it myself, or at least modify the parse output. There is also the package `git-url-parse` but I haven't tried it yet.

**Comment by jelmer** [comment]
The function you probably want is get_transport_and_path, it accepts this kind of location string.

See https://www.dulwich.io/apidocs/dulwich.client.html#get_transport_and_path

Note that the location string you mention is not a proper URL, it's a git-specific location specifier.

On 19 December 2017 01:06:40 GMT+03:00, Jason Heeris <notifications@github.com> wrote:
>Say I have an SSH URL from Gitlab's API like:
>`gitlab@gitlab.something.net:detly/some-project.git` (accessed via the
>`Gitlab.getproject()` dict result with key `ssh_url_to_repo`). It's not
>trivial to get this into a a form that Dulwich will accept.
>
>My first attempt was:
>
>```python
>dulwich.client.SSHGitClient.from_parsedurl(
>        urllib.parse.urlparse('ssh://{:s}'.format(gitlab_ssh_url))
>    )
>```
>
>But this fails because `urlparse()` thinks `detly` is the port:
>
>```text
>(Pdb) urllib.parse.urlparse('ssh://{:s}'.format(gitlab_ssh_url)).port
>*** ValueError: invalid literal for int() with base 10: 'detly'
>```
>
>At this point I think I have to parse it myself, or at least modify the
>parse output. There is also the package `git-url-parse` but I haven't
>tried it yet.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jelmer/dulwich/issues/595

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by detly** [comment]
> Note that the location string you mention is not a proper URL, it's a git-specific location specifier.

True. I did try [`git-url-parse`](https://git-url-parse.readthedocs.io/en/latest/) (not `giturlparse`!) after all and it worked fine:

```python
# gitlab_info is my own class, not Gitlab's API.
parsed_ssh_url = giturlparse.parse(gitlab_info.ssh)

client = dulwich.client.SSHGitClient(
    parsed_ssh_url.resource,
    username=parsed_ssh_url.user,
)

client.send_pack(
    parsed_ssh_url.pathname,
    refs_to_send,
    repo.object_store.generate_pack_contents
)
```

**Comment by detly** [comment]
Using `get_transport_and_path_from_url()` I have the same problem with the username being mistaken for the port.

**Comment by detly** [comment]
Personally, if it's not a "standard" URL (although I think there is an RFC for it somewhere?) it'd be perfectly valid to leave it to a 3rd party library for parsing it. I'd be fine with that. Obviously it's up to what your intent and user's expectations are.

**Comment by jelmer** [comment]
get_transport_and_path(), not get_transport_and_path_from_url(). 
The latter only accepts URLs (as defined by the RFC and implemented by python's urlparse), the former accepts both.

On 20 December 2017 02:16:42 GMT+03:00, Jason Heeris <notifications@github.com> wrote:
>Using `get_transport_and_path_from_url()` I have the same problem with
>the username being mistaken for the port.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/jelmer/dulwich/issues/595#issuecomment-352916064

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by detly** [comment]
Ah oops. Yes this works too! Saves me a dependency.
