### ISSUE TITLE
Get Active Branch

### ISSUE THREAD

**Issue by dufferzafar** [jelmer/dulwich#596]
There is `dulwich.porcelain.branch_list()` but that will list all branches for a repo.

How does one get the active branch? (the one displayed when you run `git status`)

**Comment by jelmer** [comment]
Try something like:

     >>> from dulwich.repo import Repo
     >>> Repo('.').refs.follow(b'HEAD')
     (['HEAD', 'refs/heads/master'], '4349a6e7e86d3566678657dfe4719b8a026293d9')
