### ISSUE TITLE
Porcelain Commit Error: 'name': KeyError

### ISSUE THREAD

**Issue by marcuswl345** [jelmer/dulwich#602]
Hi,

I get the following error when I try to run the **porcelain.commit** command

`'name': KeyError
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 47, in lambda_handler
    porcelain.commit(repo="/tmp/repo", message=b"A sample commit")
  File "/var/task/dulwich/porcelain.py", line 236, in commit
    return r.do_commit(message=message, author=author, committer=committer)
  File "/var/task/dulwich/repo.py", line 590, in do_commit
    committer = self._get_user_identity()
  File "/var/task/dulwich/repo.py", line 521, in _get_user_identity
    config.get((b"user", ), b"email") + b">")
  File "/var/task/dulwich/config.py", line 430, in get
    raise KeyError(name)
KeyError: 'name'`

Here is my code
````
    # Clones Repo 
    r = porcelain.clone(client_repo, "/tmp/repo/")
    
    # Copies env
    shutil.copytree("/tmp/repo/" + event["old_env"], "/tmp/repo/" + event["new_env"])
    
    # Pushes to github
    porcelain.add(repo="/tmp/repo", paths="/tmp/repo")
    ########### error occurs here #########
    porcelain.commit(repo="/tmp/repo", message=b"A sample commit")
    ##################################
    porcelain.push("/tmp/repo", "https://" + os.environ["TOKEN"] + ":x-oauth-basic@github.com/" + os.environ["CLIENT_REPO"] + ".git", "master")
    return "Success"
````

I'm using python 2.7 and dulwich 18.6

**Comment by jelmer** [comment]
This is happening because you don't have a username and email configured in .git/config or ~/.gitconfig.

I recently added some logic to have Dulwich default to $USER@$HOST, like C git does.

Can you try again with current master?

On 9 January 2018 12:43:03 GMT+08:00, marcuswl345 <notifications@github.com> wrote:
>Hi,
>
>I get the following error when I try to run the **porcelain.commit**
>command
>
>`'name': KeyError
>Traceback (most recent call last):
>  File "/var/task/lambda_function.py", line 47, in lambda_handler
>    porcelain.commit(repo="/tmp/repo", message=b"A sample commit")
>  File "/var/task/dulwich/porcelain.py", line 236, in commit
>return r.do_commit(message=message, author=author, committer=committer)
>  File "/var/task/dulwich/repo.py", line 590, in do_commit
>    committer = self._get_user_identity()
>  File "/var/task/dulwich/repo.py", line 521, in _get_user_identity
>    config.get((b"user", ), b"email") + b">")
>  File "/var/task/dulwich/config.py", line 430, in get
>    raise KeyError(name)
>KeyError: 'name'`
>
>Here is my code
>`# Clones Repo 
>    r = porcelain.clone(client_repo, "/tmp/repo/")
>    
>    # Copies env
>shutil.copytree("/tmp/repo/" + event["old_env"], "/tmp/repo/" +
>event["new_env"])
>    
>    # Pushes to github
>    porcelain.add(repo="/tmp/repo", paths="/tmp/repo")
>**porcelain.commit(repo="/tmp/repo", message=b"A sample commit")** <---
>error occurs here
>porcelain.push("/tmp/repo", "https://" + os.environ["TOKEN"] +
>":x-oauth-basic@github.com/" + os.environ["CLIENT_REPO"] + ".git",
>"master")
>    return "Success"`
>
>I'm using python 2.7 and dulwich 18.6
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jelmer/dulwich/issues/602

-- 
Jelmer Vernooĳ <jelmer@jelmer.uk>
https://www.jelmer.uk/

**Comment by marcuswl345** [comment]
Hi,

This is all done in an AWS lambda function so I don't have permission to add/modify any files expect in the /tmp/ folder.

I changed
`porcelain.commit(repo="/tmp/repo", message=b"A sample commit")`
to
`porcelain.commit(repo="/tmp/repo", message=b"A sample commit", author=b"AUTHOR", committer=b"COMMITTER")`

Where and it pushes successfully to the repo, but the repo seems to corrupted after
<img width="536" alt="screen shot 2018-01-12 at 9 18 48 am" src="https://user-images.githubusercontent.com/15118701/34850415-c48f3bde-f779-11e7-9503-f46d6eca9381.png">

This is a Github enterprise repo. Would that cause any issues?
Any other advice>

**Comment by jelmer** [comment]
You need it include an email address in the author and committee fields for them to be valid. E.g. committee=b"somebody <user@exomple.com>"

On 12 January 2018 06:21:54 GMT+08:00, marcuswl345 <notifications@github.com> wrote:
>Hi,
>
>This is all done in an AWS lambda function so I don't have permission
>to add/modify any files expect in the /tmp/ folder.
>
>I changed
>`porcelain.commit(repo="/tmp/repo", message=b"A sample commit")`
>to
>`porcelain.commit(repo="/tmp/repo", message=b"A sample commit",
>author=b"AUTHOR", committer=b"COMMITTER")`
>
>Where and it pushes successfully to the repo, but the repo seems to
>corrupted after
><img width="536" alt="screen shot 2018-01-12 at 9 18 48 am"
>src="https://user-images.githubusercontent.com/15118701/34850415-c48f3bde-f779-11e7-9503-f46d6eca9381.png">
>
>This is a Github enterprise repo. Would that cause any issues?
>Any other advice>
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/jelmer/dulwich/issues/602#issuecomment-357080788

-- 
Jelmer Vernooĳ <jelmer@jelmer.uk>
https://www.jelmer.uk/

**Comment by jelmer** [comment]
I've pushed a change to raise an exception on invalid user identities to master.

**Comment by marcuswl345** [comment]
Thanks for your help
