### ISSUE TITLE
checkout a branch/head to another directory

### ISSUE THREAD

**Issue by DeaconDesperado** [jelmer/dulwich#68]
I've seen this approach used before to automate a push to remote to update a site.

http://toroid.org/ams/git-website-howto

I'd like to use dulwich in some of our deploy fabric scripts to make this process a little saner and not rely on a repo embedded with the production code with fixed paths.

I know the `checkout` method that was patched in is intended only for freshly cloned repos to checkout the master branch.  Is it possible to call `checkout` with a path that will move through the objects in a branch and output the entire structure to a target directory?  If not, is this something I could volunteer some work on?

**Comment by jonashaag** [comment]
I'd like to have this reopened. The `build_index_from_tree` API is too difficult to use. To make thing worse, if your repository has got submodules, you'll have to add quite some code to ignore these from being copied over.

Cloning an arbitrary tree to some directory should be as easy as calling `repo.clone(..., tree=my_tree_id)` or `repo.clone(..., head=my_commit)`.

**Comment by jelmer** [comment]
On Mon, Sep 07, 2015 at 03:44:20PM -0700, Jonas Haag wrote:
> I'd like to have this reopened. The `build_index_from_tree` API is too difficult to use. To make thing worse, if your repository has got submodules, you'll have to add quite some code to ignore these from being copied over.
> 
> Cloning an arbitrary tree to some directory should be as easy as calling `repo.clone(..., tree=my_tree_id)` or `repo.clone(..., head=my_commit)`.

Right now the following should be sufficient:

build_tree_from_indeX(target_path, repo.index_path(), repo.object_store(), my_tree_id)

Are you just looking for a convenience wrapper around that on Repo?

Cheers,

Jelmer
