### ISSUE TITLE
dul-receive-pack doesn't match git-receive-pack

### ISSUE THREAD

**Issue by JonChu** [jelmer/dulwich#71]
When running dul-receive-pack on a repository I get this output:

005a23b87ffabd30448e05e1e28cafa660e4580fbb3a HEADreport-status delete-refs side-band-64k
004023b87ffabd30448e05e1e28cafa660e4580fbb3a refs/heads/branch2
003f5130a31543f90c68636a676e203ba2a975b713e7 refs/heads/master
0000

Whereas, git-receive-pack gives:
007923b87ffabd30448e05e1e28cafa660e4580fbb3a refs/heads/branch2 report-status delete-refs side-band-64k quiet ofs-delta
003f5130a31543f90c68636a676e203ba2a975b713e7 refs/heads/master
0000

I'm not sure if the extra line describing HEAD is an issue. However, the missing space between HEAD and report-status should cause the send-pack process to parse the capabilities incorrectly.

**Comment by jelmer** [comment]
The extra space is now included in master.
