### ISSUE TITLE
Possible recursion loop in dulwich

### ISSUE THREAD

**Issue by marcinkuzminski** [jelmer/dulwich#81]
I have an odd case from one of RhodeCode users, attached a stacktrace from call that causes a RuntimeError exception in dulwich code. I could not reproduce this, and i don't have any access to repo that is causing this.

```
>>  app_iter = self.application(environ, sr_checker)
Module beaker.middleware:155 in __call__
>>  return self.wrap_app(environ, session_start_response)
Module routes.middleware:131 in __call__
>>  response = self.app(environ, start_response)
Module pylons.wsgiapp:107 in __call__
>>  response = self.dispatch(controller, environ, start_response)
Module pylons.wsgiapp:312 in dispatch
>>  return controller(environ, start_response)
Module rhodecode.lib.base:287 in __call__
>>  return WSGIController.__call__(self, environ, start_response)
Module pylons.controllers.core:211 in __call__
>>  response = self._dispatch_call()
Module pylons.controllers.core:162 in _dispatch_call
>>  response = self._inspect_call(func)
Module pylons.controllers.core:105 in _inspect_call
>>  result = self._perform_call(func, args)
Module pylons.controllers.core:57 in _perform_call
>>  return func(**args)
Module rhodecode.controllers.summary:141 in index
>>  run_task(get_commits_stats, c.dbrepo.repo_name, ts_min_y, ts_max_y)
Module rhodecode.lib.celerylib:79 in run_task
>>  return ResultWrapper(task(*args, **kwargs))
Module celery.task.base:241 in __call__
>>  return self.run(*args, **kwargs)
Module celery.app:141 in run
>>  return fun(*args, **kwargs)
Module rhodecode.lib.celerylib.tasks:2 in get_commits_stats
Module rhodecode.lib.celerylib:122 in __wrapper
>>  ret = func(*fargs, **fkwargs)
Module rhodecode.lib.celerylib.tasks:171 in get_commits_stats
>>  datadict["added"] += len(cs.added)
Module rhodecode.lib.vcs.utils.lazy:27 in __get__
>>  result = obj.__dict__[self.__name__] = self._func(obj)
Module rhodecode.lib.vcs.backends.git.changeset:522 in added
>>  self._get_paths_for_status('added')], self)
Module rhodecode.lib.vcs.backends.git.changeset:507 in _get_paths_for_status
>>  a, m, d = self._changes_cache
Module rhodecode.lib.vcs.utils.lazy:27 in __get__
>>  result = obj.__dict__[self.__name__] = self._func(obj)
Module rhodecode.lib.vcs.backends.git.changeset:492 in _changes_cache
>>  for (oldpath, newpath), (_, _), (_, _) in changes:
Module dulwich.object_store:142 in tree_changes
>>  want_unchanged=want_unchanged):
Module dulwich.diff_tree:183 in tree_changes
>>  for entry1, entry2 in entries:
Module dulwich.diff_tree:148 in walk_trees
>>  tree1 = is_tree1 and store[entry1.sha] or None
Module dulwich.object_store:112 in __getitem__
>>  type_num, uncomp = self.get_raw(sha)
Module dulwich.object_store:333 in get_raw
>>  return pack.get_raw(sha)
Module dulwich.pack:1844 in get_raw
>>  type_num, chunks = self.data.resolve_object(offset, obj_type, obj)
Module dulwich.pack:1055 in resolve_object
>>  type, base_chunks = self.resolve_object(base_offset, type, base_obj)
Module dulwich.pack:1055 in resolve_object
>>  type, base_chunks = self.resolve_object(base_offset, type, base_obj)
...
Module dulwich.pack:1055 in resolve_object
>>  type, base_chunks = self.resolve_object(base_offset, type, base_obj)
Module dulwich.pack:1055 in resolve_object
>>  type, base_chunks = self.resolve_object(base_offset, type, base_obj)
Module dulwich.pack:1055 in resolve_object
>>  type, base_chunks = self.resolve_object(base_offset, type, base_obj)
Module dulwich.pack:1055 in resolve_object
>>  type, base_chunks = self.resolve_object(base_offset, type, base_obj)
Module dulwich.pack:1055 in resolve_object
>>  type, base_chunks = self.resolve_object(base_offset, type, base_obj)
Module dulwich.pack:1062 in resolve_object
>>  self._offset_cache[offset] = type, chunks
Module dulwich.lru_cache:198 in __setitem__
>>  self.add(key, value, cleanup=None)
Module dulwich.lru_cache:330 in add
>>  node = _LRUNode(key, value, cleanup=cleanup)
RuntimeError: maximum recursion depth exceeded

```

But i think we can ask question to this user undere here: https://bitbucket.org/marcinkuzminski/rhodecode/issue/642/

**Comment by ArminGruner** [comment]
I think the problem might still be there:

Using hg 3.4.1,
hg-git 0.8.1 and and dulwich 0.10.1.a,
I get:

$ hg clone git+https://github.com/freebsd/freebsd.git

[...]
  File "/usr/local/lib/python2.7/site-packages/dulwich/pack.py", line 1329, in _follow_chain
    new_offset, unpacked.obj_type_num, unpacked.obj_chunks):
  File "/usr/local/lib/python2.7/site-packages/dulwich/pack.py", line 1329, in _follow_chain
    new_offset, unpacked.obj_type_num, unpacked.obj_chunks):
  File "/usr/local/lib/python2.7/site-packages/dulwich/pack.py", line 1329, in _follow_chain
    new_offset, unpacked.obj_type_num, unpacked.obj_chunks):
  File "/usr/local/lib/python2.7/site-packages/dulwich/pack.py", line 1329, in _follow_chain
    new_offset, unpacked.obj_type_num, unpacked.obj_chunks):
  File "/usr/local/lib/python2.7/site-packages/dulwich/pack.py", line 1329, in _follow_chain
    new_offset, unpacked.obj_type_num, unpacked.obj_chunks):
  File "/usr/local/lib/python2.7/site-packages/dulwich/pack.py", line 1322, in _follow_chain
    unpacked = self._resolve_object(offset, obj_type_num, base_chunks)
  File "/usr/local/lib/python2.7/site-packages/dulwich/pack.py", line 1308, in _resolve_object
    compute_crc32=self._compute_crc32)
  File "/usr/local/lib/python2.7/site-packages/dulwich/pack.py", line 721, in unpack_object
    unpacked = UnpackedObject(type_num, delta_base, size, crc32)
RuntimeError: maximum recursion depth exceeded

**Comment by jelmer** [comment]
On Thu, Jun 18, 2015 at 10:42:11AM -0700, ArminGruner wrote:
> I think the problem might still be there:
> 
> Using hg 3.4.1,
> hg-git 0.8.1 and and dulwich 0.10.1.a,
> I get:
> 
> $ hg clone git+https://github.com/freebsd/freebsd.git
> 
> [...]
>   File "/usr/local/lib/python2.7/site-packages/dulwich/pack.py", line 1329, in _follow_chain
>     new_offset, unpacked.obj_type_num, unpacked.obj_chunks):
>   File "/usr/local/lib/python2.7/site-packages/dulwich/pack.py", line 1329, in _follow_chain
>     new_offset, unpacked.obj_type_num, unpacked.obj_chunks):
>   File "/usr/local/lib/python2.7/site-packages/dulwich/pack.py", line 1329, in _follow_chain
>     new_offset, unpacked.obj_type_num, unpacked.obj_chunks):
>   File "/usr/local/lib/python2.7/site-packages/dulwich/pack.py", line 1329, in _follow_chain
>     new_offset, unpacked.obj_type_num, unpacked.obj_chunks):
>   File "/usr/local/lib/python2.7/site-packages/dulwich/pack.py", line 1329, in _follow_chain
>     new_offset, unpacked.obj_type_num, unpacked.obj_chunks):
>   File "/usr/local/lib/python2.7/site-packages/dulwich/pack.py", line 1322, in _follow_chain
>     unpacked = self._resolve_object(offset, obj_type_num, base_chunks)
>   File "/usr/local/lib/python2.7/site-packages/dulwich/pack.py", line 1308, in _resolve_object
>     compute_crc32=self._compute_crc32)
>   File "/usr/local/lib/python2.7/site-packages/dulwich/pack.py", line 721, in unpack_object
>     unpacked = UnpackedObject(type_num, delta_base, size, crc32)
> RuntimeError: maximum recursion depth exceeded

FWIW I can reproduce this with 'dulwich clone' too.

Jelmer

**Comment by jelmer** [comment]
Properly fixed in HEAD now.
