### ISSUE TITLE
http protocol error: git fetch_pack: expected ACK/NAK, got 'dul-daemon says what'

### ISSUE THREAD

**Issue by asaladin** [jelmer/dulwich#88]
Hi,

This description follows the previous bug report on launchpad: https://bugs.launchpad.net/dulwich/+bug/953916

I've been able to reproduce the same error on a public git repository, so it can now easily be reproduced. 
I can reproduce this problem with at least two versions of dulwich: the current pypi version and the latest github master version at 2a8548be3b1fd4a (Dec 04, 2012). 

It happens during a git pull operation of a repository served by http.
Here are the steps to reproduce:

```
$ cd /tmp 
$ git clone https://github.com/asaladin/testdul_repo.git ptools
$ git clone https://github.com/asaladin/testdul_git2.git git2

$ cat test_dulwich/test_dulwich.py
##################
from dulwich.repo import Repo
from dulwich.web import HTTPGitApplication
from dulwich import server as dulserver

repo_path = "/tmp/ptools"

_d = {'/repo' : Repo(repo_path)}
backend = dulserver.DictBackend(_d)
gitserve = HTTPGitApplication(backend)

def app(environ, start_response):
   return gitserve(environ, start_response)
##################

#run on another shell with: $ gunicorn test_dulwich:app
$ cd git2
$ git pull http://localhost:8000/repo 
fatal: git fetch_pack: expected ACK/NAK, got 'dul-daemon says what'
```

cheers,

**Comment by jelmer** [comment]
Fixed in master.
