### ISSUE TITLE
test_watch (dulwich.tests.test_refs.DiskRefsContainerTests) hangs

### ISSUE THREAD

**Issue by sbraz** [jelmer/dulwich#886]
Hi,
`test_watch (dulwich.tests.test_refs.DiskRefsContainerTests)` is failing on my Gentoo system with Python 3.8, 3.9 and 3.10 (pyinotify v0.9.6). Strangely enough, `test_watch (dulwich.tests.test_refs.DictRefsContainerTests)` passes.

This is the line that hangs: https://github.com/dulwich/dulwich/blob/9dcec52ee5a4def69fda6f9700689c334eceab1d/dulwich/tests/test_refs.py#L367

If I run `strace -f python -m unittest -v dulwich/tests/test_refs.py`, I see
```
[pid 31867] newfstatat(AT_FDCWD, "/tmp/tmp3dt4pq4v/refs.git/refs/remotes/origin/other", {st_mode=S_IFREG|0755, st_size=41, ...}, 0) = 0
[pid 31867] poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}], 2, -1
```

Writing to the file (`touch /tmp/tmp3dt4pq4v/refs.git/refs/remotes/origin/other`) causes the tests to pass.

I guess there is a race condition here but I'm unable to reproduce inside a Docker container. Do you have any idea what could be happening?

**Comment by jelmer** [comment]
Something similar was recently reported when running with pytest. https://github.com/dulwich/dulwich/issues/874

Did you have pyinotify installed on the docker image? The test is a noop in other situations.

It is likely to be a race condition of some sort; we're making changes to a file and then waiting for those to show up.

**Comment by sbraz** [comment]
Hi Jelmer,
>Something similar was recently reported when running with pytest. #874

Yes I noticed that report. I have also tried pytest because it is easier to select tests with it.

> Did you have pyinotify installed on the docker image? The test is a noop in other situations.

I installed it and it passed just fine (it wasn't skipped if that is what you meant).

> It is likely to be a race condition of some sort; we're making changes to a file and then waiting for those to show up.

But don't we set the watches before modifying the file? That's what I don't really understand.

**Comment by jelmer** [comment]
I've disabled this particular test for now.
