### ISSUE TITLE
How to remove a remote?

### ISSUE THREAD

**Issue by dAnjou** [jelmer/dulwich#923]
Hi,

I'm writing a piece of code that dynamically creates a new remote repo and I'm using `porcelain.remote_add` to add it as a remote to the current repo.

That works fine the first time. But it fails the second time because the remote already exists.

Is there a way to delete a remote?

Thanks!

**Comment by jessecureton-aurora** [comment]
You can modify the repo's config directly, that's what `porcelain.remote_add` does under the hood.

Here's a quick example of both manually adding & manually removing a remote, though obviously you'll also want to handle errors, utf-8 encode/decode, etc. 

Manually adding a remote:
```python
remote_name = b"origin"
remote_url = b"git@github.com/example/example.git"

config = repo.get_config()
config.set((b"remote", remote_name), b"url", remote_url)
config.write_to_path()
```

Manually removing a remote:
```python
remote_name = b"origin"

config = repo.get_config()
del config[(b"remote", remote_name)]
config.write_to_path()
```

**Comment by jelmer** [comment]
Thanks, Jesse - that's indeed the only way to remove a remote at the moment.

If somebody was interested in contributing a porcelain.remote_remove() command based on Jesse's code, that'd be very welcome.
