### ISSUE TITLE
Repo config not available when in linked working tree

### ISSUE THREAD

**Issue by jessecureton-aurora** [jelmer/dulwich#926]
## Expected Behavior

When working inside a linked working tree, the repo's config should be common across both the main working tree and any linked working trees. Use of separate configs in a linked working tree is a git extension, and documentation of the expected config commonality is available in the [git-worktree docs](https://git-scm.com/docs/git-worktree#_configuration_file)

## Actual Behavior

When a `dulwich.repo.Repo` is created referencing a linked working tree, a call to `repo.get_config()` returns an empty `ConfigFile` object.

This is because the implementation of `get_config()` attempts to read the config file from `repo._controldir / config`, which is unique to the linked tree and does not exist. I believe `get_config()` should instead read from `repo._commondir / config`, which is shared with the main tree. This behavior would match the git-worktree docs linked above.

## Steps to Reproduce the Problem

This code is a minimal reproduction of the issue.

```python
from dulwich.repo import Repo
from dulwich import porcelain
from pathlib import Path

import shutil

ROOT = Path("/tmp/config-reprod")
if ROOT.exists():
    shutil.rmtree(ROOT)
ROOT.mkdir()

TEST_REPO = ROOT / "repo"
TEST_REPO.mkdir()
TEST_REPO_WT = ROOT / "repo_wt"
TEST_REPO_WT.mkdir()

origin_url = "git@github.com/example/example.git"

# Set up a repo and a worktree
repo = porcelain.init(TEST_REPO)
porcelain.commit(repo, b"Initial commit")
repo_wt = Repo._init_new_working_directory(TEST_REPO_WT, repo)

# Set a remote in the config for the main repo
porcelain.remote_add(repo, "origin", origin_url)

# Print configs in both the main- and linked-worktrees
print("Main tree has config:")
print(repo.get_config())

print("\nLinked tree has config:")
print(repo_wt.get_config())
```

This produces the following output, which shows the linked worktree has an empty config object.

```
Main tree has config:
ConfigFile(CaseInsensitiveDict([((b'core',), CaseInsensitiveDict([(b'repositoryformatversion', b'0'), (b'filemode', b'true'), (b'bare', b'false'), (b'logallrefupdates', b'true')])), ((b'remote', b'origin'), CaseInsensitiveDict([(b'url', b'git@github.com/example/example.git')]))]))

Linked tree has config:
ConfigFile(CaseInsensitiveDict())
```

**Comment by jessecureton-aurora** [comment]
For what it's worth, simply changing the `Repo.get_config()` implementation to reference `self._commondir` instead passes all existing tests, and gives the expected behavior on the example script I gave above.

**Comment by jelmer** [comment]
I think there are two issues here:

1) dulwich should refuse to open repositories that have extensions present that it doesn't support, like this one
2) dulwich should ideally support this particular extension, but when that extension is not present it should keep the current behaviour

it's not cmpletely clear to me whether it should *just* be reading the configuration from the working tree or from both the working tree and the common dir, where values from the former override the latter.

PRs to address any of these issues would be very much welcome.

**Comment by jessecureton-aurora** [comment]
Agreed on the first point, support for configs in a linked worktree I think is a separate issue. For your second point, I do think that the current behavior should change to match the Git CLI. I don't actually have any extensions enabled right now, I'm just looking for the same behavior as Git when referencing a remote in a linked tree.

If you run the above code and then do a `git remote -v` inside both test directories, the output is the same in both. Git currently does reference the main tree's config by default in all linked trees.

**Comment by jelmer** [comment]
On Mon, Jan 24, 2022 at 05:25:33AM -0800, Jesse Cureton wrote:
> Agreed on the first point, support for configs in a linked worktree I think is a separate issue. For your second point, I do think that the current behavior should change to match the Git CLI. I don't actually have any extensions enabled right now, I'm just looking for the same behavior as Git when referencing a remote in a linked tree.
> 
> If you run the above code and then do a `git remote -v` inside both test directories, the output is the same in both. Git currently does reference the main tree's config by default in all linked trees.

I agree that we should match the behaviour of the git command line;
maybe I was misunderstanding the original report.

-- 
Jelmer Vernooĳ ***@***.***>
PGP Key: https://www.jelmer.uk/D729A457.asc

**Comment by jessecureton-aurora** [comment]
Thanks Jelmer! I will put together a PR for this soon!

**Comment by jessecureton-aurora** [comment]
Hi @jelmer, I've put together a PR fixing this issue in #949. Looking forward to your review and getting this landed!

**Comment by jelmer** [comment]
Merged, thanks!
