### ISSUE TITLE
Import Error on notebook environment

### ISSUE THREAD

**Issue by Lothiraldan** [jelmer/dulwich#950]
Hello, when trying to import latest dulwich version (0.22.33), the import fails with an AttributeError:

```
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_756805/2729115134.py in <module>
----> 1 import dulwich.porcelain

~/.virtualenv/lib/python3.7/site-packages/dulwich/porcelain.py in <module>
    832 
    833 
--> 834 def diff_tree(repo, old_tree, new_tree, outstream=sys.stdout.buffer):
    835     """Compares the content and mode of blobs found via two tree objects.
    836 

AttributeError: 'OutStream' object has no attribute 'buffer'
```

It looks like `sys.stdout` has no 'buffer' attribute.

Would changing the outstream default argument in here https://github.com/jelmer/dulwich/blame/master/dulwich/porcelain.py#L835 to default_bytes_out_stream (https://github.com/jelmer/dulwich/blob/master/dulwich/porcelain.py#L173) would be the right approach to fix it? I would be happy to send a PR if that is the case.

Cheers and thanks again for your good work! :raised_hands:

**Comment by jelmer** [comment]
Sorry for breaking this.

Using default_out_stream here would be reasonable. Would you mind creating a PR that did that?

**Comment by Lothiraldan** [comment]
Sure, no problem, here you go: https://github.com/jelmer/dulwich/pull/951

**Comment by jelmer** [comment]
Merged, thanks!

**Comment by jelmer** [comment]
I'll try to do a new release soon.

Unfortunately since there is no CI for jupyter, it's likely we'll break this again at some point in the future. 

It would be great if somebody could contribute a test to verify that things haven't broken on jupyter.

**Comment by yakutovicha** [comment]
> It would be great if somebody could contribute a test to verify that things haven't broken on jupyter.

We've developed a GH action that is designed for testing notebooks: https://github.com/aiidalab/aiidalab-test-app-action.

I have no time to work on it now, but it is pretty straightforward to use. Feel free to incorporate it into your tests suite.
