### ISSUE TITLE
Bug in porcelain clone function not passing kwargs for client 

### ISSUE THREAD

**Issue by nokeechia** [jelmer/dulwich#954]
Hi,

 

There seems to be a bug in the porcelain clone function.

The clone function takes in kwargs, but these are not passed to the get_transport_and_path

(https://github.com/jelmer/dulwich/blob/master/dulwich/porcelain.py#L441)

The get_transport_and_path still has the possibility of passing the kwargs, it is just that the clone function does not pass it.

You can see further implementations in ls_remote(https://github.com/jelmer/dulwich/blob/master/dulwich/porcelain.py#L1537) and fetch (https://github.com/jelmer/dulwich/blob/master/dulwich/porcelain.py#L1521)

**Comment by jelmer** [comment]
Merged your PR - thanks! Closing this.
