### ISSUE TITLE
Release 0.20.38 missing wheels on PyPI

### ISSUE THREAD

**Issue by othi** [jelmer/dulwich#968]
Issue https://github.com/jelmer/dulwich/issues/963 seems to not have been fixed completely. Wheels are still missing on PyPI.

Just a heads up.

**Comment by dtrifiro** [comment]
Seems it's still not solved for 0.20.39:

https://github.com/jelmer/dulwich/runs/6509468969?check_suite_focus=true

**Comment by henriquegemignani** [comment]
Nor in 0.20.40: https://pypi.org/project/dulwich/0.20.40/#files
