### ISSUE TITLE
New dependency on python-dev breaking install

### ISSUE THREAD

**Issue by mtene** [jelmer/dulwich#970]
Starting with version 0.20.38, dulwich fails during pip install - gcc does not find Python.h.

pip install --force-reinstall dulwich==0.20.38
gcc ... -o build/temp.linux-x86_64-3.6/dulwich/_objects.o
    dulwich/_objects.c:22:10: fatal error: Python.h: No such file or directory
       22 | #include <Python.h>
          |          ^~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1

Version 0.20.37 succeeds.
This is apparently because of a new dependency on the python-dev package, which is not installed on my system (and I don't have rights to install it).
Is this a regression or intended and is there a resolution?

**Comment by jelmer** [comment]
This is because of a lack of wheels, not a new dependency. See #969
