### ISSUE TITLE
Website and Documentation Down

### ISSUE THREAD

**Issue by onerandomusername** [jelmer/dulwich#981]
The website and the docs are not responsive and cannot be used.

**Comment by jelmer** [comment]
Sorry about the delay, I didn't have access to fix this. Should be resolved now.

**Comment by jelmer** [comment]
On Thu, Jun 23, 2022 at 07:01:11PM -0700, arl wrote:
> The website and the docs are not responsive and cannot be used.
Sorry about that - should be resolved tomorrow.
